### ISSUE TITLE
latexml error on compilation: not showing missing latexml error message

### ISSUE THREAD

**Issue by PeterTKY** [metanorma/metanorma-standoc#101]
I'm glad that the Relaton error yesterday has gone. But it came to the latexml error (iso-digital-addressing repo):

> export GLOBIGNORE=sources/cc-19160-6.adoc; \
        mv sources/cc-19160-6.* documents; \
        unset GLOBIGNORE
FILENAME=sources/iso-19160-6.adoc; \
        echo "Compiling locally..."; bundle exec metanorma $FILENAME
Compiling locally...
Error: No such file or directory - latexml, 
Not sure what to run? try: metanorma help
make: *** [sources/iso-19160-6.xml] Error 2

**Comment by ronaldtse** [comment]
@PeterTKY you need to install latexml: `brew install latexml`

It's automatically installed if you use the Metanorma brew on macOS:

https://www.metanorma.com/author/topics/install/
```
brew tap metanorma/metanorma
brew install metanorma
```

**Comment by ronaldtse** [comment]
Please close if it works, thanks!

**Comment by ronaldtse** [comment]
That said, there should be a better error message on the missing latexml. Why is the error message not showing? @CAMOBAP795 ?

**Comment by ronaldtse** [comment]
@PeterTKY can you provide the installed metanorma-standoc version? Thanks!

**Comment by PeterTKY** [comment]
The installed commit is ec4c5665be991d31d5b24e1f72d79db790fa0873, which should be the latest as I just updated my bundle.

It works after installing latexml. Is latexml a new feature? Because I haven't encountered this error before...

**Comment by PeterTKY** [comment]
It would be great if there's a check whether the required dependencies/libraries have been installed instead of having to compile and wait and then it throws the error at runtime...

**Comment by CAMOBAP795** [comment]
@PeterTKY yes and no, some user don't need latexml at all, this is why we added warning instead of fatal error before compilation, but a fatal error on compilation

@PeterTKY How do you think about this approach?

**Comment by PeterTKY** [comment]
@CAMOBAP795 "Some user don't need latexml at all", that's our point of view as the developers of metanorma because we know what users need to compile. But from our users' point of view, they may not know what they need as they don't necessarily have the knowledge of how metanorma works behind the scene. Having the compilation error when generating the document will be quite scary and they may think it's a bug in our metanorma stack.

**Comment by ronaldtse** [comment]
@PeterTKY I agree but also there is an additional consideration -- for some people that have installed Metanorma before the dependency requirement (e.g. they installed 0.1 but now requires 0.2), they will be unable to compile the documents they used to unless they also upgrade the dependency.

Now I see the proper way of handling this:
- If the dependency is USED NOW -- then we should present a hard error ("You must upgrade/install Y to version FOO").
- If the dependency is NOT USED NOW, but has been detected to be OUTDATED -- we should present a soft error / warning ("Metanorma version X depends on version FOO, but you have BAR, please upgrade; you will encounter a hard error if `[latexmath]` blocks are used")

@CAMOBAP795 can you help follow up with this?

**Comment by CAMOBAP795** [comment]
@ronaldtse done https://github.com/metanorma/metanorma-standoc/pull/115

**Comment by CAMOBAP795** [comment]
Fixed regression in https://github.com/metanorma/metanorma-standoc/pull/119

**Comment by ronaldtse** [comment]
Fixed. Closing.
