### ISSUE TITLE
Update specs to reflect new Relaton output (master is now failing)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#103]
@CAMOBAP795 the specs rely on Relaton, which has recently changed.

UPDATE: actually this is wrong. Wait for  https://github.com/metanorma/relaton-iso/issues/65 to be fixed.

This is the diff for one of the specs (ISO 124):

```diff
<   <title type="title-main" format="text/plain" language="en" script="Latn"></title>
<   <title type="main" format="text/plain" language="en" script="Latn"></title>
---
>   <title type="title-intro" format="text/plain" language="en" script="Latn">Latex, rubber</title>
>   <title type="title-main" format="text/plain" language="en" script="Latn">Determination of total solids content</title>
>   <title type="main" format="text/plain" language="en" script="Latn">Latex, rubber - Determination of total solids content</title>
>   <title type="title-intro" format="text/plain" language="fr" script="Latn">Latex de caoutchouc</title>
>   <title type="title-main" format="text/plain" language="fr" script="Latn">Détermination des matières solides totales</title>
>   <title type="main" format="text/plain" language="fr" script="Latn">Latex de caoutchouc - Détermination des matières solides totales</title>
6a11
>   <docidentifier type="ISO">ISO 124:2014</docidentifier>
19a25
>   <language>fr</language>
21a28
>   <abstract format="text/plain" language="fr" script="Latn">L'ISO 124:2014 spécifie des méthodes pour la détermination des matières solides totales dans le latex de plantation, le latex de concentré de caoutchouc naturel et le latex de caoutchouc synthétique. Ces méthodes ne conviennent pas nécessairement au latex d'origine naturelle autre que celui de l'Hevea brasiliensis, au latex vulcanisé, aux mélanges de latex, ou aux dispersions artificielles de caoutchouc.</abstract>
```

The first part (the new parts) is wrong, Relaton is now missing the titles.

This section is also wrong (caused by https://github.com/metanorma/relaton-iso/issues/64), so please don't update this part (until the issue is resolved).

```diff
48,49c55,56
<     <structuredidentifier>
<       <project-number>?</project-number>
---
>     <structuredidentifier type="ISO">
>       <project-number>ISO 124</project-number>
```

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-standoc/pull/102#issuecomment-522655472_

**Comment by opoudjis** [comment]
Underlying issue is resolved: it was simply a matter of the metanorma-standoc VCR recordings being updated to reflect the new version of relaton-iso. Alex, you can proceed with this.

Ronald, I disagree that rspec tasks are what should be delegated from me to other people. I manage the metanorma stack, I do the releases, I do the testing before releases, *I need to know what is going wrong with the gems.* 

Please (a) only assign spec breakages for the metanorma stack to me in future; (b) don't assign tickets like these at all, because they are a nuisance: my BAU is to do this testing anyway.
