### ISSUE TITLE
Generalise translate-from from metanorma-iec to metanorma-standoc

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#105]
And insert any other summary relations that look useful.

**Comment by ronaldtse** [comment]
@opoudjis and what does `translate-from` accept: a reference document in free form text?

**Comment by opoudjis** [comment]
No, it takes a document identifier, in Relaton format. If it can find the document on relaton, good, otherwise it puts in a dummy bibitem with empty title and the nominated document identifier. We have already done this in NIST for obsoleting and superseding standards, and generically in metanorma-standoc for part-of identifiers.

**Comment by ronaldtse** [comment]
@opoudjis then we need to update metanorma.com, the current explanation of this document attribute does not provide this level of detail.

**Comment by ronaldtse** [comment]
> No, it's not a general solution, but a general solution won't come until you can attach relaton XML records to a document via an external bibliography.

i.e. Metanorma able to accept Relaton records (YAML, XML) in general via an external bibliography.

**Comment by ronaldtse** [comment]
> then we need to update metanorma.com, the current explanation of this document attribute does not provide this level of detail.

This is done in https://github.com/metanorma/metanorma.com/pull/121 now.
