### ISSUE TITLE
Consider whether we support multiple languages of text within the same document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#110]
Some standardization documents need to be presented in dual-languages. A prime example is ISO Guide 73, presented side by side in 2 columns in English and French.

ITU  documents can be in 6 official languages, and for various reasons it is useful to have them side by side allowing comparison.

There are also translations of Chinese standards into English (you can find such official submissions online, e.g., by SAC to ISO), there are also Chinese standards in English and German (the official bi-lateral standards recognition programs China-US and China-Germany).

We should support a single ADoc for multiple languages as well.

This is a generic task for StanDoc.

**Comment by opoudjis** [comment]
We have implemented concatenated documents in different languages.

God willing, we never have to implement side-by-side bilingual documents.

**Comment by opoudjis** [comment]
This has been partially implemented already in https://github.com/metanorma/isodoc/pull/508
