### ISSUE TITLE
Add line breaks to AsciiMath expressions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#111]
Seek to support, via AsciiMath:

* single equation that spans multiple lines
* multiple equations aligned at the middle operator

The former to be done presumably by introducing some sort of linebreak character within AsciiMath. This is already done in the Asciidoctor version of AsciiMath (though not prominently documented), with end of line backslash: https://github.com/asciidoctor/asciidoctor/issues/2497

https://www.dessci.com/en/products/mathplayer/tech/mathml3-lb-indent.htm

Need to establish that any MathML linebreaks will be respected in OOXML.

**Comment by opoudjis** [comment]
Asciidoctor rendering respects backslash + carriage return; the Asciidoctor to MathML converter, in asciimath, does not. So any manipulation of AsciiMath needs to happen as an intervention where that converter is called, from within Html2Doc.

**Comment by opoudjis** [comment]
Conversion of MathML to OOXML (example from https://www.dessci.com/en/products/mathplayer/tech/mathml3-lb-indent.htm) ignores MathML linebreak attributes.

Proceeding further with this is likely pointless, and will certainly require extensive research.

**Comment by ronaldtse** [comment]
Word apparently doesn't support multiple lines in one equation, but they support "Equation Alignment" across multiple equations.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/11865/65559683-329c2000-df6e-11e9-956b-cb80ddb74414.png">

**Comment by opoudjis** [comment]
In MathML that is supported via indentation attributes, which operates within a single equation, and *presupposes that line breaks work*.

I don't think this is feasible using MathML as our input mechanism.

**Comment by ronaldtse** [comment]
Agree. MathML input with line breaks won’t work for output into Word, unless we parse and manipulate the MathML heavily into OOXML.

**Comment by opoudjis** [comment]
Example: ITU, In G.650 recommendation, equation II-2, line breaks are used before each "=" sign:

https://user-images.githubusercontent.com/55683568/67639827-e9384b00-f8f4-11e9-9584-657da69411ec.png

**Comment by manuel489** [comment]
I have this case:

````
[%unnumbered]
[stem]
++++
D =_{"def"} D_1 xx D_2^** xx D_3 bb "-set" xx D_1 xx (D_1 uu D_2) xx ( D_1 xx D_2)^** xx (D_1 xx D_2) bb "-set" xx (D_1 uu D_2) bb "-set"]
++++
````
In HTML, the equation get out of boundaries (when the window is shrunk).

![capture5](https://user-images.githubusercontent.com/33627611/68349637-388c3180-00d4-11ea-8770-7fa23d48902a.JPG)

**Comment by opoudjis** [comment]
Of course, that's going to happen to your Math expression if you shrink your window, no matter what. 

It turns out that while MathML 2's `<mspace>` is sneered at in MathML 3, it works fine in MathJax, and is a simpler (and of course less sophisticated) rendering of a line break. The mspace tag is still not recognise in the converters to OOXML, and processing it would still require editing of the OOXML XSLT.

... I have to say though, this is an edge case. If we strongly require optional or mandatory linebreaks in HTML, I think the best approach is to enter MathML in the HTML (copy-pasted from the XML back into the Asciidoc source), and add at the appropriate places `<mspace linebreak="??"/>`, where the linebreak attribute is one of:

````
Value	Description
newline	start a new line and do not indent
indentingnewline	start a new line and do indent
nobreak	do not allow a linebreak here
goodbreak	if a linebreak is needed on the line, here is a good spot
badbreak	if a linebreak is needed on the line, try to avoid breaking here
````

Right now, realising this in AsciiMath is simply not a priority (especially as we would need to differentiate `newline`, `indentingnewline` and `goodbreak`.)

**Comment by opoudjis** [comment]
As reported by @manuel489 again:

According to this thread https://github.com/asciidoctor/asciidoctor/issues/2497, a newline in stem block can be introduced using `\`. Nonetheless, Metanorma doesn't seem to support this approach.

````
[stem]
++++
A "and" B rarr [A&B] \
A "and" "ONEOF"(B1,B2) rarr A&[B1,B2] = [A&B1,A&B2] \
"ONEOF"(A1,A2) "and" "ONEOF"(B1,B2) rarr [A1,A2]&[B1,B2] = [A1&B1,A1&B2,A2&B1,A2&B2]
++++
````

Normal AsciiDoc:
![cap1](https://user-images.githubusercontent.com/33627611/90551332-2826de00-e15f-11ea-9b27-0c85bffc7ad5.PNG)

Metanorma (HTML):
![cap2](https://user-images.githubusercontent.com/33627611/90551344-2a893800-e15f-11ea-9df2-12125e3e1188.PNG)


Now, I can workaround this problem using inline stems:

````
stem:[A "and" B rarr [A&B\]] +
stem:[A "and" "ONEOF"(B1,B2) rarr A&[B1,B2\] = [A&B1,A&B2\]] +
stem:["ONEOF"(A1,A2) "and" "ONEOF"(B1,B2) rarr [A1,A2\]&[B1,B2\] = [A1&B1,A1&B2,A2&B1,A2&B2\]]
````
And the result will be practically the same as normal AsciiDoc, but I report the issue anyway.

Thanks!

**Comment by opoudjis** [comment]
Pending https://github.com/plurimath/plurimath/issues/179

**Comment by opoudjis** [comment]
Insert `<br/>` between math elements split by linebreak.

**Comment by opoudjis** [comment]
Right now,

`<br/>` insertion works in PDF:

![Screenshot 2023-12-20 at 01 40 43](https://github.com/metanorma/metanorma-standoc/assets/1911039/767f3f6f-dfa0-4fc4-b3bc-7b6aa17d2695)

`<br/>` is redundant in the HTML—which means we should insert the `<br/>` in PDF and DOC preprocessing. The placement of the ordinal number needs to be sorted out as well:

![Screenshot 2023-12-20 at 01 42 09](https://github.com/metanorma/metanorma-standoc/assets/1911039/dcab1f51-661f-4e4d-b129-72f43bc55bc1)

DOC also seems to require explicit left alignment:

![Screenshot 2023-12-20 at 01 43 06](https://github.com/metanorma/metanorma-standoc/assets/1911039/1f7be5b1-0382-47df-ac67-d81bd3862133)

**Comment by opoudjis** [comment]
> The placement of the ordinal number needs to be sorted out as well

It can't be, anything that ends up with two math expressions in HTML treats them as two separate blocks, and puts the following number on a third block. I could do some fancy CSS, but I now think the best solution is to generate Presentation XML with `<stem><mathml-with-linebreak>....</mathml-with-linebreak><mathml-no-linebreak>...</mathml-no-linebreak></stem>`, and pick which of the two to render for each output format: HTML consumes mathml-no-linebreak, PDF and DOC consume mathml-with-linebreak.

**Comment by opoudjis** [comment]
In the case of Word, we have to wrap the initial `m:oMath` in `<m:oMathPara><m:oMathParaPr><m:jc m:val="left"/></m:oMathParaPr>...</m:oMathPara>, to get the alignment right. It's fine to do that in html2doc, although now the pre-breakup version will be available anyway, so that may not be needed.

**Comment by opoudjis** [comment]
Asciidoc:

````
[stem]
++++
x = \
y = \
z
++++
````

HTML:

![Screenshot 2023-12-21 at 01 37 14](https://github.com/metanorma/metanorma-standoc/assets/1911039/d2523520-8770-4af3-b98b-efeeafc088b1)


PDF:

![Screenshot 2023-12-21 at 01 38 09](https://github.com/metanorma/metanorma-standoc/assets/1911039/9981b620-a127-42b9-9807-cb5a557d0000)



DOC:

![Screenshot 2023-12-21 at 01 38 53](https://github.com/metanorma/metanorma-standoc/assets/1911039/602eda50-82c9-41b1-96f9-12dd3b680129)

**Comment by opoudjis** [comment]
@suleman-uzair Thank you for all your work!
