### ISSUE TITLE
feature/datamodel: section numbering at the first generated section is wrong

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#114]
Section 4 is dynamically generated by the datamodel feature. However, it is showing as section 6 (in HTML + Word). Subsequent sections have correct numbering.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/11865/65371083-9e426c80-dc92-11e9-85d5-c59e7b03592b.png">

**Comment by opoudjis** [comment]
Dealt with in #116
