### ISSUE TITLE
feature/datamodel: re-implement, provide documentation

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#116]
I have been asked to use feature/datamodel to refactor the UML diagrams of csd-standard-doc

I cannot proceed any further with this task until I have documentation of how this feature works. I've already spent two hours on it, and I've only just realised the distinction being made between views and models. Please provide explicit documentation.

**Comment by opoudjis** [comment]
Well, someone else has done this particular task, but in theory i'm very happy to review the documentation. In practice, I'm simply too busy too, and recommend we use one of the three editors we've hired (who would be using the tool anyway). I will assign the task on once one of them becomes available.

**Comment by ronaldtse** [comment]
This feature has to be reimplemented based on the new YAML functionality. @w00lf please discuss with @ronaldtse when we are to start this. Thanks.

**Comment by opoudjis** [comment]
This is the original code that your current implementation work is reimplementating.
