### ISSUE TITLE
Issue with double quotation marks

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#128]
When a double quotation mark is present twice in a row into a math environment, the compiled result of the entire document shows no new changes. I mean, for example, if you write: "something like this"", in math mode, and compile the document, the output won't show any changes. (It doesn't generate a new output.)
[qm-issue.zip](https://github.com/metanorma/metanorma-standoc/files/3679474/qm-issue.zip)

**Comment by opoudjis** [comment]
Yes, " is a special character in Asciimath, and so needs to be escaped. Not only is " ignored, but any text inside the " " is parsed as a mathematical expression; so any instances of the string "in" inside the quotes are parsed as ∈.

What you want to do is two things:

* Any text in AsciiMath needs to be wrapped explicitly in text("")
* Quotes themselves need to appear in a separate text() function. Or, much better, quotes need to be entered as smart quotes -- which are not special characters in AsciiMath to begin with.

So:

````
text(")text("some text")text(")
````

or better:

text(“some text”)

**Comment by manuel489** [comment]
Ok Nick, understood. Thanks.

**Comment by ronaldtse** [comment]
@opoudjis I was under the impression that double quotes (`"blah"`) is a shorthand for `text(blah)`. Have you found it otherwise?

**Comment by manuel489** [comment]
@ronaldtse Yes, you're right. `text(blah)` is the correct form. And `"blah"` is another way to achieve the same.

**Comment by manuel489** [comment]
What I was trying to say (for information purposes) is: if the user writes (by accident) an additional quotation mark in math mode, like this: stem:["some text""] (notice the additional quotation mark at right) the compiler doesn't generate a new output (and doesn't tell you what went wrong). 

It happenned to me, and it took me a while to discover where the error was. So, I thought it could be helpful to spread the info.

**Comment by ronaldtse** [comment]
Fully agree, maybe we should make a page on metanorma.com. Let me file the ticket.
