### ISSUE TITLE
Latex is keeping its backslashes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#131]
As found in processing of ITU G.650.1-201803.adoc by @anermina, the conversion of LaTeX expresssions to MathML is retaining a lot of LaTeX backslashes. So for example

````
a(x)=1-
\frac{P(x)}{P_{max}}
```` 

The backslash before `frac` is being preserved in the HTML output, as MathML `<mi>\</mi>`

**Comment by opoudjis** [comment]
Cannot replicate, and this is an issue with the LaTeX to MathML converter, latexml, which is an external tool.

I am not debugging latexml, and I don't know enough about LaTeX to know where to even look. This is, in the first instance, an issue for @CAMOBAP795 to ensure that @anermina has the right version of latexml installed, and for him to try and confirm it on a Windows environment. Passing to him.

**Comment by anermina** [comment]
After forcing LaTeXML re-installation, following notification appears first:
latexml v0.8.4 already installed. Forcing reinstall of version '0.8.4'.
 Please use upgrade if you meant to upgrade to a new version.

However, some of the procedures failed and they keep failing in new re-installation attempts:
PS D:\> more C:\Users\Nermina\.cpanm\work\1570911249.7456\build.log | grep -i fail
"Parse::RecDescent failed to created parser, trying to use old implementation. "
#   Failed test 't/daemon/profiles/fragment'
#   Failed test 't/daemon/profiles/math'
# Looks like you failed 2 tests of 13.
Failed 2/13 subtests
#   Failed test 't/daemon/formats/citation'
#   Failed test 't/daemon/formats/citationraw'
#   Failed test 't/daemon/formats/jats'
#   Failed test 't/daemon/formats/tei'
# Looks like you failed 4 tests of 37.
Failed 4/37 subtests
t/92_profiles.t      (Wstat: 512 Tests: 13 Failed: 2)
  Failed tests:  7, 10
t/93_formats.t       (Wstat: 1024 Tests: 37 Failed: 4)
  Failed tests:  4, 7, 10, 37
Result: FAIL
Failed 2/30 test programs. 6/384 subtests failed.
-> FAIL Installing LaTeXML failed. See C:\Users\Nermina\.cpanm\work\1570911249.7456\build.log for details. Retry with --force to force install it.

**Comment by CAMOBAP** [comment]
For now latexml easily can be installed with `choco install latexml`

@anermina can you confirm that this works (or not) for you?

**Comment by anermina** [comment]
@CAMOBAP yes, I don't have latexml issues anymore.
