### ISSUE TITLE
Implement Title attribute for images

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#135]
Both HTML and Word support the distinction between Image ALT vs Image TITLE. Note that Image TITLE is not Image CAPTION, which is separate.

The syntax will be:

```adoc
image:PATH.jpg[TITLE,HEIGHT,WIDTH,alt="ALT"]
```

Rendered in HTML:

```html
<img alt="ALT" src="path" title="TITLE">
```

Rendered in Word:

https://terrillthompson.com/548

TITLE => Word Image Alt Title
ALT => Word Image Alt Description

Caption is separate.

**Comment by opoudjis** [comment]
As discussed at some length: currently Asciidoctor treats the image title attribute and the initial-dot title of an image block identically (as node.title), and we already use the initial-dot title  for the figure caption, as we do throughout Metanorma with captions. We would be breaking all existing documents if we undo that assignment. Therefore the only current way to implement this in Metanorma without breaking captions is by giving this title attribute a distint name, `titleattr`.

If you have a distinct mechanism of processing Asciidoctor that preserves all its existing functionality, including substitutions, @ronaldtse, we can revisit that. Until you do, and it does *everything* that Asciidoctor currently does, this is the way it's going to be implemented.

**Comment by opoudjis** [comment]
https://terrillthompson.com/548

I only have ONE alt text field in my copy of Word:

<img width="1502" alt="Στιγμιότυπο 2019-10-14, 17 45 18" src="https://user-images.githubusercontent.com/1911039/66733182-736ec100-eeaa-11e9-92c3-892378ebea58.png">

I'm dumping this title attribute into the title attribute of Word HTML for images, but if it's not supported as a distinct attribute in Office 2016, then I'm only going to move it to another attribute if someone tells me what that attribute should be.

**Comment by ronaldtse** [comment]
Me too, on Word for Mac 16.29.

<img width="300" alt="Screen Shot 2019-10-14 at 2 48 53 PM" src="https://user-images.githubusercontent.com/11865/66733326-bf613c00-ee91-11e9-9612-df7c12165de6.png">
