### ISSUE TITLE
Unable to auto-cite GB standards

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#143]
```
GB/T 16159 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC
GB/T 16159 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC
GB/T 15834 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC
GB/T 15834 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC
GB/T 28039 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC
GB/T 28039 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC
```

This is from https://github.com/CalConnect/csd-transcription-systems

**Comment by opoudjis** [comment]
https://github.com/relaton/relaton/

````
The identifiers for which bibliographic entries are to be retrieved need to indicate which standards body they belong to. To do so, this gem adopts the convention of bracketing identifiers, and preceding them with a code that indicates the standards body:

If the standards body is the national standards body, the wrapper uses the ISO country code. So CN(GM/T 0009-2012) is Chinese sector standard GM/T 0009-2012.
````

This was the absolutely correct thing to do, given the riot of prefixes in GB, which are guarantee to clash with other standards: the raw prefixes are recognised in metanorma-gb, because they are assumed as default, but they absolutely will not be recognised in an extraneous standard like CSD. The bug report says this explicitly: that's why "CN" is there.

**Comment by opoudjis** [comment]
if you think the error message "does not have a recognised prefix" should point users to relaton.com documentation on prefixes, feel free to raise a ticket with @andrew2net.

**Comment by opoudjis** [comment]
Actually, I will:

Andrej, the error message "does not have a recognised prefix" in `relaton/lib/relaton/db.rb` should point users to the documentation of prefixes in relaton/README.adoc. (Actually, it should point to relaton.com, but that's all it does.) Please add "See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them."

@ronaldtse if you want different text, let Andrej know.

**Comment by opoudjis** [comment]
Ah, can't transfer. OK, opening in relaton.

**Comment by ronaldtse** [comment]
@opoudjis thanks. In fact, I contest the inability to cite "GB/T" directly in ISO. This works the same for DIN and other national standards. Reopening.

**Comment by ronaldtse** [comment]
@opoudjis 

> This was the absolutely correct thing to do, given the riot of prefixes in GB, which are guarantee to clash with other standards.

Disagree. While we do not need to support all the non-national prefixes, we should support the national prefixes. i.e. GB, GB/T, GB/Z.

**Comment by opoudjis** [comment]
Can't use wrapped codes anyway, bug in relaton: https://github.com/relaton/relaton/issues/64

So what you are saying is you want GB, GB/T, GB/Z to be an exception to the requirement to wrap CN around all Chinese standards codes.

That is adhoccery, but fine. This becomes a relaton-gb issue.

**Comment by opoudjis** [comment]
As it turns out, GB is already recognised as a prefix without the CN wrapper. I am adding GB/T and GB/Z.

**Comment by opoudjis** [comment]
Confirmed as working, but you will need to fetch relaton-gb to get it working.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !
