### ISSUE TITLE
Make auto-fetch of citation optional

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#146]
From https://github.com/metanorma/mn-templates-iso/issues/12

> People don't know that the title is auto-fetched, and they need a way of overriding auto-fetch.

the simplest thing is to prefix/wrap the identifier code, to prevent fetching. 

````
* [[[ISO1234,nofetch(ISO 1234)]]]
````

**Comment by opoudjis** [comment]
Until I am provided context for the request, this is low priority.

**Comment by ronaldtse** [comment]
Thanks for posting this. I don't remember the exact use case. Will promote this once I remember or it occurs again...

**Comment by ronaldtse** [comment]
@opoudjis I know it's on your plan, but a reminder for updating Metanorma.com.
