### ISSUE TITLE
Cross-reference fails if anchor starts with number

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#147]
```
[[120-annexa]]
== General requirements

== Next

<<120-annexa>>
```

Fails.

```
[[part120-annexa]]
== General requirements

== Next

<<part120-annexa>>
```

Works.

**Comment by opoudjis** [comment]
A constraint imposed by Asciidoctor itself: Asciidoctor simply refuses to process anchors starting with numbers. And this is also a constraint imposed by XML to xml:id: https://www.w3.org/TR/xml-id/#processing, https://www.w3.org/TR/xml11/#NT-NameStartChar : xml:id is an XML NCName.

I will not be relaxing this constraint, which would break any XML parser that ever touches Metanorma. And this constraint is documented in the Asciidoctor User Manual:

https://asciidoctor.org/docs/user-manual/#custom-ids

> Asciidoctor recognizes all valid UTF-8 characters in section IDs. When using the double square bracket form, the ID must conform to the XML Name rules, which means the ID must start with a letter, an underscore, or a colon.

The metanorma.com documentation is not a place to repeat every paragraph of the Asciidoctor user manual, and it is big enough already. But I have added a note in the discussion of crossreferences in metanorma.com.
