### ISSUE TITLE
"Abbreviated terms" clause name cannot be repeated

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#148]
In some ISO standards the section name "Abbreviated terms" is used in annexes.

Right now, these error will be thrown, and the rendering of those annex sections of "Abbreviated terms" will fail:

(there are two annexes that contain a clause called "Abbreviated terms")
```
No label has been processed for ID _abbreviated_terms_2
No label has been processed for ID _abbreviated_terms_3
No label has been processed for ID _abbreviated_terms_2
No label has been processed for ID _abbreviated_terms_3
No label has been processed for ID _abbreviated_terms_2
No label has been processed for ID _abbreviated_terms_3
```

And the section becomes:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/11865/68394689-2a193680-0123-11ea-8b70-67865a6ac17c.png">

**Comment by opoudjis** [comment]
Abbreviated Terms is a reserved title under Metanorma (and Metanorma-ISO), that is how symbols sections are detected. But what you're showing me is the expected definition list anyway, so that should not be an issue.

**Comment by opoudjis** [comment]
Cannot reproduce:

````
= X 
A 

== Abbreviated Terms

a:: b

[appendix]
== Appendix1

=== Abbreviated Terms

c:: d

[appendix]
== Appendix2

=== Abbreviated Terms

e:: f
````

[a3.html.zip](https://github.com/metanorma/metanorma-standoc/files/3828107/a3.html.zip)

**Comment by ronaldtse** [comment]
Here's how it appears.

```adoc
= title

== Terms, definitions, symbols and abbreviated terms

[source="ISO_8000-102"]
=== Terms and definitions

=== Symbols

p:: property
...

=== Abbreviated terms

ABNF:: Augmented Backus-Naur Form
...

[appendix,obligation="informative"]
== Blah

=== Foo

...

=== Abbreviated terms

For the purposes of this annex, the following abbreviated terms apply:

NAND:: NOT AND
...

```

**Comment by ronaldtse** [comment]
The actual document is located here:
https://gitlab.com/metanorma/iso-tc184-sc4/tree/master/sources/iso-8000/part110-2

**Comment by ronaldtse** [comment]
My temporary workaround is this:
```adoc
=== Abbreviated terms used in this annex

For the purposes of this annex, the following abbreviated terms apply:

NAND:: NOT AND
...
```

**Comment by opoudjis** [comment]
Ronald indicates this is closed.

**Comment by ronaldtse** [comment]
Thanks! Confirmed.
