### ISSUE TITLE
Auto-fetch mistakenly gives standard's ID instead of the text in anchor

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#149]
```
* [[[ISO_7372_data,ISO 7372 Directory]]], _Trade Data Elements Directory_, 2005. UN/CEFACT. http://www.unece.org/cefact/publica/publi_index.htm 
```

Citation of this will get rendered as `ISO 7372` because auto-fetch thinks that the document is citing "ISO 7372", but this is clearly wrong. The intention is citing a data source that relates to ISO 7372, not ISO 7372 itself.

**Comment by opoudjis** [comment]
It is unreasonable to expect an identifier prefixed with a clear ISO prefix to behave as anything other than an ISO identifier. And "ISO 7372 Directory" is an identifier prefixed with "ISO".

Two things need to happen here:

* First, Relaton needs to verify that the identifier submitted is actually matched in the fetched document. relaton-iso did have such behaviour in the past; but an identifier like "ISO 7372 Directory" should not match whatever ISO things the identifier is, and relaton should return "not found" --- in which case the reference is processed as normal. I will raise a ticket with relaton.

* Second, we should overrule the attempt to fetch the resource, as anticipated in https://github.com/metanorma/metanorma-standoc/issues/146 . So the identifier would become nofetch(ISO 7372 Directory), and metanorma would strip the nofetch() wrapper.

@ronaldtse Does that work for you?

**Comment by ronaldtse** [comment]
> First, Relaton needs to verify that the identifier submitted is actually matched in the fetched document. relaton-iso did have such behaviour in the past; but an identifier like "ISO 7372 Directory" should not match whatever ISO things the identifier is, and relaton should return "not found" --- in which case the reference is processed as normal. I will raise a ticket with relaton.

Agree. This identifier should not match Relaton.

> Second, we should overrule the attempt to fetch the resource, as anticipated in #146 . So the identifier would become nofetch(ISO 7372 Directory), and metanorma would strip the nofetch() wrapper.

I agree we should have a `nofetch` option but that is tangential to the current scenario. It is unreasonable to think that `ISO 7372 Directory` matches `ISO 7372`.

**Comment by opoudjis** [comment]
Ticket now duplicates https://github.com/relaton/relaton-iso/issues/77, #146
