### ISSUE TITLE
Boilerplate in all flavors should be moved inside XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#157]
From @opoudjis :
>  Much longer term: change boilerplate for all gems.

* ISO: https://github.com/metanorma/metanorma-iso/issues/292
* ITU: https://github.com/metanorma/metanorma-itu/issues/138
* IEC: https://github.com/metanorma/metanorma-iec/issues/18
* NIST: https://github.com/metanorma/metanorma-nist/issues/164
* OGC: https://github.com/metanorma/metanorma-ogc/issues/76
* CSA: https://github.com/metanorma/metanorma-csa/issues/22
* CSD: https://github.com/metanorma/metanorma-csd/issues/92
* GB: https://github.com/metanorma/metanorma-gb/issues/110
* M3D: https://github.com/metanorma/metanorma-m3d/issues/23
* RSD: https://github.com/metanorma/metanorma-rsd/issues/29
* UNECE: https://github.com/metanorma/metanorma-unece/issues/34
* etc.

**Comment by opoudjis** [comment]
Limit of one of these per month. *I am being serious*. These are extremely painful to implement because of how Word front pages do indulgent formatting of this material.

**Comment by opoudjis** [comment]
Closing in favour of child tickets

**Comment by opoudjis** [comment]
Need to migrate boilerplate functionality from local gems to standoc and isodoc. (Generic functionality in the case of isodoc.)
