### ISSUE TITLE
Allow user nominated label for autofetch reference

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#159]
`[[[xxx,(zzz)yyy]]]`  shall be interpreted as: fetch yyy against anchor xxx, but label the reference not with the standard document identifier, but with zzz.

**Comment by opoudjis** [comment]
NIST need this.

**Comment by ronaldtse** [comment]
This is going to affect all the mn-samples-nist source files. Right now they use the user-supplied labels without auto-fetch, we will need to update them to reflect the user-supplied tags together with the auto-fetch string.

**Comment by ronaldtse** [comment]
ITU also needs this.

**Comment by opoudjis** [comment]
Change rendering rules, since now metanorma ID (= user supplied label) will coexist with other document IDs: prefer metanorma ID whenever present, else go down existing hierarchy of non(DOI, ISSN, metanorma), then first available ID.
