### ISSUE TITLE
Provide "full document identifier" in Metanorma XML for compatibility

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#162]
Users of Metanorma XML do not necessarily have the capacity to implement modeling of document identifiers, especially considering how many flavors there are.

We should provide a "text-pre-rendered" document identifier in Metanorma XML for compatibility, allowing users to directly extract the formatted document identifier.

This relates to: https://github.com/metanorma/metanorma-iso/issues/298

**Comment by opoudjis** [comment]
In ISO, this is a false alarm, and we are doing two full identifiers, one with the language suffix and one without.

I would argue that in the other gems, `<docidentifier type={flavour}>` is the true full identifier — and if it is not, it should be. So redundant issue, I'd misremembered that we had taken care of full identifiers a while ago.

**Comment by ronaldtse** [comment]
> I would argue that in the other gems, <docidentifier type={flavour}> is the true full identifier — and if it is not, it should be. So redundant issue, I'd misremembered that we had taken care of full identifiers a while ago.

I hope so too.
