### ISSUE TITLE
Implement ISO 690 citations and references: A.1. General

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#168]
A.1 General

A.1.1 Linking citations to references

Statements in a text should be linked to the bibliographic details of the information resources which support those statements in one of the methods described in this Annex.

A.1.2 Reference list arrangement order

The recommended arrangement of references within an alphabetical list is specified in this clause.

Alphabetical lists of references should be arranged according to the principles in a) to e), based on the first element given in the reference. See also Clause 8.

a)	A creator’s own writings precede any information resource he/she has cited. 
b)	A single-creator entry precedes a dual or multi-creator entry beginning with the same name. 
c)	Multiple entries by a single creator are arranged chronologically, with the earliest cited information resource first. 
d)	Multiple creator entries with the same first creator may be arranged chronologically after entries by the first creator alone or with one co-creator, in order to match citations in the document which give the first creator’s name, “and others” or “et al.” after the date (see also 7.2.6). 
e)	Corporate creators (such as organizations) are alphabetized according to the first significant word of the name. 

In special circumstances, an alternate order may be used if done so consistently for all references.

EXAMPLE 1	In lists of references arranged in classified or subject order, it is often appropriate to place the title first and the creator second.

EXAMPLE 2	In accession lists of maps, the area may be placed first.

EXAMPLE 3	In lists of moving-image materials, the title is normally placed first.

**Comment by opoudjis** [comment]
This is author-based sorting, which we have not implemented for any flavour yet. (OGC is a candidate.)

**Comment by opoudjis** [comment]
In reality, this has been implemented already in https://github.com/metanorma/isodoc/issues/159: author sorting and handling multiple authors is intrinsic to Author-Date citation.
