### ISSUE TITLE
Asciidoctor: `footnoteref` is deprecated, use `footnote:id[]` instead

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#169]
> `footnoteref` does indeed seem to have been deprecated between Asciidoctor 1 and Asciidoctor 2, but that is an Asciidoctor markup issue.

> What is happening is simply that the Asciidoctor markup of the document needs to signal explicitly that the footnote is to be reused.

> I also need to make sure that the new method for signalling that in Asciidoctor, `footnote:id[]`, is recognised in XML generation.  (The "id" is to be replaced by an arbitrary string, which needs to be the same for the two footnote instances.) Once that is done, I'll remove all instances of footnoteref from our repositories.

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-itu/issues/135#issuecomment-561418041_

**Comment by opoudjis** [comment]
I've rspec'd `footnote:id[]`, and it's behaving exactly the same as footnoteref, so the markup should have worked for Nermina. Will remove footnoteref as stated.
