### ISSUE TITLE
Should not generate invalid table (from mn-itu-samples)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#170]
Table generation can currently be invalid:

```adoc
[[table-i-1]]
.OCP related specifications
|===

| *Family*
| *Specification*
| *Summary*
| *Published*
.8+.<| OpenRack V2
| Twin Lakes 1S Server Design Specification V1.00 <<b-OCP_1S>>

| This specification describes the design of the Twin Lakes 1S server based on the Intel Xeon Processor D-2191 System-on-a-Chip (SoC).

| 2018

| Facebook 2S Server Tioga Pass Specification V1.0 <<b-OCP_2S>>

| This specification describes Facebook dual sockets server Intel Motherboard v4.0
(Project name: Tioga Pass) design and design requirement to integrate Tioga Pass into Open Rack V2.

...
```

(from https://github.com/metanorma/mn-samples-itu/blob/master/sources/Y.3507-201812.adoc)

Will generate the following XML:

```
<table id="table-i-1">
  <name>OCP related specifications</name>
  <tbody>
    <tr>
      <td align="left">
        <strong>Family</strong>
      </td>
    </tr>
    <tr>
      <td align="left">
        <strong>Specification</strong>
      </td>
    </tr>
    <tr>
      <td align="left">
        <strong>Summary</strong>
      </td>
    </tr>
    <tr>
      <td align="left">
        <strong>Published</strong>
      </td>
    </tr>
    <tr>
      <td rowspan="8" align="left">OpenRack V2</td>
    </tr>
  </tbody>
</table>
```
The cell in **last** row has a value **rowspan**="8", but no continue.
In my local version:
```
<table id="table-i-1">
  <name>OCP related specifications</name>
  <tbody>
    <tr>
      <td align="center">
        <strong>Family</strong>
      </td>
      <td align="center">
        <strong>Specification</strong>
      </td>
      <td align="center">
        <strong>Summary</strong>
      </td>
      <td align="center">
        <strong>Published</strong>
      </td>
    </tr>
    <tr>
      <td rowspan="8" align="left">OpenRack V2</td>
      <td align="left">Twin Lakes 1S Server Design Specification V1.00 <eref type="inline" bibitemid="b-OCP_1S" citeas="b-OCP 1S"/></td>
      <td align="left">This specification describes the design of the Twin Lakes 1S server based on the Intel Xeon Processor D-2191 System-on-a-Chip (SoC).</td>
      <td align="center">2018</td>
    </tr>
    <tr>
      <td align="left">Facebook 2S Server Tioga Pass Specification V1.0 <eref type="inline" bibitemid="b-OCP_2S" citeas="b-OCP 2S"/></td>
      <td align="left">This specification describes Facebook dual sockets server Intel Motherboard v4.0<br/>
(Project name: Tioga Pass) design and design requirement to integrate Tioga Pass into Open Rack V2.</td>
      <td align="center">2018</td>
    </tr>
    <tr>
      <td align="left">Big Basin-JBOG Specification V1.0 <eref type="inline" bibitemid="b-OCP_JBOG" citeas="b-OCP JBOG"/></td>
      <td align="left">This document describes technical specifications for Facebook's Big Basin-JBOG for use in Open Rack V2.</td>
      <td align="center">2018</td>
    </tr>
    <tr>...
```

Metanorma should not allow generation of invalid tables.

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn-native-pdf/issues/39#issuecomment-561862643_

**Comment by ronaldtse** [comment]
I was able to workaround the markup to generate properly in this commit:
https://github.com/metanorma/mn-samples-itu/commit/ef4e34b05e2667807af32ab1bc59ed25e32199ca

This indicates that this markup is misunderstood in AsciiDoctor:

```adoc
.OCP related specifications
[cols="a,2a,3a,a",cols="header"]
|===
^| Family
^| Specification
^| Summary
^| Published

.8+| OpenRack V2
```

Which generates these errors:
```
asciidoctor: ERROR: Y.3507-201812.adoc: line 661: dropping cell because it exceeds specified number of columns
asciidoctor: ERROR: Y.3507-201812.adoc: line 661: dropping cell because it exceeds specified number of columns
...
```

And the full header columns could only be understood when all the header cells are placed on a single line:

```adoc
[cols="a,2a,3a,a",cols="header"]
|===
^| Family ^| Specification ^| Summary ^| Published
```

Which is very strange, especially when the content is long:

```adoc
^| NO. ^| Requirements in this Recommendation ^| Relationship with related specifications from other SDOs
```

**Comment by opoudjis** [comment]
I don't understand what you expect me to do here. This is an Asciidoctor markup issue. And it is most definitely not urgent.

**Comment by opoudjis** [comment]
If people put in incorrect Asciidoctor markup, incorrect things will happen. If you decide to play funny buggers with table markup, incorrect things will happen.

This is a RTMFM issue, and the Manual is at https://asciidoctor.org/docs/user-manual/#header-row. The failure to insert the required empty line after the end of the header, and worse still, the empty line before the header (which ends up meaning THERE IS NO HEADER ROW) is an error in data entry. It is not my problem, and again, I siomply do not see what I am meant to do here.

The correct markup is

````
[[table-i-1]]
.OCP related specifications
[cols="a,2a,3a,a",options="header"]
|===
^| Family
^| Specification
^| Summary
^| Published

.8+| OpenRack V2
|a |b |c
|a |b |c
|a |b |c
|a |b |c
|a |b |c
|a |b |c
|a |b |c
|a |b |c
|===
````

Of *course* `[cols="a,2a,3a,a",cols="header"]` is misunderstood by Asciidoctor, because it is nonsense.

**Comment by ronaldtse** [comment]
Ah, so there were two separate markup issues. Thanks for spotting that.

BTW doesn't the last row sticking with the closing table tag mean the "footer"?

**Comment by opoudjis** [comment]
> BTW doesn't the last row sticking with the closing table tag mean the "footer"?

The answer is not only "no", but "RTFM". Again.

https://asciidoctor.org/docs/user-manual/#footer-row

> The last row of a table can be styled as a footer by adding the footer keyword to the options attribute.
