### ISSUE TITLE
Implement landscape mode for content (or just tables...?)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#173]
As seen here: https://github.com/metanorma/metanorma-iso/issues/263 sometimes tables are too wide and require landscape mode.

ITU OB sample: https://github.com/ituob/service-publications-refs/tree/master/974-F.400

There should be a syntax to mark content as "landscape" mode in Metanorma.

**Comment by opoudjis** [comment]
Page break in asciidoc is:

````
<<<
````

Asciidoc markup allows options on pagebreak:

````
[%landscape]
<<<

[%portrait]
<<<
````

So the appropriate markup can be introduced, and will need to be converted in Word into section breaks. The challenge will be whether this can be done without unworkable additions to Word's CSS defining page layouts.

**Comment by opoudjis** [comment]
https://stigmortenmyre.no/mso/html/word/wdconsectionbreaks.htm and other online references notwithstanding, `mso-page-orientation: landscape` is being ignored by Word; what works is to flip the height and width in the `size` attribute of `@page`.

**Comment by opoudjis** [comment]
Needed changes in Word for every single gem are:

* Next to `@page WordSection3`, add `@page WordSection3L`, with the width and height flipped
* If there are any headers or footers with a right tab at the right edge of the page, or a center tab at the center of the page (e.g. for page number), create in header.html a variant header/footer with the tab in the center/right of the landscape page

In isodoc:

* Whenever a section orientation page break is found, add a section break and a new section to the CSS, with `page: WordSection3` or `page: WordSection3L` respectively set.
* That section needs to force closing and reopening of all open tags at that point (which, given markup, will be limited to divs): get all ancestors at that point in Nokogiri up to the WordSection div, close their tags, and then reopen their tags with the ids stripped, via wrap.
** As an alternative to that horror, we might preprocess input, but that would likely be even worse.

This all is tractable, but it's also a big refactor. Again. I would rather this not hold up Friday release of gem.

**Comment by opoudjis** [comment]
Also need to add WordSection3P (portrait) as well as WordSection3L, and WordSection2P and WordSection2L. All these continuation sections need to resume page numbering from the previous section, so they have different `@page` attributes from the initial WordSection2 and WordSection3.
