### ISSUE TITLE
Better warning when bad anchor used in reference

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#176]
This term source reference:

```
=== addressee
...

[.source]
<<UNCITRAL 2007,section="4.(e)">>, modified entry has been added.

[bibliography]
== Bibliography
* [[[UNCITRAL_2007,UNCITRAL 2007]]], _United Nations Convention on the Use of Electronic Communications in International Contracts_
```

Should have been:

```
[.source]
<<UNCITRAL_2007,section="4.(e)">>, modified entry has been added.
```

The anchor used in the original example was missing an underscore.

Right now, the only warning that will be produced is:
`UNCITRAL 2007 is not a real reference!`

But it should be more explicit and helpful for the user, showing the file path and line number that this error refers to (and it should quote the broken anchor used).

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-standoc/issues/174#issuecomment-565233563_

**Comment by opoudjis** [comment]
It *is* quoting the broken anchor. Message clarified, it gives the XML line number (as the error is only found on checking over the XML. Tracing back to the source Asciidoctor line is intractable.)

````
Crossreferences: (XML Line 000023): UNCITRAL 2007 is not a real reference!
````
