### ISSUE TITLE
Double quotes still in the wrong direction in pseudocode

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#181]
Image: <img width="604" alt="Screen Shot 2019-12-14 at 6 41 37 PM" src="https://user-images.githubusercontent.com/11865/70847618-5d2cb380-1ea1-11ea-882b-a46e314518d2.png">

**Comment by opoudjis** [comment]
Better just to disable smart quotes in pseudocode, as is already the case in sourcecode.

**Comment by opoudjis** [comment]
And pseudocode is size 9 in Word.

**Comment by ronaldtse** [comment]
Thanks. This is blocking a submission of document, hopefully it will get fixed soon.

**Comment by opoudjis** [comment]
Sourcecode is 9 pt Courier. Pseudocode is 9 pt Body Font, but that is wrong, since Body Font is smaller than Courier: putting it back to 10 pt.

**Comment by ronaldtse** [comment]
Confirmed -- this is fixed.
