### ISSUE TITLE
Check for `plantuml` command return code

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#185]
@opoudjis this remediation method seems dangerous -- it's lacking the check if the `plantuml` command failed. If it failed, it may not even generate the PNG file. Here we ought to check for the return code of the `plantuml` command.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-standoc/pull/184#issuecomment-566087734_

**Comment by opoudjis** [comment]
Duplicated in #187
