### ISSUE TITLE
Windows Ruby 2.6 refusal to move PlantUML image

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#187]
This only fails on Windows Ruby 2.6:

https://github.com/metanorma/metanorma-standoc/runs/361653277

lib/asciidoctor/standoc/macros.rb

````
FileUtils.mv (Pathname.new(localdir) + "plantuml" + "#{fn}.png").to_s,
            (Pathname.new(localdir) + outfile).to_s
````

A permission error is raised in GitHub Actions which is not raised in other flavours.

@CAMOBAP795 could you please investigate?

**Comment by opoudjis** [comment]
This is a Heisenbug: in https://github.com/metanorma/metanorma-standoc/runs/370329707, it fails in Windows Ruby 2.5.

**Comment by opoudjis** [comment]
And now hitting Ruby 2.4: https://github.com/metanorma/metanorma-standoc/commit/1ccc8b8aa232defaaf27307e230e117027fd447a/checks?check_suite_id=398745759

https://github.com/rubygems/bundler/search?utf8=✓&q=Permission+denied&type=Issues might help

**Comment by ronaldtse** [comment]
@opoudjis this advice may apply: https://github.com/rubygems/bundler/pull/7546

> Don't rename folders while being inside
This fails on Windows.

In addition, this code seems to assume the existence of `(Pathname.new(localdir) + "plantuml" + "#{fn}.png").to_s`. We should check:

1. the success of PlantUML
2. the existence of the file generated by PlantUML
3. the existence of the directory that contains `(Pathname.new(localdir) + outfile).to_s`
4. the writability of the directory that contains `(Pathname.new(localdir) + outfile).to_s`

**Comment by ronaldtse** [comment]
Moreover, we SHOULD NOT write to `(Pathname.new(localdir) + "plantuml" + "#{fn}.png").to_s`. We should write to a TMPDIR and `mv` the file over to the desired destination.
