### ISSUE TITLE
Replace Date.today with Date.current

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#190]
Replace Date.today in test scripts with Date.current:

````
require "active_support"
require "active_support/core_ext/date/calculations"
````

And gemspec: 

````
  spec.add_development_dependency "activesupport"
````

**Comment by opoudjis** [comment]
Already implemented in metanorma-gb

**Comment by opoudjis** [comment]
activesupport 6 is hard coded to Ruby 2.5, and I am predictably outraged that version hell is being unleashed on my stack by such a nicety. Downgrading to activesupport 5.

**Comment by ronaldtse** [comment]
@opoudjis Can we not add activesupport?

**Comment by opoudjis** [comment]
Not if you want the Date.current or Time.current that Hound wants. Let me see if they exist elsewhere.

**Comment by opoudjis** [comment]
Will not use; Date.today is already localtime, and switching to time zone based date is marginal benefit for the hassle of version dependencies with activesupport.
