### ISSUE TITLE
-- rendered as em dash or en dash

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#191]
From https://github.com/metanorma/metanorma-ogc/issues/56

Asciidoctor renders `--` as em-dash in substitutions of normal text. However `--` contained in block attributes is pretty-printed by the smartquotes_cleanup method afterwards, and ends up as en-dash.

**Comment by opoudjis** [comment]
This behaviour originated in wanting to emulate the behaviour of ISO, which uses en-dash as a delimiter between title parts in its bibliographic references. But this leads to inconsistency with Asciidoctor's native way of processing `--`, and that inconsistency is unacceptable.

**Comment by opoudjis** [comment]
Make an exception of -- within date

**Comment by ronaldtse** [comment]
> This behaviour originated in wanting to emulate the behaviour of ISO, which uses en-dash as a delimiter between title parts in its bibliographic references. 

@opoudjis ISO uses en-dashes to delimit title parts in references? Where is that shown?

**Comment by opoudjis** [comment]
Welp, looks like I had got that wrong. It is certainly em-dashes in the bibliographic website as well; it might have been en-dashes previously.

**Comment by ronaldtse** [comment]
Thanks for the confirmation.
