### ISSUE TITLE
Implement plugin/extension to allow converting structured data (YAML) into Metanorma content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#195]
Allow coding of a template inside adoc and then 

e.g.

```adoc
[yaml2text,foobar.yaml]
----
=== {item.name}
{item.desc}

{item.symbol}:: {item.symbol_def}
----
```

Given a YAML file like this:

`foobar.yaml`
```yaml
- name: spaghetti
  desc: wheat noodles of 9mm diameter
  symbol: SPAG
  symbol: the situation is message like spaghetti at a kid's meal
```

Gets rendered into a form that is produced using this adoc:

```adoc
=== spaghetti
wheat noodles of 9mm diameter

SPAG:: the situation is message like spaghetti at a kid's meal
```

**Comment by ronaldtse** [comment]
Notice that this interpolation method also works with expansions.

e.g. given a YAML file that has a collection of items, of which each item contains collections:

``adoc
[yaml2text,blah.yaml]
----
=== {item.name}
{item.desc}

[yaml2text,item.symbols]
------
{item.symbol}:: {item.symbol_def}
------
----
```

**Comment by ronaldtse** [comment]
This already makes #134 a lot more palatable.

**Comment by ribose-jeffreylau** [comment]
Or maybe something like the following...  Just some ideas.

## Examples

### An array of strings

#### Given:

strings.yaml
```yaml
---
- lorem
- ipsum
- dolor
```

#### Usage:

Implicit array context.  I don't prefer this, as this seems to be confusion-prone.
```adoc
[yaml2text,strings.yaml,s]
----
=== {s.#} {s}

This section is about {s}.
----
```

vs

Explicit context.  This seems clearer to me.
```adoc
[yaml2text,strings.yaml,ar]
----
{ar.*,s,EOS}
=== {s.#} {s}

This section is about {s}.

{EOS}
----
```

Syntax is: `[yaml2text,` _YAML file path_ `,` _self-defined context name_ `]`

Here, the _file path_ is `strings.yaml`, and _context name_ is `s`.

`{s.#}` gives you back the zero-based position of item `s` in the parent array `yaml.items`.

#### Expect:

```adoc
=== 0 lorem

This section is about lorem.

=== 1 ipsum

This section is about ipsum.

=== 2 dolor

This section is about dolor.
```

### A hash

#### Given:

hash.yaml
```yaml
---
name: Lorem ipsum
desc: dolor sit amet
```

#### Usage (with fixed, known keys):

Explicit context.  Again, I think I like this better for its clarity.
```adoc
[yaml2text,hash.yaml,my_item]
----
=== {my_item.name}

{my_item.desc}
----
```

vs 

Implicit context
```adoc
[yaml2text,hash.yaml]
----
=== {name}

{desc}
----
```

#### Expect:

```adoc
=== Lorem ipsum

dolor sit amet
```

#### Usage (with free keys):

Named hash key AND value
```adoc
[yaml2text,hash.yaml,my_item]
----
{my_item.*,key,val,EOI}
=== {key}

{val}

{EOI}
----
```

vs

Named hash key only
```adoc
[yaml2text,hash.yaml,my_item]
----
{my_item.*,key,EOI}
=== {key}

{my_item[key]}

{EOI}
----
```

Array / hash items can be de-referenced with square brackets, e.g. `{yaml.items[s.#]}`, `{my_hash[key_name]}`.

Hash items should only be de-referenced with item key and not with integer index.


#### Expect:

```adoc
=== name

Lorem ipsum

=== desc

dolor sit amet
```

### An array of hashes

#### Given:

array_of_hashes.yaml
```yaml
---
- name: Lorem
  desc: ipsum
  nums: [2]
- name: dolor
  desc: sit
  nums: []
- name: amet
  desc: lorem
  nums: [2, 4, 6]
```

#### Usage:

```adoc
[yaml2text,array_of_hashes.yaml,ar]
----
{ar.*,item,EOF}

{item.name}:: {item.desc}

{item.nums.*,num,EON}
- {item.name}: {num}
{EON}

{EOF}
----
```

Different contexts are referred to by the name defined, e.g. `ar`, `item`, `num`.

Scopes are delimited by self-defined heredoc-esque markers, e.g. `EOF`, `EON`.

#### Expect:

```adoc

Lorem:: ipsum

- Lorem: 2

dolor:: sit


amet:: lorem

- amet: 2
- amet: 4
- amet: 6

```


### An array with interpolated file names, etc. for Asciidoc's consumption


#### Given:

strings.yaml
```yaml
---
prefix: doc-
items:
- lorem
- ipsum
- dolor
```

#### Usage:

```adoc
[yaml2text,strings.yaml,yaml]
------
First item is {yaml.items[0]}.
Last item is {yaml.items[-1]}.

{yaml.items.*,s,EOS}
=== {s.#} -> {s.# + 1} {s} == {yaml.items[s.#]}

[source,ruby]
----
include::{yaml.prefix}{s.#}.rb[]
----

{EOS}
------
```

Negative array indices wraps around from the end like Ruby Arrays do.

If brace expressions like `{s.# + 1}` are to be supported (at all), only addition needs to be supported for the moment, unless there's a clear need to support others as well.

#### Expect:

```adoc
First item is lorem.
Last item is dolor.

=== 0 -> 1 lorem == lorem

[source,ruby]
----
include::doc-0.rb[]
----

=== 1 -> 2 ipsum == ipsum

[source,ruby]
----
include::doc-1.rb[]
----

=== 2 -> 3 dolor == dolor

[source,ruby]
----
include::doc-2.rb[]
----
```

Out-of-bound errors should be thrown.

**Comment by ronaldtse** [comment]
Thanks @ribose-jeffreylau ! This ticket is actionable now!

**Comment by ronaldtse** [comment]
Merged and documented on metanorma.com. Thanks @w00lf and @ribose-jeffreylau  !
