### ISSUE TITLE
biblio refactor breaks metanorma-iso (and all other boilerplate gems) in Windows

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#197]
As a result of https://github.com/metanorma/metanorma-standoc/issues/157, a file called boilerplate.xml is included in the Metanorma XML generated for all gems that have that file. That is done in the following code:

metanorma-standoc, lib/asciidoctor/standoc/cleanup_boilerplate.rb:

````
      def initial_boilerplate(x, isodoc)
        return if x.at("//boilerplate")
        preface = x.at("//preface") || x.at("//sections") || x.at("//annex") ||
          x.at("//references") || return
        b = boilerplate(x, isodoc) or return
        preface.previous = b
      end

      def boilerplate_file(xmldoc)
          File.join(@libdir, "boilerplate.xml")
      end

      def boilerplate(xml, conv)
        file = boilerplate_file(xml)
        file = File.join(@localdir, @boilerplateauthority) if @boilerplateauthority
        !file.nil? and File.exists?(file) or return
          conv.populate_template((File.read(file, encoding: "UTF-8")), nil)
      end
````

The `boilerplate` element is successfully read into the Metanorma XML for Ubuntu and MacOS per https://github.com/metanorma/metanorma-iso/actions/runs/32948529 and https://github.com/metanorma/metanorma-iso/actions/runs/32948525. The `boilerplate` element is failing to be read in to Windows per https://github.com/metanorma/metanorma-iso/actions/runs/32948533

`boilerplate_file` should be yielding a correct file name; the only thing I can think of is that `@libdir`, which is the file directory of the current gem, is not set correctly.

`@libdir` is set cleverly, perhaps too cleverly, with a hook in standoc, which is inherited by all the other gems: metanorma-standoc, lib/asciidoctor/standoc/converter.rb

https://stackoverflow.com/questions/4812873/how-can-i-access-the-current-file-in-a-subclass-from-a-method-in-the-supercl

````
      def initialize(backend, opts)
        super
        basebackend "html"
        outfilesuffix ".xml"
        #@libdir = File.dirname(__FILE__)
        @libdir = File.dirname(self.class::_file || __FILE__)
      end

      class << self
        attr_accessor :_file
      end

      def self.inherited( k )
        k._file = caller.first[/^[^:]+/]
      end
````

The idea is that `@libdir` updates to be the gem current directory for any gem inheriting Asciidoctor::Standoc::Converter. It way well not be working in Windows, because `caller.first[/^[^:]+/]` is not removing an initial `C:`?

**Comment by opoudjis** [comment]
The ruby documenation is misleading, because it illustrates `caller` with simple file names, of the pattern filename:line-number. The StackOverflow solution relies on the fact that they are in fact absolute file locations; e.g. on Mac, the first string in the array returned by `caller` is:

`"/Users/nickn/.rvm/gems/ruby-2.5.1/gems/byebug-11.1.1/lib/byebug/helpers/eval.rb:61:in `eval'"`

Of course, on Windows, that absolute path is going to be prefixed by `C:` or equivalent.

Switching to `caller_location.absolute_path()` will fix this

**Comment by CAMOBAP795** [comment]
@opoudjis please write an answer on SO I will vote for you
