### ISSUE TITLE
Resolve PlantUML macro TODOs by raising proper errors

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#205]
In #204 a number of TODOs need to be addressed, all in this file:
`lib/asciidoctor/standoc/macros.rb`

```ruby
        # TODO: this should raise failure if there is no image output!!
        run(umlfile, outfile) or return
        umlfile.unlink
--
        # TODO: this should raise failure if the destination path already exists!
        File.exist?(path) or return

        # TODO: this should raise failure if the destination path is not writable!
        File.writable?(path) or return
--
        # TODO: Abort should really raise an error
        warn msg
        attrs["language"] = "plantuml"
```

**Comment by ronaldtse** [comment]
These problems are leading to PlantUML errors being undetected in specs and also in real processing. When PlantUML can't be found, all it does it print out "PlantUML not found" and the processing chain crashes when the expected generated image is not found.

**Comment by ronaldtse** [comment]
Also, add a spec to test PlantUML when `:imagesdir:` is set vs `:imagesdir:` is not set.

**Comment by opoudjis** [comment]
> Also, add a spec to test PlantUML when :imagesdir: is set vs :imagesdir: is not set.

That's already there in spec/asciidoctor-standoc/macros_spec.rb:

````
  it "processes the PlantUML macro" do

....

  it "processes the PlantUML macro with imagesdir" do
````

**Comment by ronaldtse** [comment]
@opoudjis thanks for pointing that out. Updating issue now.

**Comment by opoudjis** [comment]
Decided not to raise errors per se, but to keep raising warnings with fallback of literal block rendering.
