### ISSUE TITLE
CRLF-text documents causes Metanorma to crash on macOS

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#207]
This document is from https://github.com/metanorma/mn-samples-un/pull/12 .

It was originally authored on Windows, and uses the DOS-formatted line breaks, which crashes Metanorma on macOS right away. This file apparently worked with Metanorma in Windows.

I used this command to convert DOS line breaks into Unix style line breaks before compilation worked:

```sh
tr -d '\r' < ECE_TRADE_C_CEFACT_2019_09_dos.adoc > ECE_TRADE_C_CEFACT_2019_09_unix.adoc
```

Both `ECE_TRADE_C_CEFACT_2019_09_dos.adoc` and `ECE_TRADE_C_CEFACT_2019_09_unix.adoc` files are attached here:
[Archive.zip](https://github.com/metanorma/metanorma-standoc/files/4173845/Archive.zip)

This task is to ensure Metanorma does not crash on both DOS and Unix line breaks.

**Comment by CAMOBAP795** [comment]
https://github.com/metanorma/metanorma/pull/98 - ready for review
