### ISSUE TITLE
-- rendered as em dash or en dash #191

### ISSUE THREAD

**Issue by rggibb** [metanorma/metanorma-standoc#213]
Using:
```
[[test-1]]
.Core -- Data Model
[.requirement, model="ogc", type="verification", id="http://www.opengis.net/spec/DGGS/2.0/conf/core/data_model"]
====
```
This is producing:
`<p class="RecommendationTitle">Requirement A.1:<br/>Core&amp;#8201;&amp;#8212;&amp;#8201;Data Model</p>`

So the &amp; instances are rendering as `&#8201;` etc in the htm and word docs and not interpreted as rendered thinsp and m-dash as intended. 

I think I'm using the appropriate latest metanorma:
> metanorma version
Metanorma 0.3.18
Metanorma::Cli 1.2.9
Metanorma::Standoc 1.3.17/IsoDoc 1.0.16
Metanorma::ISO 1.3.16
Metanorma::Iec 0.1.7
Metanorma::Ietf 2.0.3
Metanorma::Gb 1.3.4
Metanorma::Csd 1.3.3
Metanorma::Csa 1.4.3
Metanorma::M3d 1.3.12
Metanorma::Acme 1.4.0
Metanorma::Unece 0.2.14
Metanorma::NIST 0.2.14
Metanorma::Ogc 0.2.13
Metanorma::ITU 1.0.7

**Comment by rggibb** [comment]
Have now noticed that 
```
[[test-1]]
.Core - Data Model
[.requirement, model="ogc", type="verification", id="http://www.opengis.net/spec/DGGS/2.0/conf/core/data_model"]
====
```
Produces a properly rendered m-dash in the title. while initially a tad counter intuitive, it is useable.

**Comment by opoudjis** [comment]
Nokogiri Builder `container.tag value` does not deal with non-Unicode characters well; `<<` needs to be used consistently.
