### ISSUE TITLE
Paragraph is not rendering when footnote is present

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#215]
When a paragraph contains a footnote and is immediately below a figure item, the whole paragraph doesn't render and only the footnote is shown.

For example, consider the following markup:

````
== SAMPLE TEXT
The LEO Horizon2020 (H2020) Project developed software tools that 
support the whole lifecycle of reuse of EO data and related linked 
geospatial data. To demonstrate the benefits of linked open EO data
and its combination with linked geospatial data to the European 
economy, a precision farming application was developed (<<fig-example-application-precision-farming>>).

[[fig-example-application-precision-farming]]
.Example Application: Precision Farming (Figure Source: Manolis Koubarakis)
image::fig-example-application-precision-farming.png[]

Another example of Big Data for Agriculture includes satellite image
processing to calculate the available area of arable land. Fritz et 
al. have shown that land suitable for cultivating biofuel crops has 
been vastly overestimated. They have reduced the estimate by almost 
80 percent and expressed a growing concern about how production of 
biofuels will impact food security. Based on Big Data analytics,
Fritz's et al. study showed that previous studies had overestimated
the amount of arable land and had underestimated the amount of land
already being cultivated footnote:[http://pubs.acs.org/doi/abs/10.1021/es103338e].
````
The output obtained is:

![footnote-issue2](https://user-images.githubusercontent.com/33627611/74599379-3df40300-5057-11ea-8469-fdb99b8ef83d.JPG)
*(Red squares were added manually.)*

Notice that the paragraph placed after the figure markup is gone and only the footnote is shown. Also, there is an additional word that wasn't written in the code, "Key".

Sample file:
[footnote-issue2.zip](https://github.com/metanorma/metanorma-standoc/files/4209365/footnote-issue2.zip)

**Comment by opoudjis** [comment]
In figure_footnote_cleanup, footnotes after a figure are merged into the figure. But that must not apply to a footnote in a nonempty paragraph after a figure.
