### ISSUE TITLE
Implement `metanorma setup` procedure to allow installation of necessary fonts

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#217]
Native PDF functionality requires installation of the `mn2pdf` tool, and it should be installed together with metanorma-standoc.

The instructions to compile `mn2pdf` is given in https://github.com/metanorma/mn-native-pdf.

Once this is included we can get rid of Puppeteer.

**Comment by ronaldtse** [comment]
This is a blocker to:
* https://github.com/metanorma/metanorma-docker/issues/62
* https://github.com/metanorma/homebrew-metanorma/issues/36
* https://github.com/metanorma/metanorma-linux-setup/issues/21
* https://github.com/metanorma/chocolatey-metanorma/issues/38

**Comment by opoudjis** [comment]
Already done in feature/xslfo branch.
