### ISSUE TITLE
Upgrade dependency to Relaton

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#218]
Relaton version is now locked to 0.5.0, but it is now at 0.10.0 with a number of fixes and improvements. It is also blocking the usage of relaton-cli which is now of a higher version.

We need to upgrade Relaton in metanorma-standoc.

Related to https://github.com/relaton/relaton-cli/issues/73

**Comment by opoudjis** [comment]
Discussed. relaton dependency was in fact upgraded to 0.7 in January, and to 0.10 on Feb 27 (just after Metanorma release). bundler is having trouble reconciling relaton being released in advance of metanorma.

As mitigation, have added relaton-cli dependency into metanorma-cli, which will be updated each metanorma release.

**Comment by ronaldtse** [comment]
@opoudjis this should be also fixed in metanorma/metanorma-cli@684502ba78fa3ab955ac9e8132612cdef77547ca

**Comment by opoudjis** [comment]
... I thought you WANTED the relaton-cli dependency fixed in metanorma. 

I will not be tinkering with versions any more; this is not a good use of my time.

**Comment by ronaldtse** [comment]
@opoudjis Yes I wanted it fixed. This is all done now thanks to your commit. 4671aa501390bc8918bac0d3c763af9c7d313743
