### ISSUE TITLE
Tables get too wide (DOC output)

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#219]
If a table cell contains a very large string of characters (e.g. a large hyperlink), the whole table gets wide beyond the boundaries of the document.
For example, consider the following table sample:
````
[%unnumbered]
[cols="4"]
|===
h|Parameter name h|KVP Example h|Optionality/ multiplicity h|Definition, format and use

|Styles |`Styles=` |Mandatory, one |Comma separated list of one rendering style per requested collection. Shall be implemented by both client and server.

|Options |`Options.mpeg2.codec=h264&Options.mpeg2.stream=transport&Options.mpeg2.kbps=000&Options.mpeg2.fps=29.977` |Optional, zero or one |Vendor specific options for this request. Extends the request. (Default: Options=). Shall be optionally implemented by both client and server.

|Path |`Path=URL Encoded XML` |Mandatory, one |Specifies the tracks to be rendered by the service. Shall be implemented by both client and server.
|===
````

The respective outputs result in:

*HTML*:
![capture1](https://user-images.githubusercontent.com/33627611/76344367-d50b4e00-62d7-11ea-8f94-3b4063d872db.PNG)

*DOC*:
![capture2](https://user-images.githubusercontent.com/33627611/76344375-d89ed500-62d7-11ea-8f7e-22668af8cbdc.PNG)

A workaround would be to introduce blank spaces in random positions, but if it were a hyperlink, maybe this wouldn't be suggested.

Thanks!

Sample file:
[table-wide-issue.zip](https://github.com/metanorma/metanorma-standoc/files/4314021/table-wide-issue.zip)

**Comment by opoudjis** [comment]
This is intervention I'm not very happy about, but: if we encounter a very long string of text in isodoc ouput, longer than 80 chars in normal text, and longer than 40 chars  in tables, we should aim for inserting space at any `[&=?.,]` within 10 chars of n * 80 (or n * 40), or failing that at the cutoff.

**Comment by ronaldtse** [comment]
@opoudjis does Word not have any measure for overflowing tables?

**Comment by opoudjis** [comment]
Space is inserted at the best place it can find every 30 characters; so the long URL ends up as:

````
Options.mpeg2.codec= h264&Options.mpeg2.stream= transport&Options.mpeg2.kbps=000&Options. mpeg2.fps=29.977
````

Yes, there is a second space. That's my solution; I can't guess in the general case how many spaces are needed, and whether there will be a line break each one.

**Comment by ronaldtse** [comment]
@opoudjis I think this behavior is going to break some URLs and affect click-ability. I'd rather the DOC be broken and fixed manually?

**Comment by manuel489** [comment]
Well, actually, the workaround that I proposed above in the description was meant to be achieved by the user. Entering the blank spaces manually, whether into the code, or directly into the .doc file.

**Comment by opoudjis** [comment]
> @opoudjis I think this behavior is going to break some URLs and affect click-ability. 

> Well, actually, the workaround that I proposed above in the description was meant to be achieved by the user.

1. @manuel489 : if you're going to ask me to address an issue, that's a request for coding. If this was something that users were going to address by inserting spaces, then why ask me to get involved at all?

2. @ronaldtse : This is about text, it explicitly sidesteps the content of the hyperlink. No URLs broken, no clickability broken.

@ronaldtse Do you want me to rescind this fix?

**Comment by ronaldtse** [comment]
> This is about text, it explicitly sidesteps the content of the hyperlink. No URLs broken, no clickability broken.

Then the fix should be good, for now. Thanks.

**Comment by manuel489** [comment]
> @manuel489 : if you're going to ask me to address an issue, I have to assume that's a request for coding. If this was something that users were going to address by inserting spaces, then why ask me to get involved at all?

@opoudjis , yes you're right. I'm afraid I have expressed myself in the wrong way and that may have caused you unnecessary extra work. I apologize.

What I meant to say with this "workaround" is that user can take action on solving the issue by adding blank spaces in the code (or directly in the doc output) but, if the text happens to be a link, that action wouldn't be suggested because, as @ronaldtse says, it would break the hyperlink behavior. So, I opened this issue to see if you can find another solution via coding that would not require user intervention and would not affect the click-ability of the hyperlink, which, judging by your answer in the above messages, you managed to achieve.

I will make a test of your solution and let you know. Thanks.

**Comment by manuel489** [comment]
The fix works just perfect! Thanks @opoudjis !

**Comment by opoudjis** [comment]
Well... it will occasionally put spaces where a human would not. So I am still not very enthusiastic about it. But yes, by default, it looks presentable. If  of course you put the spaces in yourself, then the renderer is not going to find a sequence of 30 characters to break up, so your spaces will be respected.
