### ISSUE TITLE
(URGENT) IEV citation currently broken, regression

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#224]
```adoc
[[term-instant]]
===== instant

point on the _time axis_ (<<term-time-axis>>)

NOTE: An instantaneous event occurs at a specific instant.

[.source]
<<IEV,clause "113-01-08">>
```

Currently renders as:
<img width="451" alt="Screen Shot 2020-03-25 at 4 23 04 PM" src="https://user-images.githubusercontent.com/11865/77516222-f4e46980-6eb4-11ea-9d31-94f31985651c.png">

This is a regression, it used to show the proper citation correctly.

In the bibliography, you can see the documents references are correct, except that:

1. The correct reference is not shown in the citation
2. The "IEC Electropedia" reference should not show up in Bibliography.

<img width="1059" alt="Screen Shot 2020-03-25 at 4 24 42 PM" src="https://user-images.githubusercontent.com/11865/77516330-2826f880-6eb5-11ea-850e-61f62046d9fe.png">

NOTE: Need to create specs for this.

**Comment by opoudjis** [comment]
I cannot replicate this in either ISO or ITU. Please point me to the source document.

**Comment by opoudjis** [comment]
Markup error: `[[[IEV,IEC Electropedia]]]` should be `[[[IEV,IEV]]]`: IEV is recognised as such by bibliographic identifier, not anchor.
