### ISSUE TITLE
error file writing tested for all flavours

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#225]
And File.join to form file path

**Comment by ronaldtse** [comment]
Need to add example file run for ALL FLAVORS.

**Comment by opoudjis** [comment]
It'll be a one-line file then. Testing takes too long already.

**Comment by opoudjis** [comment]
I do one example, with minimal file with error, written to a subdirectory, then assign to @w00lf to do remainder.

**Comment by opoudjis** [comment]
Need the following test added to all metanorma-* gems, from metanorma-standoc:

It is in metanorma-standoc/spec/asciidoctor-standoc/validate_spec.rb

````
  it "generates error file" do
  FileUtils.rm_f "spec/assets/xref_error.err"
  Asciidoctor.convert_file "spec/assets/xref_error.adoc", {:attributes=>{"backend"=>"standoc"}, :safe=>0, :header_footer=>true, :requires=>["metanorma-standoc"], :failure_level=>4, :mkdirs=>true, :to_file=>nil}
  expect(File.exist?("spec/assets/xref_error.err")).to be true
  end
````

The file xref_error.adoc should be copied from metanorma-standoc/spec/assets/xref_error.adoc, which should be added in to the gem. It should always be coped to the spec/assets subdirectory, which should be created if it does not exist.

The test needs to be updated, to replace all mentions of "standoc" with the flavour name; i.e. for metanorma-iso, the command becomes:

````
  Asciidoctor.convert_file "spec/assets/xref_error.adoc", {:attributes=>{"backend"=>"iso"}, :safe=>0, :header_footer=>true, :requires=>["metanorma-iso"], :failure_level=>4, :mkdirs=>true, :to_file=>nil}
````

**Comment by opoudjis** [comment]
@w00lf Taking this task off you

File test needs to be run in metanorma. This leads to unfortunate circular dependency for testing purposes, which makes major releases of metanorma a car crash (as I've just found); but that can't be helped.
