### ISSUE TITLE
Usage of IEV citation causes duplicated bibliographic references

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#226]
Follow up of https://github.com/metanorma/metanorma-standoc/issues/224 : 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/11865/77643655-ba54fc80-6f9a-11ea-903f-eaa175ded53b.png">

```
Syntax: (XML Line 000822:54): ID "IEC60050-113" has already been defined
Syntax: (XML Line 000744:24552): first occurrence of ID "IEC60050-113"
Syntax: (XML Line 000822:2607): ID "IEC60050-713" has already been defined
Syntax: (XML Line 000784:54): first occurrence of ID "IEC60050-713"
```

**Comment by opoudjis** [comment]
Has already been addressed in #224: any new additions detect any collisions in ID anchor (e.g. if IEC 60050 document occurs with different year), and add "-1" to the anchor to avoid collision.
