### ISSUE TITLE
Parentheses get exaggeratedly large in math mode - Bug ticket?

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#228]
*Encoding sample:*
````
[stem]
++++
(1)/(z + (( - k)/((1 + (1)/(z + ((1 - k)/((1 + (2)/(z + ((2 - k)/((1 + (3)/( ... )))))))))))))
++++
````

*Asciidoctor output:*
![asciidoc-cap](https://user-images.githubusercontent.com/33627611/77839546-b0bec680-714b-11ea-8e57-d35cfc90799a.PNG)

*Metanorma HTML output:*
![html-cap](https://user-images.githubusercontent.com/33627611/77839551-bae0c500-714b-11ea-8d4f-63ddc25c5f9d.PNG)

As it seems this behavior comes from asciidoctor itself, I'm not sure if we should consider it as a bug.

Thanks!

**Comment by ronaldtse** [comment]
This issue is from MathJax the JS plugin we use in HTML. We’re not going to fix this but we can file a bug at MathJax.

**Comment by opoudjis** [comment]
Forcing the numerator and denominator to have the same height... gives these results, but I'm not sure everyone will regard it as a bug. 

Word does exactly the same thing with this. This is standard maths rendering, I don't think we should do anything about it...

**Comment by manuel489** [comment]
This issue is already solved.
