### ISSUE TITLE
Location of generated error file 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#229]
As a follow up to #223, the location of the generated error file should "accompany the destination file". Right now, it is created in the "source" directory, but it should go into the "destination" directory.

Sorry @opoudjis for the mistake in the original ticket!

**Comment by opoudjis** [comment]
Metanorma does not differentiate this. It always outputs files into the same directory as where the source file is; your makefiles are what shuffle things into a destination directory. Metanorma has no notion of specifying a distinct destination directory; and if there is to be one, that will be the business of metanorma-cli.

I'm not actioning this in its present form. Either the makefiles deal with this, or metanorma-cli does; I do not believe that metanorma-standoc should.

**Comment by ronaldtse** [comment]
I forgot that metanorma-standoc doesn't have a notion of an output directory. Our Makefiles were meant to achieve this purpose. The https://github.com/metanorma/metanorma-cli/issues/134 issue is meant for this, so let's close this for now.
