### ISSUE TITLE
Relax NIST bibliography grammar to accept document-class and short-title

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#231]
@opoudjis just to inform you, the [NIST grammar](https://github.com/metanorma/metanorma-model-iso/blob/4d21b5c3056437eeded78efab68c6195cf76fb52/grammars/nist.rnc#L12) still have title type constraint.

These lines are generated by metanorma-nist but not accepted in the NIST bibliography grammar:

```xml
<title language="en" format="text/plain" type="document-class">Information Security</title>
<title language="en" format="text/plain" type="document-class">Computer Security</title>
<title language="en" format="text/plain" type="short-title">Security Considerations for Code Signing</title>
```

Moved from https://github.com/relaton/relaton-cli/issues/77

_Originally posted by @andrew2net in https://github.com/relaton/relaton-cli/issues/75#issuecomment-605706267_

**Comment by opoudjis** [comment]
This is a general requirement to relax title types throughout metanorma.

**Comment by opoudjis** [comment]
... as it turns out, only NIST was forcing its own title types.
