### ISSUE TITLE
References: Mixing auto-fetch with numbered-reference-tags

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#232]
The user-defined reference tag format is described here:

https://www.metanorma.com/author/topics/document-format/bibliography/#named-reference-tag-with-automatic-reference-fetching

```adoc
* [[[ISO20483,(CerMoist)ISO 20483]]], _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,(MaiMoist)ISO 6540]]]. _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
```

There is also the "numeric" tag. If we combine the numeric tag with auto-fetch syntax, we get this:

```
* [[[ISO20483,(1)ISO 20483]]], _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,(2)ISO 6540]]]. _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
```

Here's what we did in metanorma/mn-samples-iho#4, but it doesn't work:

```adoc
[bibliography]
=== References

* [[[iho_ts_dhd,(1)IHO S57]]], S57 edition 3.1: IHO Transfer Standard for Digital Hydrographic Data, International Hydrographic Organization (www.iho.int)

* [[[dss,(2)NIST FIPS 186]]], Digital Signature Standard (DSS), FIPS Pub 186 (www.itl.nist.gov/div897/pubs/fip186.htm)

* [[[sha,(3)NIST FIPS 180-1]]], Secure Hash Standard (SHA), FIPS Pub 180-1 (www.itl.nist.gov/div897/pubs/fip180-1.htm)

* [[[ITU-T_X.509,(4)ITU-T X.509]]], Information Technology – Open Systems Interconnection – The Directory: Authentication Framework. X.509 version 3 - International Telecommunication Union

* [[[zip_ffs,(5)ZIP File Format Specification]]], ZIP File Format Specification, PKWare Inc.

* [[[des_mf,(6)NIST FIPS 81]]], DES Modes of Operation, FIPS Pub 81 (www.itl.nist.gov/fipspubs/fip81.htm)

* [[[rfc1423,(7)IETF RFC 1423]]], RFC 1423: Privacy Enhancements for Internet Electronic Mail: Part III: Algorithms, Modes and Identifiers

* [[[blowfish_ref,(8)Blowfish encryption algorithm]]], Blowfish encryption algorithm, B. Schneier, Fast Software Encryption, Cambridge Security Workshop Proceedings (December 1993), Springer-Verlag, 1994, pp. 191-204. (www.counterpane.com)

* [[[crc32,(9)ISO/IEC 13239:2002]]], CRC32 checksum algorithm. Information technology -- Telecommunications and information exchange between systems -- High-level data link control (HDLC) procedures. ISO/IEC 13239:2002.
```

As @anermina reported:
> In generated document, reference numbers are repeated (yellow highlighted):

![image](https://user-images.githubusercontent.com/11865/77870108-19ed2980-7273-11ea-83be-0fd9dd4fbe3e.png)

And the auto-fetched document ID is not showing.

**Comment by opoudjis** [comment]
This is not happening under ITU, so this is not a general issue.

````
[4]  Recommendation ITU-T X.509 | ISO/IEC 9594-8, Information technology – Open Systems Interconnection – The Directory: Public-key and attribute certificate frameworks.

[CerMoist]  ISO 20483:2013 ( 2013 ), Cereals and pulses – Determination of the nitrogen content and calculation of the crude protein content – Kjeldahl method.

[MaiMoist]  ISO 6540:1980 ( 1980 ), Maize – Determination of moisture content (on milled grains and on whole grains).

[9]  ISO/IEC 13239:2002 ( 2002 ), Information technology – Telecommunications and information exchange between systems – High-level data link control (HDLC) procedures.

[7]  IETF RFC 1423 | rfc-anchor RFC1423 ( 1993), Privacy Enhancement for Internet Electronic Mail: Part III: Algorithms, Modes, and Identifiers.

[3]  NIST FIPS 180-1 ( 1995), Secure Hash Standard.

[2]  NIST FIPS 186-4 ( 2013), Digital Signature Standard (DSS).

[6]  NIST FIPS 81 ( 1980), DES Modes of Operation.

[8]  Blowfish encryption algorithm, Blowfish encryption algorithm, B. Schneier, Fast Software Encryption, Cambridge Security Workshop Proceedings (December 1993), Springer-Verlag, 1994, pp. 191-204. (www.counterpane.com).

[1]  IHO S57, S57 edition 3.1: IHO Transfer Standard for Digital Hydrographic Data, International Hydrographic Organization (www.iho.int).

[5]  ZIP File Format Specification, ZIP File Format Specification, PKWare Inc.
````

**Comment by opoudjis** [comment]
... but I need to take the opportunity to dodge rfc-anchor in ITU.

**Comment by opoudjis** [comment]
This is unearthing that different flavours are not coping well with metanorma identifiers (the numbers in the instance above). But @anermina, I do not know which flavour specifically you are using to render IHO documents, so I cannot replicate your results. Please indicate which flavour it is.

**Comment by opoudjis** [comment]
If a metanorma (user supplied) ID ends up in normative references, it needs to be put in square brackets, same as for bibliography.

**Comment by ronaldtse** [comment]
> If a metanorma (user supplied) ID ends up in normative references, it needs to be put in square brackets, same as for bibliography.

I understood every word here but couldn't figure out what it means. Can you illustrate with an example? 😉

**Comment by anermina** [comment]
> Please indicate which flavour it is.

@opoudjis I used OGC flavour for generating this document.

**Comment by opoudjis** [comment]
@ronaldtse Normative references in isodoc (following ISO) are assumed always to have an identifier. If the user supplied identifier is the only identifier available, it will be put in brackets in the bibliography, consistent with how user supplied identifiers appear in the bibliography;

`<p id='zip_ffs' class='NormRef'>[5], Title 5</p>`

The alternative, `<p id='zip_ffs' class='NormRef'>5, Title 5</p>`, just looks wrong.

**Comment by opoudjis** [comment]
In NIST, ignoring metanorma as a document identifier used in bibliography body.

**Comment by opoudjis** [comment]
And in ITU, likewise, ignore metanorma ids as document identifier used in bibliography body.
