### ISSUE TITLE
Move boilerplate text into a place where they are more editable: AsciiDoc/YAML instead of XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#233]
In every flavor we have boilerplate text: license, warnings, copyright, patent notices.

We should move (and consolidate) boilerplate text into a place where they are more editable: AsciiDoc/YAML instead of XML.

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-ogc/issues/118#issuecomment-605750781_

**Comment by opoudjis** [comment]
In addition: request that Asciidoctor document clause be used with role to populate boilerplate sections.

Potentially, request that Asciidoctor document clause be used to override individual clauses with same identifier in gem-supplied boilerplate.

**Comment by ronaldtse** [comment]
Right now we have to resort to XML boilerplate like this:
* https://github.com/metanorma/mn-samples-bsi/pull/297

We should get this task going.

**Comment by opoudjis** [comment]
Start by translating boilerplate Asciidoctor into XML.

**Comment by opoudjis** [comment]
The Asciidoctor uses its top clauses for tags: copyright-statement, license-statement, etc.

{{ }} in Liquid is also concept markup in Asciidoctor, and breaks Metanorma parsing. So will Liquid preprocess the boilerplate before converting it to XML.

**Comment by ronaldtse** [comment]
@opoudjis are you sure you don’t want to use Coradoc for parsing these snippets instead?

**Comment by opoudjis** [comment]
Never mention that abomination in my presence again.

It is manifestly obvious that the Asciidoc in the boilerplate should be parsed by the same parser as the text in the document, including any flavour-specific customisations (and they do exist.)

**Comment by opoudjis** [comment]
The parser is in place (and didn't take a lot); what remains is to start translating the XML into Asciidoctor for all the gems. The parser will accept both XML and ADOC.

**Comment by ronaldtse** [comment]
> Never mention that abomination in my presence again.
> 
> It is manifestly obvious that the Asciidoc in the boilerplate should be parsed by the same parser as the text in the document, including any flavour-specific customisations (and they do exist.)

This is an unfair comment — Coradoc is a way superior parser compared to Asciidoctor because it is entirely model based.

**Comment by opoudjis** [comment]
It is way inferior for the purposes of Metanorma in that there are any number of Metanorma- and flavour-specific enhancements in the Metanorma asciidoctor processing code, which coradoc won't know jack about. Including *all* Metanorma-specific macros, and *most* Metanorma-specific attributes. (How did you think those Metanorma-specific attributes attached to the model?)

That is a firm no.

**Comment by opoudjis** [comment]
The IEEE boilerplate specifies a distinct, non-numeric identifier, which is identified explicitly and rendered as an asterisk. Need to override the default ID assignment of footnotes with a user-supplied identifier.

**Comment by opoudjis** [comment]
No, we'll insert those in post-processing.

Need to get rid of empty paragraphs: we want to mark up:

````
<ul>
<li><dl><dt>A</dt><dd>B</dd></li>
</ul>
````

We use

````
* {blank}
a::: b
````

We are getting

````
<ul><p/>
<li><dl><dt>A</dt><dd>B</dd></li>
</ul>
````

<p/> does not belong in our XML. If we do want spacing paragraphs, they should contain a space, for clarity: `<p>&nbsp;</p>`

**Comment by opoudjis** [comment]
Conversion of boilerplate top-level titles restricted to _*-statement_

**Comment by opoudjis** [comment]
Need to remove default namespace from processed boilerplate, since it hasn't yet been added to the entire document.

**Comment by opoudjis** [comment]
Arguments to be passed into Boilerplate are properly Metanorma XML or HTML, since they expected to be inserted into Metanorma XML or HTML. Now that they are being inserted into Asciidoctor, they need to be inserted as passthroughs.

**Comment by opoudjis** [comment]
If a clause has no title and no user-assigned anchor, it gets assigned _{n} as its anchor, with consecutive numbering.

Both the boilerplate and the main document are doing this to their untitled clauses, which means that if both have untitled clauses with no  user-assigned anchor, this results in collision of anchor _2 occurring twice.

The problem is, we have no means of telling whether a user has assigned the _2, or the _2 is autogenerated. However, I am going to proceed on the assumption that there can be no _{n} anchors in the boilerplate, and overwrite them with UUIDs; and I will document that constraint.

**Comment by ronaldtse** [comment]
@opoudjis looks like the asciidoc boilerplate isn't implemented for BSI?

**Comment by opoudjis** [comment]
You're right, will add now
