### ISSUE TITLE
Greater than, and less than characters (">", "<") are not rendering in table mode

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#239]
String characters like: `<<random text>>` and `<random text>` are not working properly in table mode, DOC output.

For example:

*Code:*
````
== In normal mode (paragraph)

\<<random text>>, <random tex>

== In table mode


[cols="a,a,a",options="header"]
|===
|Header1 |Header2 |Header3 

| \<<CodeList>>
| \<<Enumeration>>
| \<<DataType>>
|===

== Another example

[cols="a,a,a",options="header"]
|===
|Header1 |Header2 |Header3 

|<Attribute>
|<filePath>
|<Full path from the exchange set root directory>
|===
````

*HTML output:*
![html-capture](https://user-images.githubusercontent.com/33627611/78462567-7c925b00-76a1-11ea-8d5d-a51576dd9f5e.PNG)

*DOC output:*
![doc-capture](https://user-images.githubusercontent.com/33627611/78462568-7e5c1e80-76a1-11ea-9f88-5fe93a749355.PNG)

*AsciiDotor:*
![asciidoctor-capture](https://user-images.githubusercontent.com/33627611/78462571-84ea9600-76a1-11ea-84cf-74073842f49e.PNG)

Sample file:
[character-issue.zip](https://github.com/metanorma/metanorma-standoc/files/4432638/character-issue.zip)

Thanks!

**Comment by opoudjis** [comment]
That was fixed in https://github.com/metanorma/metanorma-ogc/issues/122, included in the latest release of isodoc (1.0.23) released Friday. @manuel489 Could you please confirm the latest release fixes this?

**Comment by manuel489** [comment]
Yes, it is fixed. Sorry @opoudjis . Closing.

**Comment by opoudjis** [comment]
No problem. It was only a day apart :)
