### ISSUE TITLE
Six level section titles aren't working

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#240]
The sixth level of section title isn't working. 

*Code sample:*
`````
== Level 1

=== Level 2

==== Level 3

===== Level 4

====== Level 5

======= Level 6
`````

*Output:*
![six-level-cap](https://user-images.githubusercontent.com/33627611/78501644-6d0b2480-772a-11ea-9968-c1c77f83ffb0.PNG)

(Test performed with `metanorma-standoc 1.3.23`)

Thanks!

Sample file:
[six-level-issue.zip](https://github.com/metanorma/metanorma-standoc/files/4434089/six-level-issue.zip)

**Comment by opoudjis** [comment]
I refer both you and @ronaldtse to the manual.

https://www.metanorma.com/author/topics/document-format/sections/#sections-deeper-than-5-levels

You must use `[level=6]`.

**Comment by manuel489** [comment]
Update added in https://github.com/metanorma/mn-samples-iho/pull/15

**Comment by ronaldtse** [comment]
Asciidoctor 2.0 no longer has the limitation on section headers. We shouldn't either. The point of this ticket is to make 6+ levels work.

**Comment by opoudjis** [comment]
Not at all convinced Asciidoctor 2.0 doesn't have that limitation, but I'll find out when I get to this.

**Comment by opoudjis** [comment]
Almost certain that @ronaldtse has confused the limit of nested lists, which was 6 before v1.5.8, and the limit of headings:

https://asciidoctor.org/docs/user-manual/

https://asciidoctor.org/docs/user-manual/#sections-summary : Section numbering is only possible up to level 5. The same constraint applies to Table of Contents levels: https://asciidoctor.org/docs/user-manual/#table-of-contents-summary

https://asciidoctor.org/docs/user-manual/#nested:

> In Asciidoctor 1.5.7 and earlier you could only have up to six (6) levels of nesting (assuming one level uses the hyphen marker). Since Asciidoctor 1.5.8, you can nest unordered lists to any depth

Headings are still behaving the same in v2 with current code, and current code is not imposing a constraint on heading nesting. Confirming in Asciidoc source code:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/rx.rb

````
AtxSectionTitleRx = /^(=={0,5})[ \t]+(#{CC_ANY}+?)(?:[ \t]+\1)?$/

  # Matches an extended Atx section title that includes support for the Markdown variant.
  ExtAtxSectionTitleRx = /^(=={0,5}|#\#{0,5})[ \t]+(#{CC_ANY}+?)(?:[ \t]+\1)?$/
````

**Comment by ronaldtse** [comment]
My bad here, it's broken by nature.

**Comment by opoudjis** [comment]
@manuel489 Proceed with the workaround as before; the constraint is still there.
