### ISSUE TITLE
Introduce release date

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#246]
Introduce release date to allow transforming Metanorma XML into NISO STS.
NISO STS format has pub-date and release-date elements.
For pub-date we can use MN XML element bibdata/date[@type="published"]. But for release-date there isn't such element.
Example of NISO STS xml part:
```
<pub-date>2019-03-15</pub-date>
<release-date>2018-10-31</release-date>
```

Comment from NISO-STS-common-metadata1.ent (https://www.niso-sts.org/DTDs-XSDs-RNGs-alternative.html -> https://www.niso-sts.org/downloadables/DTDs/v1-0/NISO-STS-1.0-All-DTDs.zip):

```
The <pub-date> was used in ISO STS to name
the date this standard was (or was to be)
published. This element has been superseded
by <release-date> but may still appear in 
documents for backward compatibility with 
ISO STS.
  Remarks: While this element may still be
used, for better JATS compatibility, the
date of initial publication should be
recorded using <release-date> with the
appropriate attributes.
  Remarks: For ISO STS published standards,
the <pub-date> recorded the date on which
the project reached ISO stage 60, and the
IS was first published. For the initial
publication, the <pub-date> and the
<release-date> were the same. For later ISO
 publications (corrections, new editions,
versions in other languages), the <pub-date>
would be earlier than the <release-date> (and
was be the same across all versions of a
given standard).

```

**Comment by ronaldtse** [comment]
Thanks for posting this @Intelligent2013 . We could add them as bibliographic dates:

* date of base document publication
* date of derived document publication (Amendment, Tech Corr, Translations, etc)

**Comment by opoudjis** [comment]
I would much prefer the relation to be the latter: for document X, "date of base document publication" = `X/bibdata/relation[@type = "updates"]/bibitem[edition.text() = "1"]/date[@type = "published"]`.

I think you see the problem with that though. A document is in an "updates" relation with all its previous editions, and we cannot assume that all first editions are going to be coded as `<edition>1</edition>`.

And if we can't reliably encode that, then we will need `date[@type = "firstpublished"]`, ugly though it is.

@ronaldtse ?

**Comment by opoudjis** [comment]
Our decision, @ronaldtse and mine, is for the time being to proceed with the former option:

````
<bibdata>
  ....
  <date type="published">PUB-DATE</date>
  ....
  <relation type="updates">
    <bibitem>
      ....
      <date type="published">RELEASE-DATE</date>
       ....
      <edition>1</edition>  
    </bibitem>
  </relation>
</bibdata>
````

If that doesn't work -- because we cannot rely on first editions to be numbered 1 -- I will either introduce `<edition first="true">` to insist on it, or else concede or introduce `date[@type = "firstpublished"]`

**Comment by ronaldtse** [comment]
Discussed and agree with @opoudjis , thanks.

**Comment by opoudjis** [comment]
> Discussed and agree with @opoudjis , thanks.
> 
> There are additional issues:
> 
> 1. Which bibitem do we know should contain the "release date"? The first relation with "updates"? The "base document"? Probably the "base document".

As you can see, it is the relation with updates, and with a first edition indicated.

> 2. Does the base document need to have the same docidentifier as the current document? Probably not.

No, "updates" takes care of that:

> updates
>document B is an edition of the same Work as document A, and is subsequent to document A; A is an Expression (updatedBy)

**Comment by ronaldtse** [comment]
> As you can see, it is the relation with updates, and with a first edition indicated.

Can you provide a syntax to demonstrate how to use this?

> No, "updates" takes care of that:

Can you provide a syntax to demonstrate how to use this?

**Comment by opoudjis** [comment]
>>> Which bibitem do we know should contain the "release date"? The first relation with "updates"? The "base document"? Probably the "base document".
>> As you can see, it is the relation with updates, and with a first edition indicated.
> Can you provide a syntax to demonstrate how to use this?

````
<bibdata>
  ....
  <date type="published">current edition publication date</date>
  ....
  <relation type="updates">
    <bibitem>
      ....
      <date type="published">RELEASE-DATE</date>
       ....
      <edition>1</edition>  
    </bibitem>
  </relation>
</bibdata>
````

>>> Does the base document need to have the same docidentifier as the current document? Probably not.
>> No, "updates" takes care of that:
> Can you provide a syntax to demonstrate how to use this?

... The definition takes care of that:

> updates
> document B is an edition of the same Work as document A, and is subsequent to document A; A is an Expression (updatedBy)

If two standards documents are editions of the same Work, that means that they will have the same document number (which identifies the Work), but different publication years or edition numbers. If they were unrelated documents, with one document replacing another in its coverage, the relation would be "obsoletes", not "updates".
