### ISSUE TITLE
Introduce table's width property

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#250]
Introduce table's width property to better display in PDF and allow transforming Metanorma XML into NISO STS.
NISO STS format has such attribute @width:
```
<table width="638">
<col width="14%"/>
<col width="15.09%"/>
<col width="17.92%"/>
<col width="26.41%"/>
<col width="26.58%"/>
<thead>
<tr>
```

**Comment by opoudjis** [comment]
Turns out has already been implemented.
