### ISSUE TITLE
Introduce table's column's width property

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#251]
Introduce width property for each column in table for better display in PDF and allow transforming Metanorma XML into NISO STS.
NISO STS format has such attribute @width for 'col' elements:
```
<table width="638">
<col width="14%"/>
<col width="15.09%"/>
<col width="17.92%"/>
<col width="26.41%"/>
<col width="26.58%"/>
<thead>
<tr>...
```

**Comment by opoudjis** [comment]
Tightening the requirement on the cols attribute: each column needs to be given an explicit width number, in order for there to be a valid colgroup element, and there needs to be more than one column. `[cols="2"]` will not be recognised as having equal width.

**Comment by opoudjis** [comment]
The output is:

````
<table>
<colgroup>
<col width="...%"/>
<col width="...%"/>
<col width="...%"/>
</colgroup>
</table>
````

The colgroup element is optional.
