### ISSUE TITLE
Introduce extended id for eref

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#253]
Introduce extended id property for eref (or change bibitemid) to allow better transforming Metanorma XML into NISO STS.

NISO STS format has such sts-id
```
<std std-id="iso:std:iso:8601:ed-3:en" type="dated">
   <std-ref>ISO 8601:2004</std-ref
</std>
```
Note: std-id - is not unique id.

**Comment by ronaldtse** [comment]
This ID applies to ISO and IEC documents as per RFC 5141 https://tools.ietf.org/html/rfc5141. 

We should utilize this scheme for all ISO/IEC documents.

**Comment by ronaldtse** [comment]
> This ID applies to ISO and IEC documents as per RFC 5141 https://tools.ietf.org/html/rfc5141.

I think this URN should be generated by Relaton. Let me open a ticket there.

**Comment by opoudjis** [comment]
If the URN (whatever it is) is already in the reference as generated by relaton, then there is no need for it to also be present in eref, right? the STS transform can simply look up the reference that the eref is linking to, retrieve the URN, and use that as its std-id. Inserting it in the eref of Metanorma XML would be a really bad thing to do, and it is clearly unnecessary.

**Comment by opoudjis** [comment]
This issue is on hold awaiting relaton/relaton-iso#85

**Comment by opoudjis** [comment]
So given:

````
<eref type="inline" bibitemid="ref1" citeas="ISO 19160-1"/>

....

<bibitem type="standard" id="ref1">
...
  <docidentifier type='URN'>urn:iso:std:iso:123</docidentifier>
...
</bibitem>
````

you should be able to retrieve the URN: `<std std-id="X">`, where X = `//bibitem[@id = 'R']/docidentifier[@type = 'URN']`, and R = `eref/@bibitemid`.
