### ISSUE TITLE
Math expressions ("<" sign) is not rendering well in definition lists

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#256]
From @anermina 

While editing ISO 10303-50, I've noticed that one stem expression is not rendering well when written in a definition of some item, although it is rendering well when it's written in a regular paragraph. This issue is yellow highlighted in the image below.

![image](https://user-images.githubusercontent.com/11865/79707305-a331d200-82ee-11ea-961e-393db5857fd6.png)

[test.zip](https://github.com/metanorma/iso-10303/files/4500839/test.zip)

**Comment by opoudjis** [comment]
I cannot replicate this: I am getting the expression intact in both locations. @anermina and @manuel489, can you both try again? And if this happens for either of you, can you please include the XML and HTML in what you send me?

**Comment by anermina** [comment]
I can confirm this is no longer an issue. In both example document and ISO 10303-50, expected result is produced.
