### ISSUE TITLE
Supporting locality indicators in documents for technical corrigendum/amendments

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#259]
We need a locality reference mechanism to define what things to change in technical corrigenda/amendments:

```
=== Page 14, 4.3.1 _array_based_unstructured_mesh_

_Some attributes referenced in the EXPRESS are not properly defined, Remove the EXPRESS definition of this entity and replace with:_

EXPRESS specification:

[%unnumbered]
[source,html]
----
*)
ENTITY array_based_unstructured_mesh
...
(*
----
```

This can be specified like:

```
// the container
[locality,page=14,clause=4.3.1,title=_array_based_unstructured_mesh_]
====

// Human-readable message
_Some attributes referenced in the EXPRESS are not properly defined, Remove the EXPRESS definition of this entity and replace with:_

// the actual location of change
[replace_with,locality=./source]
======
[%unnumbered]
[source,html]
----
*)
ENTITY array_based_unstructured_mesh
...
(*
----
======

====
```

This is also necessary for rendering of the TC/Amd, e.g.:

```
=== Page 27, table 2

_This table contains information on polygon cells which are not included in ISO 10303-52. Remove table 2 completely and replace with:_

.Edges of triangle and quadrilateral cells
|===
2+^.^h| triangle 2+^.^h| quadrilateral
^.^| edge ^.^| vertices ^.^| edge ^.^| vertices
^.^| 1 ^.^| 1, 2 ^.^| 1 ^.^| 1, 2
^.^| 2 ^.^| 2, 3 ^.^| 2 ^.^| 2, 3
^.^| 3 ^.^| 3, 1 ^.^| 3 ^.^| 3, 4
| | ^.^| 4 ^.^| 4, 1
|===
```

Here, the table needs to be rendered as:
* Table 2 -- Edges of triangle and quadrilateral cells

So this sort of syntax is necessary:

```
// the container
[locality,page=27,table=2]
====

_This table contains information on polygon cells which are not included in ISO 10303-52. Remove table 2 completely and replace with:_

[replace_with]
======
.Edges of triangle and quadrilateral cells
|===
2+^.^h| triangle 2+^.^h| quadrilateral
^.^| edge ^.^| vertices ^.^| edge ^.^| vertices
^.^| 1 ^.^| 1, 2 ^.^| 1 ^.^| 1, 2
^.^| 2 ^.^| 2, 3 ^.^| 2 ^.^| 2, 3
^.^| 3 ^.^| 3, 1 ^.^| 3 ^.^| 3, 4
| | ^.^| 4 ^.^| 4, 1
|===
======

====
```

**Comment by opoudjis** [comment]
The syntax shall not pointlessly override what is already in place in mn-samples-iso, which works fine. So:

* this functionality is specific to ISO for now
* this functionality is triggered on clauses with a "change=modify" or "change=add" attribute
* clauses must have titles in Asciidoctor, but they can be overridden by a title attribute (if you must), and by the locality
* the proposal to encode the entire change as an example (!!!) is rejected
* we shall continue to use blockquote, not example, to indicate the replacement text
* because the functionality is triggered by the clause attribute "change", there is no need to signal on the blockquote that it is replacement text; the locality attribute can stand on its own
* indicating a locality of change in the replacement text, that is an XPath on top of the locality of the clause, is extraordinarily clunky, but it is forced by the constraint of human-readability.
* The Metanorma XML may end up distinct: I haven't decided yet

````
// the container
[change=modify,locality="page=14,clause=4.3.1,title=_array_based_unstructured_mesh_"]
==== {blank}

// Human-readable message
_Some attributes referenced in the EXPRESS are not properly defined, Remove the EXPRESS definition of this entity and replace with:_

// the actual location of change
[locality=./source]
____
[%unnumbered]
[source,html]
----
*)
ENTITY array_based_unstructured_mesh
...
(*
----
____

````

and

````
// the container
[locality="page=27,table=2"]
==== {blank}

_This table contains information on polygon cells which are not included in ISO 10303-52. Remove table 2 completely and replace with:_

____
.Edges of triangle and quadrilateral cells
|===
2+^.^h| triangle 2+^.^h| quadrilateral
^.^| edge ^.^| vertices ^.^| edge ^.^| vertices
^.^| 1 ^.^| 1, 2 ^.^| 1 ^.^| 1, 2
^.^| 2 ^.^| 2, 3 ^.^| 2 ^.^| 2, 3
^.^| 3 ^.^| 3, 1 ^.^| 3 ^.^| 3, 4
| | ^.^| 4 ^.^| 4, 1
|===
____


````

**Comment by ronaldtse** [comment]
Looks good to me.

**Comment by opoudjis** [comment]
Further modification:

* The location of a change within a numbered section is given as an XPath, as shown above with "./source"; but that is named as a distinct `path` attribute on the initial clause; attributes should not be given separately on the blockquote.
* In case the change spans multiple elements within the nominated location, path shall be taken as the starting element of the text to be replaced; the final element shall be given as `path_end`
* Excerpts to be changed will need numbering overrides for any numbered assets they contain. These will be given as `autonumber:type[number]`, e.g. `autonumber:table[2]`
* The title is not a locality, and should be given as a distinct attribute
* Machine readability really means that a clause reference must be included

So:

````
// the container
[change=modify,locality="page=14,clause=4.3.1",title=_array_based_unstructured_mesh_,path="./source"]
==== {blank}

// Human-readable message
_Some attributes referenced in the EXPRESS are not properly defined, Remove the EXPRESS definition of this entity and replace with:_

____
[%unnumbered]
[source,html]
----
*)
ENTITY array_based_unstructured_mesh
...
(*
----
____

````

and

````
// the container
[locality="page=27,table=2"]

or

[locality="page=27",path="//table[2]"]
==== {blank}

autonumber:table[2]

_This table contains information on polygon cells which are not included in ISO 10303-52. Remove table 2 completely and replace with:_

____
.Edges of triangle and quadrilateral cells
|===
2+^.^h| triangle 2+^.^h| quadrilateral
^.^| edge ^.^| vertices ^.^| edge ^.^| vertices
^.^| 1 ^.^| 1, 2 ^.^| 1 ^.^| 1, 2
^.^| 2 ^.^| 2, 3 ^.^| 2 ^.^| 2, 3
^.^| 3 ^.^| 3, 1 ^.^| 3 ^.^| 3, 4
| | ^.^| 4 ^.^| 4, 1
|===
____


````

**Comment by opoudjis** [comment]
Remaining work is to integrate this processing into ISO

**Comment by opoudjis** [comment]
And I see that this will force a PDF update. This work needs to be pulled into a feature branch.

**Comment by opoudjis** [comment]
We unfortunately need to accommodate descriptive text after the amendment. I will convert the amend block to normal text and blockquote for the replacement text in PresentationXML, to preempt PDF development.

**Comment by opoudjis** [comment]
Change `replacement` to `newcontent`

**Comment by opoudjis** [comment]
Inserted xpaths in the modifications in mn-sample-iso amendements.
