### ISSUE TITLE
Differentiated image formats for Word / PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#271]
Considering:

* Word doesn't accept SVG in MHT. In normal Word, it rasterizes it into PNG when dragged in / manually imported. Word only accepts .EMF as its vector format.

* PDF accepts SVG, but not .EMF.

For people who want to publish with vector graphics, they are forced to choose between SVG or EMF. And there does not seem to be a correct answer here (unless it's PNG).

The only decent software I found that converts between SVG and EMF is Inkscape, which is a large piece of software that I doubt whether we should include it. ImageMagick and other SVG software I've tried have poor results.

Here's the question. Do we allow differentiated image includes?

e.g.
```
if:output:word
image::xxx.emf
endif
if:output:pdf
image::xxx.svg
endif
```

Or we help them do this automatically?
```
image::xxx.emf
```
In Word it uses EMF, in PDF it converts to SVG.

And
```
image::xxx.svg
```
In PDF it uses SVG, in Word it converts to EMF.

**Comment by opoudjis** [comment]
Magic is fine so long as it predictable and manageable. If any of these have online APIs, and we cache the results, that's potentially tractable.

People are going to balk at the choice; it may well be that if they don't offer alternates, we just don't generate the PDF or the Word.

I'm not convinced you need to destroy the output like that at all though. You could specify an SVG file by default, and when Word sees it, before attempting to convert it, Word looks for an EMF file with the same name in the same location. (That means that SVG and EMF sidestep data-uri, which is a small price to pay.)

**Comment by ronaldtse** [comment]
> If any of these have online APIs, and we cache the results, that's potentially tractable.

https://cloudconvert.com offers 25 images a day, but the easiest is Inkscape (GPL2) which you can install for free (with the conversion in excellent quality).

> You could specify an SVG file by default, and when Word sees it, before attempting to convert it, Word looks for an EMF file with the same name in the same location. 

Sounds good to me.

> (That means that SVG and EMF sidestep data-uri, which is a small price to pay.)

What does this mean?

**Comment by opoudjis** [comment]
>> (That means that SVG and EMF sidestep data-uri, which is a small price to pay.)
> What does this mean?

If Word looks for an EMF file, that means you can't use Data URI, the Data URI means you're not leaving an EMF file lying around. But OK.

**Comment by ronaldtse** [comment]
Now the question is whether we can embed both image formats (for the same image) inside Metanorma XML. I think that would solve a number of issues...
