### ISSUE TITLE
Test updated AsciiMath conversion

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#272]
You may recall that we used to get a white square error with many AsciiMath expressions in Word, until we found the cause—Word requires mrow wrappers around the arguments of what it considers to be n-Ary operators, MathML munder mover munderover msup msub msupsub. We've had to kludge this in the past by putting the arguments in brackets.

The latest Github checkin of the AsciiMath, https://github.com/asciidoctor/asciimath/issues/14, should address this issue. I'd like to ask you to test it with any AsciiMath you're aware of that may break Word.

To test this:

* Specify the github AsciiMath in GitHub
* Specify the branch feature/asciimath from github for Html2Doc
* Wait for the github AsciiMath to be debugged (I'll let you know when to proceed)

The AsciiMath operators susceptible to such breakage are particularly things with three arguments, such as integers and sums. See e.g. https://github.com/metanorma/metanorma-nist/issues/154

**Comment by anermina** [comment]
I remember having lots of issues with white squares while converting ITU G.650. Therefore, I tested all the relevant equations from that document, some of the equations from NIST 800-90B and some random ones, which I created only for testing purposes. All the generated equations were as expected (without white squares). Attached is the file I created for testing, as well as DOC outputs for NIST and ITU flavors.

@manuel489 , please confirm there were no issues in your tests either, or let us know if you run into any error.

[test.zip](https://github.com/metanorma/metanorma-standoc/files/4593889/test.zip)

**Comment by manuel489** [comment]
Ok, I've got the same result as @anermina. Even this issue: https://github.com/metanorma/metanorma-standoc/issues/228, got solved 😃

**Comment by manuel489** [comment]
However, math expressions nested in `pseudocode` block get broken.

*Sample 1:*
````
[pseudocode]
====
[stem]
++++
bar X' = (1)/(v) sum_(i = 1)^(v) t_(i)
++++
====
````

*Output 1:*
![out1](https://user-images.githubusercontent.com/33627611/81360105-01113880-90a9-11ea-93f3-7b260a09b519.PNG)


*Sample 2:*
````
[pseudocode]
====
stem:["Rule" ::= f(t_1, ...,  t_n) := t_0 (n >= 0)]
====
````

*Output 2:*
![out2](https://user-images.githubusercontent.com/33627611/81360185-30c04080-90a9-11ea-9506-e6a919dc133f.PNG)

**Comment by opoudjis** [comment]
OK, @manuel489, could you please raise that as a new issue? It's an issue with "apostrophes" that I need to look out for anyway.

**Comment by manuel489** [comment]
> OK, @manuel489, could you please raise that as a new issue? It's an issue with "apostrophes" that I need to look out for anyway.

Ticket opened in https://github.com/metanorma/metanorma-standoc/issues/275

**Comment by opoudjis** [comment]
Ok, thank you both!
