### ISSUE TITLE
Apostrophes issue in math expressions

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#275]
Math expressions nested in `pseudocode` blocks get broken.

*Sample 1:*
````
[pseudocode]
====
[stem]
++++
bar X' = (1)/(v) sum_(i = 1)^(v) t_(i)
++++
====
````

*Output 1:*
![out1](https://user-images.githubusercontent.com/33627611/81360105-01113880-90a9-11ea-93f3-7b260a09b519.PNG)

*Sample 2:*
````
[pseudocode]
====
stem:["Rule" ::= f(t_1, ...,  t_n) := t_0 (n >= 0)]
====
````

*Output 2:*
![out2](https://user-images.githubusercontent.com/33627611/81360185-30c04080-90a9-11ea-9506-e6a919dc133f.PNG)

[equations.zip](https://github.com/metanorma/metanorma-standoc/files/4596654/equations.zip)

**Comment by opoudjis** [comment]
Need to make sure that no pretty printing is done to the apostrophes inside AsciiMath, if they are inside pseudocode.

**Comment by opoudjis** [comment]
> Math expressions nested in pseudocode blocks get broken.

Sample 1:

Can't tell you why, but this is an issue with Asciidoctor, not with Metanorma: the stem block in 

````
[pseudocode]
====
[stem]:
++++
bar X' = (1)/(v) sum_(i = 1)^(v) t_(i)
++++
====
````

simply is not being recognised as such, no matter if I insert blank lines around it or not. The only stem expression that is recognised within an example is an inline stem expression:

````
[pseudocode]
====
stem:[bar X' = (1)/(v) sum_(i = 1)^(v) t_(i)]
====
````

**Comment by opoudjis** [comment]
@manuel489 @anermina Don't use `[pseudocode]` but `[.pseudocode]`; the style attribute, `[pseudocode]`, is locked down by Asciidoctor, and tends not to work. With `[.pseudocode]`, both expressions render fine.

**Comment by opoudjis** [comment]
Issue was that pseudocode macro was adding ` +` to all lines in its content, including to Asciidoctor directives such as `[stem]` and delimiters such as `====`. Prevented in macro.

**Comment by opoudjis** [comment]
Have also turned off replacements substitutions in blocks within pseudocode, to prevent smart apostrophes (A's => A’s), and other substitutions inappropriate to pseudocode.
