### ISSUE TITLE
`mailto:` error in Standoc

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#279]
Here's my experiment with mailto:

```adoc
If there is difficulty accessing these sites contact ISO Central Secretariat or contact the ISO TC 184/SC4 Secretariat directly at:

* mailto:sc4sec@cme.nist.gov
* mailto:sc4sec@cme.nist.gov[NIST]
* sc4sec@cme.nist.gov
```

XML:
```xml
<p id="_cbdda666-e679-4eb3-a3c1-394f7c344430">
  If there is difficulty accessing these sites contact ISO Central Secretariat
  or contact the ISO TC 184/SC4 Secretariat directly at:
</p>
<ul id="_0f11d5e7-dada-4d15-b374-c57735942805">
  <li>
    <p id="_f748f8fd-4a21-45c4-8a7d-e1e7578db823">
      mailto:sc4sec@cme.nist.gov
    </p>
  </li>
  <li>
    <p id="_3851ed0c-50c2-4a56-949c-76dc0834f8c3">
      <link target="mailto:sc4sec@cme.nist.gov">
        NIST
      </link>
    </p>
  </li>
  <li>
    <p id="_898063b2-41bc-4c91-9517-f846ffe4361e">
      <link target="mailto:sc4sec@cme.nist.gov"/>
    </p>
  </li>
</ul>
```

It gets rendered like this (HTML):
<img width="820" alt="image" src="https://user-images.githubusercontent.com/11865/81637751-bfd2ad00-9449-11ea-9e3a-f2129e7b949c.png">

* The first one is a Standoc error. <== ping @opoudjis (should have been a real link)
* The second one is correct.
* The third one is a mn2pdf error (reported in https://github.com/metanorma/mn-native-pdf/issues/186).

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-native-pdf/issues/186#issuecomment-627093790_

**Comment by opoudjis** [comment]
> The first one is a Standoc error. <== ping @opoudjis (should have been a real link)

The first one is an *Asciidoctor* issue. `mailto:` is a macro, which requires brackets to be recognised as such. Emails and http:// URLs are autorecognised by regex; emails prefixed by mailto: are not.

This is not a standoc specific error, and tinkering with the backend macro recognition of Asciidoc is a dangerous activity that does not justify the beyond-marginal benefit here.
