### ISSUE TITLE
Permit language metadata for clauses

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#28]
Requirement arising from https://github.com/riboseinc/metanorma-model-unece/issues/5

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! How are we able to access this functionality?

**Comment by opoudjis** [comment]
````
[language=en,script=Latn]
````

as style attributes on any clause. Illustrated in spec/asciidoctor/section_test.rb of metanorma-standoc.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , is this documented on metanorma.com? If not can you help do so?

**Comment by opoudjis** [comment]
It is documented, pending pull request https://github.com/metanorma/metanorma.com/pull/102
