### ISSUE TITLE
Override autonumbering

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#287]
There are circumstances when autonumbering of assets needs to be overriden; e.g. numbering out of sequence in updated documents, as in https://portal.ogc.org/public_ogc/directives/directives.php Directive 43:

> For a revision to a standard, all unchanged requirements retain the same number. Deleted requirements have numbers which are deleted and not to be reused. New requirements take the next available number at the end of the sequence, even if inserted between existing, consecutive requirements.

To address such use cases, all assets will have an optional "number" attribute, giving a required asset number to override autonumbering. Any assets subsequent to that asset will be autonumbered so as to follow the previous asset. For subsequences, number shall have only subsequence scope.

**Comment by ronaldtse** [comment]
@opoudjis we are in discussion with OGC on this.

**Comment by ronaldtse** [comment]
Locality stack as method of overriding auto numbering initial number?

**Comment by opoudjis** [comment]
... No, the locality stack has nothing to do with asset captions, I don't see how that will help at all. It is not cross-references to assets that need the autonumbering disrupted, it's the cross-reference targets.
