### ISSUE TITLE
PlantUML failing in Ubuntu Ruby 2.6

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#288]
And only Ruby 2.6

https://github.com/metanorma/metanorma-standoc/runs/749270713?check_suite_focus=true

**Comment by CAMOBAP** [comment]
After rerun tests are passed, but the problem still exists, another case are here:
https://github.com/metanorma/metanorma-standoc/runs/748922437?check_suite_focus=true

It's hard to tell exact reproduction rate, Investigation in progress

**Comment by CAMOBAP** [comment]
After ~100 attempts in a row wasn't managed to reproduce it, trying with docker

**Comment by CAMOBAP** [comment]
The problem related to the `curl: (7) Failed to connect to sourceforge.net port 443: Connection timed out` issue

**Comment by CAMOBAP** [comment]
- [ ] https://github.com/metanorma/plantuml-install/pull/2 need review
 - [x] add retry logic https://github.com/metanorma/metanorma-build-scripts/commit/c3b0cc7845b46c0f4775063726a06124907d61e1

**Comment by ronaldtse** [comment]
@CAMOBAP I've merged the above, can close?

**Comment by CAMOBAP** [comment]
Yep
