### ISSUE TITLE
Some reference localities render wrongly

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#290]
Consider the following examples taken from the [official documentation -- Localities](https://www.metanorma.com/author/topics/document-format/bibliography/#localities):

````
// renders as: "the foregoing reference"
<<ISO712,the foregoing reference>>

// renders as: "ISO 712, Section 5, Page 8-10"
<<ISO712,section=5, page 8-10>>

// renders as "ISO 712, 5:8-10"
// ("5:8-10" treated as replacement text for all the foregoing)
<<ISO712,section=5, page=8-10: 5:8-10>>

// renders as: "ISO 712, Whole of text"
<<ISO712,whole>>
````

Which results in 
![Capture](https://user-images.githubusercontent.com/33627611/84210277-477dfc80-aa86-11ea-9337-3010369cd599.PNG)

According to the comments in the code, the first two configurations are correct. But apparently, the other two are not.

Thanks!

**Comment by opoudjis** [comment]
@manuel489 the third one is also correct, surely:

`<<ISO712,section=5, page=8-10: 5:8-10>>`

Means (a) the locality is defined by `section=5, page=8-10`, and (b) the display text is `5:8-10`. The display text you're showing is `5:8-10`. That's right.

**Comment by opoudjis** [comment]
"Whole of text" was being missed because of typo.
