### ISSUE TITLE
Numbered references not rendering properly in subsections

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#295]
*This issue is related to https://github.com/metanorma/mn-samples-nist/issues/43*

In bibliography subsections, numbered references don't render as expected if the first title is other than `Bibliography`

For example,
````
[appendix]
== References
[bibliography]
=== Part 1

* [[[ref1,1]]], E-Government Act [includes FISMA] (P.L. 107-347), December 2002.
* [[[ref2,1]]], Federal Information Security Management Act (P.L. 107-347, Title III), December 2002.
* [[[ref3,1]]], Paperwork Reduction Act (P.L. 104-13), May 1995.

[bibliography]
=== Part 2

* [[[ref11,1]]], Presidential Memorandum, National Insider Threat Policy and Minimum Standards for Executive Branch Insider Threat Programs, November 2012.
* [[[ref12,1]]], Code of Federal Regulations, Title 5, _Administrative Personnel_, Section 731.106, _Designation of Public Trust Positions and Investigative Requirements_ (5 C.F.R. 731.106).
* [[[ref13,1]]], Code of Federal Regulations, Part 5 Administrative Personnel, Subpart C—Employees Responsible for the Management or Use of Federal Computer Systems, Section 930.301 through 930.305 (5 C.F.R. 930.301-305).
````

Renders as

![biblio-nist1](https://user-images.githubusercontent.com/33627611/85868937-fa459e80-b798-11ea-8aa3-835efa39f12f.PNG)

But if we put `Bibliography` as title instead of `References`, we get the proper result:

![biblio-nist2](https://user-images.githubusercontent.com/33627611/85869295-7cce5e00-b799-11ea-9ce3-904f3a24075a.PNG)

Sample file: 
[test.zip](https://github.com/metanorma/metanorma-standoc/files/4837541/test.zip)

**Comment by opoudjis** [comment]
Excessively restrictive condition on which references to renumber: allow annex/references as well as clause/references (and in this instance annex/clause/references).

**Comment by manuel489** [comment]
> Excessively restrictive condition on which references to renumber: allow annex/references as well as clause/references (and in this instance annex/clause/references).

@opoudjis, I have confirmed that the numbering works for "annex/references" but it stopped working for "annex/bibliography"
