### ISSUE TITLE
Numbered references not rendering properly in auto-fetch

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#296]
*This issue is related to https://github.com/metanorma/mn-samples-nist/issues/43*

Numeric references are not getting numbered (properly) in auto-fetch configuration.

For example,
````
[appendix]
[bibliography]
== References

* [[[ref1,1]]], E-Government Act [includes FISMA] (P.L. 107-347), December 2002.
* [[[ref2,1]]], Federal Information Security Management Act (P.L. 107-347, Title III), December 2002.
* [[[ref54,(1)ISO/IEC 27001:2005]]], International Organization for Standardization/International Electrotechnical Commission 27001:2005, _Security techniques --_ _Information security management systems -- Requirements_.
````

Renders as:

*NIST output:*
![biblio-nist](https://user-images.githubusercontent.com/33627611/85871923-151a1200-b79d-11ea-8785-383dd5f3eebd.PNG)

*ISO output:*
![biblio-iso](https://user-images.githubusercontent.com/33627611/85871654-b8b6f280-b79c-11ea-9099-776d2ae50407.PNG)

Sample file:
[ref_test.zip](https://github.com/metanorma/metanorma-standoc/files/4837671/ref_test.zip)

**Comment by opoudjis** [comment]
ISO: the ordinal used in bibliographies invalidates use of numeric metanorma identifiers; remove specious distinction between standard and non-standard rendering in Bibliographies. Addresses ISO.

**Comment by opoudjis** [comment]
Add same metanorma identifier processing code to standards and non-standards for NIST.
