### ISSUE TITLE
Inline latexmath renders as block math expression

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#300]
`latexmath:[{expression}]` renders as block math instead of inline math.

For example,
````
where stem:[(x,y,z)] are the cartesian coordinates, stem:[(u,v,w)] are the cartesian components of velocity, stem:[rho] is static 
density, stem:[p] is static pressure, stem:[c] is the static speed of sound, and stem:[mu] is the molecular viscosity. In this 
example, tilde quantities latexmath:[(\:\tilde{}\:)] are nondimensional and all others are dimensional...
````

renders as

*Metanorma:*
![capture-metanorma](https://user-images.githubusercontent.com/33627611/86435331-bccb9e80-bccd-11ea-9d79-2b0c774932eb.PNG)

*Asciidoctor:*
![capture-asciidoc](https://user-images.githubusercontent.com/33627611/86435343-c1905280-bccd-11ea-8d59-427a064ebc3b.PNG)

**Comment by ronaldtse** [comment]
Thanks @manuel489 for reporting!

**Comment by opoudjis** [comment]
`latexmlmath` is injecting `display = "block"` into all the MathML it generates. Will override.
