### ISSUE TITLE
Do not allow using invalid XML anchors

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#305]
Anchors, references and bib refs: they cannot contain colons -- because they are written to XML. XML does not support colon, spaces, and phrases that start with numbers in `id`.

Metanorma should display errors when such anchors are used.

From: https://github.com/metanorma/iso-10303/pull/71

**Comment by opoudjis** [comment]
But we have lost the IDREF validation for xrefs that point to a destination within the document, without an #. We will restore that functionality as a coded validation step.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !

**Comment by opoudjis** [comment]
I'm also not going to raise error on fatal validation issues, because I want validation to log all issues with the file, not just the first.
