### ISSUE TITLE
CSA: Differences between Metanorma "presentational XML" and "sources PDF/DOC" forms

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#306]
- CSA
Source PDF form (https://github.com/metanorma/mn-native-pdf/issues/46, https://github.com/metanorma/mn-native-pdf/files/3977293/Information.Security.Management.through.Reflexive.Security.pdf, https://github.com/metanorma/mn-native-pdf/files/3977294/Six.Pillars.of.DevsecOps-Branded.pdf) doesn't have a section number:
![изображение](https://user-images.githubusercontent.com/5559926/88167095-f7678d80-cc20-11ea-841b-ef4c49e43f50.png)

but presentation XML has:
```xml
<clause id="_scope" type="scope" obligation="normative"><title depth="1">1.<tab/>Scope</title>
```

therefore sections in resulted PDF displays now with numbers:
![изображение](https://user-images.githubusercontent.com/5559926/88167293-49101800-cc21-11ea-8d67-57339dec0706.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 thanks for raising this. The numbers are intended here, so it's fine 👍  Maybe some spacing between the number and section title is needed.

**Comment by opoudjis** [comment]
OK. This issue is going to include all the discrepancies between pres_xml and master output that @Intelligent2013 identifies, so this first issue is not a concern, but others are.

Once this issue is resolved, the pres_xml branch (to date) will me merged into master. I anticipate that will be the release after next, which will be a major version. The next release will be Friday, and will include the sassc refactor and metanorma collection code; Alex will likely be done by then, but I don't want to rush the code merger, or guarantee I will have debugged everything.

**Comment by Intelligent2013** [comment]
> Maybe some spacing between the number and section title is needed.

Fixed:

![изображение](https://user-images.githubusercontent.com/5559926/88201929-c901a680-cc50-11ea-8385-427c4b68d16f.png)

**Comment by Intelligent2013** [comment]
- GB
Presentation XML contains char hex 3000 between section number and section title instead of `<tab/>`:

rice.gb.en.presentation.xml:
```xml
<clause id="_范围" type="scope" obligation="normative"><title depth="1">1　Scope</title>
```

![изображение](https://user-images.githubusercontent.com/5559926/88202120-13832300-cc51-11ea-97a6-fdd5ee9ff094.png)

It shows ok in resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/88200896-72479d00-cc4f-11ea-9170-986f1e5afd03.png)

but if we need to manage distance between section number and title, we need to replace to`<tab/>`. Sure I can process 0x3000 programmatically in xslt, but it would be better to use common approach as for another forms.

**Comment by Intelligent2013** [comment]
- IEC
  - Regarding IEC styling (Foreword) (https://github.com/metanorma/mn-native-pdf/issues/111) table in preface section doesn't have a title:
![изображение](https://user-images.githubusercontent.com/5559926/88208433-dff8c680-cc59-11ea-870b-ba0b9b9730c5.png)

but presentation XML (iec-rice.presentation.xml) contains 'Table 1':
```xml
<table id="_3c13360f-7da4-4c47-a9ec-ddae1fbadf16"><name>Table 1</name>
<thead>
<tr>
<th align="left">FDIS</th>
<th align="left">Report on voting</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">XX/XX/FDIS</td>
<td align="left">XX/XX/RVD</td>
</tr>
</tbody>
</table>
```

and in resulted PDF it shows as:
![изображение](https://user-images.githubusercontent.com/5559926/88208610-2a7a4300-cc5a-11ea-92cb-11c800d8578c.png)


-   - Regarding IEC styling (Annex numbering) (https://github.com/metanorma/mn-native-pdf/issues/116), between 'Annex X' and (normative) should not be a space:
![изображение](https://user-images.githubusercontent.com/5559926/88211728-c9a13980-cc5e-11ea-885b-e53d75d5f8d7.png)

but in presentation XML there is an excess `<br/>` after 'Annex A':
```xml
<annex id="AnnexA" inline-header="false" obligation="normative"><title><strong>Annex A</strong><br/><br/>(normative)<br/><br/><strong>Determination of defects</strong></title>
```

and it shows in resulted PDF as:
![изображение](https://user-images.githubusercontent.com/5559926/88211915-108f2f00-cc5f-11ea-8b01-0bb4a0df2501.png)

-  - In source PDF a reference to equation titles as Equation:
![изображение](https://user-images.githubusercontent.com/5559926/88212813-8647ca80-cc60-11ea-856f-a0f1114611b4.png)

but in presentation XML it titled as 'Formula':
```xml
<xref target="formulaA-1">Formula (A.1)</xref>
```
and in resulted PDF it shows as:
![изображение](https://user-images.githubusercontent.com/5559926/88213103-f5252380-cc60-11ea-8a44-b77e2b341cfe.png)

**Comment by opoudjis** [comment]
GB: 

> but if we need to manage distance between section number and title, we need to replace to<tab/>. Sure I can process 0x3000 programmatically in xslt, but it would be better to use common approach as for another forms.

You are right, and that's an oversight.

This raises the issue of how to deal with tab programmatically, and I think we should both make changes. So:

* U+3000 is the Chinese script equivalent of nonbreaking space and tab.
* That means that if the document is in Chinese, tab should be mapped to U+3000, regardless of flavour. (Note: that is a change I have to make as well in rendering.)
* The character U+3000 should be avoided in XML in favour of U+3000; that was an oversight (although I think I know why it happened—U+3000 replaces &nbsp; as well, and I will check the instances where it still occurs.)
* In GB specifically, U+3000 is mandated in their rendering spec. That means that we map tab to U+3000 in GB for Latin script texts as well as Chinese language texts.

I will update pres_xml branch and the rendering of ISO and GB samples, and provide them to you.

**Comment by opoudjis** [comment]
I'm going to insert numbers in your comments, to uniquely identify each issue.

**Comment by Intelligent2013** [comment]
- IHO
-  - **IHO 1**: Tables with attribute `unnumbered="true"` has `<name>Table </name>`:
Example s5a.presentation.xml:
```xml
<table id="_3f38773b-45f0-44a9-85c6-bb6e215ab35a" unnumbered="true"><name>Table </name>
```
-  - **IHO 2**: when I processed non-presentation xml to produce PDF, I've put title:
      - 'Annex' for `annex` with attribute `obligation="normative"` and 
      - 'Appendix' for `annex` with attribute `obligation="informative"` 
and it showed as (example for s102.xml):
![изображение](https://user-images.githubusercontent.com/5559926/88273745-4f66c880-cce3-11ea-8327-2ef1c2c5f2f1.png)

but in presentation xml all `annex` have title 'Annex ...' and resulted PDF now is:
![изображение](https://user-images.githubusercontent.com/5559926/88273976-ab315180-cce3-11ea-893a-866a92c53baf.png)

And please note that in the s63.presentation.xml there is a text relates to Appendixes:
```xml
<p id="_34b2cce6-582d-44bd-907a-9da04684bcd8">Appendix 1: Contains a definition of available test data which can be used to develop full compliance with all aspects of the Data Protection Scheme.</p>
</li>
<li>
<p id="_e2d7526c-3db0-47d4-84d9-909a14a7019d">Appendix 2: Defines how encrypted ENC exchange sets provided by Data Servers will be stored using mass storage devices such as DVD or USB memory sticks.</p>
</li>
```
but concordance `annex` have 'Annex ...' titles.

**Comment by Intelligent2013** [comment]
- ISO: nested figures titles have 'dash':
Example: rice-en.final.presentation.xml 
```xml
<figure id="figureC-2"><name>Figure C.2 — Stages of gelatinization</name><figure id="_572adcc6-b543-4112-80db-5491c5c2baf5">
<name>a) — Initial stages: No grains are fully gelatinized (ungelatinized starch granules are visible inside the kernels)</name>
```
Resulted PDF for presentation XML:
![изображение](https://user-images.githubusercontent.com/5559926/88282120-9b206e80-ccf1-11ea-9f3b-fab0ffa94cf9.png)

Resulted PDF for non-presentation XML:
![изображение](https://user-images.githubusercontent.com/5559926/88282198-bb502d80-ccf1-11ea-88e6-e3a271aeffbc.png)

I don't sure that it's a bug, but just I've noticed a difference.

**Comment by Intelligent2013** [comment]
- ITU:
  - **ITU 1**: Tables with attribute `unnumbered="true"` has a name 'Table ':
  ```xml
  <table id="_7cb6a451-ff32-4ac4-ab3d-a98242ca29d4" unnumbered="true"><name>Table </name>
  ```
  - **ITU 2**: Single `termnote`'s (i.e. single in the current section) doesn't have a `name`, but multiple `termnote`'s have a number only :
  Example G.650.1-201803.presentation.xml:
  ```xml
  <termnote id="_188489e5-da7c-4459-a67f-f234dba9e9eb">
  <p id="_9d13fa54-3e23-42fb-a699-2ae40fe2e7d8"><em>n</em> need not be an integer.</p>
  </termnote>
  ...
  <termnote id="_82f34efc-62d7-4ec6-9806-536536630a96"><name> 1</name>
  <p id="_abbf6f90-50b3-4ea7-8e9e-b3404f2f887e">The above constant level shall be chosen between 5% and 50% of maximum near-field intensity.</p>
  </termnote><termnote id="note_core_centre"><name> 2</name>
  <p id="_7173e3a2-4c33-4ed3-9d34-ea25fdb8701d">Usually, the core centre represents a good approximation of the mode field centre.</p>
  ```
  - **ITU 3**: a.presentation.xml - sections 'Scope', 'References', 'Definitions', 'Abbreviations and acronyms' don't have section number in a `title`. Section numbers start from '5' (Conventions).

**Comment by ronaldtse** [comment]
@Intelligent2013 it might be better to open a new issue per flavor for tracking 😉

**Comment by Intelligent2013** [comment]
> @Intelligent2013 it might be better to open a new issue per flavor for tracking wink

@ronaldtse Done. Close this ticket.
