### ISSUE TITLE
ITU: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#307]
- **1**: Tables with attribute `unnumbered="true"` has a name 'Table ':
  ```xml
  <table id="_7cb6a451-ff32-4ac4-ab3d-a98242ca29d4" unnumbered="true"><name>Table </name>
  ```
- **2**: Single `termnote`'s (i.e. single in the current section) doesn't have a `name`, but multiple `termnote`'s have a number only :
  Example G.650.1-201803.presentation.xml:
  ```xml
  <termnote id="_188489e5-da7c-4459-a67f-f234dba9e9eb">
  <p id="_9d13fa54-3e23-42fb-a699-2ae40fe2e7d8"><em>n</em> need not be an integer.</p>
  </termnote>
  ...
  <termnote id="_82f34efc-62d7-4ec6-9806-536536630a96"><name> 1</name>
  <p id="_abbf6f90-50b3-4ea7-8e9e-b3404f2f887e">The above constant level shall be chosen between 5% and 50% of maximum near-field intensity.</p>
  </termnote><termnote id="note_core_centre"><name> 2</name>
  <p id="_7173e3a2-4c33-4ed3-9d34-ea25fdb8701d">Usually, the core centre represents a good approximation of the mode field centre.</p>
  ```
- **3**: a.presentation.xml - sections 'Scope', 'References', 'Definitions', 'Abbreviations and acronyms' don't have section number in a `title`. Section numbers start from '5' (Conventions).

**Comment by opoudjis** [comment]
"1": fixed in https://github.com/metanorma/metanorma-standoc/issues/314

**Comment by opoudjis** [comment]
"2": termnotes were not being labelled, I was using an incorrect code shortcut.
