### ISSUE TITLE
ISO: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#308]
Nested figures titles have 'dash':
Example: rice-en.final.presentation.xml 
```xml
<figure id="figureC-2"><name>Figure C.2 — Stages of gelatinization</name><figure id="_572adcc6-b543-4112-80db-5491c5c2baf5">
<name>a) — Initial stages: No grains are fully gelatinized (ungelatinized starch granules are visible inside the kernels)</name>
```
Resulted PDF for presentation XML:
![изображение](https://user-images.githubusercontent.com/5559926/88282120-9b206e80-ccf1-11ea-9f3b-fab0ffa94cf9.png)

Resulted PDF for non-presentation XML:
![изображение](https://user-images.githubusercontent.com/5559926/88282198-bb502d80-ccf1-11ea-88e6-e3a271aeffbc.png)

I don't sure that it's a bug, but just I've noticed a difference.

**Comment by opoudjis** [comment]
No, the dash shouldn't be there
