### ISSUE TITLE
IHO: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#309]
- **1**: Tables with attribute `unnumbered="true"` has `<name>Table </name>`:
Example s5a.presentation.xml:
```xml
<table id="_3f38773b-45f0-44a9-85c6-bb6e215ab35a" unnumbered="true"><name>Table </name>
```
-  **2**: when I processed non-presentation xml to produce PDF, I've put a titles:
      - 'Annex' for `annex` with attribute `obligation="normative"` and 
      - 'Appendix' for `annex` with attribute `obligation="informative"` 
and it showed as (example for s102.xml):
![изображение](https://user-images.githubusercontent.com/5559926/88273745-4f66c880-cce3-11ea-8327-2ef1c2c5f2f1.png)

but in presentation xml all `annex` have title 'Annex ...' and resulted PDF now is:
![изображение](https://user-images.githubusercontent.com/5559926/88273976-ab315180-cce3-11ea-893a-866a92c53baf.png)

And please note that in the s63.presentation.xml there is a text relates to Appendixes:
```xml
<p id="_34b2cce6-582d-44bd-907a-9da04684bcd8">Appendix 1: Contains a definition of available test data which can be used to develop full compliance with all aspects of the Data Protection Scheme.</p>
</li>
<li>
<p id="_e2d7526c-3db0-47d4-84d9-909a14a7019d">Appendix 2: Defines how encrypted ENC exchange sets provided by Data Servers will be stored using mass storage devices such as DVD or USB memory sticks.</p>
</li>
```
but concordance `annex`s have 'Annex ...' titles.

**Comment by opoudjis** [comment]
"1": Fixed in https://github.com/metanorma/metanorma-standoc/issues/314

**Comment by opoudjis** [comment]
"2": I cannot replicate this:

s102.presentation.xml

````
<annex id="annex-normative-implementation-guidance" obligation="normative">
<title><strong>Annex C</strong><br/><strong>Normative Implementation Guidance</strong></title>
<note id="_0064dd68-e00d-44c6-ae83-59a51b87e941"><name>NOTE</name>
<p id="_5b3dee8a-2815-4eb2-80ac-b4e8c3362027">Normative Implementation Guidance to be addressed in a future version of S-102.</p>
</note>
</annex><annex id="annex-feature-catalogue" obligation="informative">
<title><strong>Appendix 1</strong><br/><strong>Feature Catalogue</strong></title>
<p id="_1f10f26d-eb63-4633-a45e-e3c320016390">S-102 Feature Catalogue information is contained within a separate document: S-102FC_Ed2.0.0.docx.</p>
</annex>
````

Am sending you latest.

**Comment by opoudjis** [comment]
Whatever the issue had been, it's now fixed.
