### ISSUE TITLE
IEC: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#310]
- **1**: Regarding IEC styling (Foreword) (https://github.com/metanorma/mn-native-pdf/issues/111) table in preface section doesn't have a title:
![изображение](https://user-images.githubusercontent.com/5559926/88208433-dff8c680-cc59-11ea-870b-ba0b9b9730c5.png)

but presentation XML (iec-rice.presentation.xml) contains 'Table 1':
```xml
<table id="_3c13360f-7da4-4c47-a9ec-ddae1fbadf16"><name>Table 1</name>
<thead>
<tr>
<th align="left">FDIS</th>
<th align="left">Report on voting</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">XX/XX/FDIS</td>
<td align="left">XX/XX/RVD</td>
</tr>
</tbody>
</table>
```

and in resulted PDF it shows as:
![изображение](https://user-images.githubusercontent.com/5559926/88208610-2a7a4300-cc5a-11ea-92cb-11c800d8578c.png)

- **2**: Regarding IEC styling (Annex numbering) (https://github.com/metanorma/mn-native-pdf/issues/116), between 'Annex X' and (normative) should not be a space:
![изображение](https://user-images.githubusercontent.com/5559926/88211728-c9a13980-cc5e-11ea-885b-e53d75d5f8d7.png)

but in presentation XML there is an excess `<br/>` after 'Annex A':
```xml
<annex id="AnnexA" inline-header="false" obligation="normative"><title><strong>Annex A</strong><br/><br/>(normative)<br/><br/><strong>Determination of defects</strong></title>
```

and it shows in resulted PDF as:
![изображение](https://user-images.githubusercontent.com/5559926/88211915-108f2f00-cc5f-11ea-8b01-0bb4a0df2501.png)

- **3**: In source PDF a reference to equation titles as Equation:
![изображение](https://user-images.githubusercontent.com/5559926/88212813-8647ca80-cc60-11ea-856f-a0f1114611b4.png)

but in presentation XML it titled as 'Formula':
```xml
<xref target="formulaA-1">Formula (A.1)</xref>
```
and in resulted PDF it shows as:
![изображение](https://user-images.githubusercontent.com/5559926/88213103-f5252380-cc60-11ea-8a44-b77e2b341cfe.png)

**Comment by opoudjis** [comment]
"1". There is no inherent reason to skip table numbering in the foreword; I am inserting "unnumbered" attribute in the source Asciidoc.

**Comment by opoudjis** [comment]
"2". Overriden default, removed one linebreak.

**Comment by opoudjis** [comment]
"3". Had never implemented this, but luckily have implemented it elsewhere: introducing into YAML.
