### ISSUE TITLE
GB: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#311]
Presentation XML contains char hex 3000 between section number and section title instead of `<tab/>`:

rice.gb.en.presentation.xml:
```xml
<clause id="_范围" type="scope" obligation="normative"><title depth="1">1　Scope</title>
```

![изображение](https://user-images.githubusercontent.com/5559926/88202120-13832300-cc51-11ea-97a6-fdd5ee9ff094.png)

It shows ok in resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/88200896-72479d00-cc4f-11ea-9170-986f1e5afd03.png)

but if we need to manage distance between section number and title, we need to replace to`<tab/>`. Sure I can process 0x3000 programmatically in xslt, but it would be better to use common approach as for another forms.

**Comment by Intelligent2013** [comment]
From @opoudjis:

> but if we need to manage distance between section number and title, we need to replace to<tab/>. Sure I can process 0x3000 programmatically in xslt, but it would be better to use common approach as for another forms.

You are right, and that's an oversight.

This raises the issue of how to deal with tab programmatically, and I think we should both make changes. So:

* U+3000 is the Chinese script equivalent of nonbreaking space and tab.
* That means that if the document is in Chinese, tab should be mapped to U+3000, regardless of flavour. (Note: that is a change I have to make as well in rendering.)
* The character U+3000 should be avoided in XML in favour of U+3000; that was an oversight (although I think I know why it happened—U+3000 replaces &nbsp; as well, and I will check the instances where it still occurs.)
* In GB specifically, U+3000 is mandated in their rendering spec. That means that we map tab to U+3000 in GB for Latin script texts as well as Chinese language texts.

I will update pres_xml branch and the rendering of ISO and GB samples, and provide them to you.

**Comment by opoudjis** [comment]
@Intelligent2013 Am I leaving this ticket open for you? I am going to use `<tab/>` consistently for the Chinese U+3000 character.

**Comment by Intelligent2013** [comment]
Thanks.
