### ISSUE TITLE
NIST.SP: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#312]
- **1.** Tables marked `unnumbered="true"` has a name `<name>Table </name>`.
Example NIST.SP.800-116r1.presentation.xml:
```xml
<table id="_e2449a60-0030-4e06-844c-627e69899ee9" unnumbered="true"><name>Table </name>
<thead>
<tr>
<th align="left">Version</th>
<th align="left">Release Date</th>
<th align="left">Updates</th>
</tr>
```

- **2.** References section in `Appendix F` has a title `<title>F.</title>`.
Example NIST.SP.800-116r1.presentation.xml:
```xml
<annex id="_26295b25-7d2b-4123-831b-5d52a7e905c3" obligation="normative">
	<title><strong>Appendix F</strong> — <strong>References</strong></title>
	<references id="_bibliography" normative="true" obligation="informative"><title>F.</title> <bibitem id="FIPS199" type="standard">...
```
Looks like the references's title is superfluous here.

**Comment by Intelligent2013** [comment]
- **3.** in PDF we use special page numbers prefix for appendixes:
In Table of Contents:
![изображение](https://user-images.githubusercontent.com/5559926/88418185-d3a47300-cdeb-11ea-8628-4ff0399a1fbd.png)
and in footers:
![изображение](https://user-images.githubusercontent.com/5559926/88418137-c38c9380-cdeb-11ea-887f-7a3a1ca1ea3d.png)

Is there a possibility to include 'Appendix' title and number/letter into a separate element or attribute? When I calculated it via XSLT it was a simple to use one algorithm to put appendix number anywhere, but in presentation XML I have to calculated it again via xslt (it's a potential source of issues due possible different algorithms in presentation XML generation and XSLT) or extract from element `title`, but it's language specific problem.

**Comment by opoudjis** [comment]
"1": Fixed in https://github.com/metanorma/metanorma-standoc/issues/314

**Comment by opoudjis** [comment]
"2": Single reference sections in references have their titles skipped for rendering; they need to also be skipped for auto-numbering.

**Comment by opoudjis** [comment]
"3". Are you going to want this everywhere, or just NIST? Because I have inserted the crossreference text everywhere, I'm not clear as to why you need it, but yes, I can inject it in a separate "xref" attribute of the title (since that is what is used in crossreferences).

**Comment by opoudjis** [comment]
It's for footer generation.
