### ISSUE TITLE
OGC: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#313]
- **1.** Tables with attribute `unnumbered="true"` has a name 'Table ':
Example 15-120r5.presentation.xml:
```xml
<table id="_13b7fdd9-e835-47c8-afd7-c60c61d07922" unnumbered="true"><name>Table </name>
<thead>
<tr>
<th align="left">Date</th>
<th align="left">Release</th>
<th align="left">Author</th>
<th align="left">Paragragh</th>
<th align="left">Description</th>
```
- **2.** In some documents (for example 17-069.presentation.xml) the `preface/abstract/title` doesn't contain 'Abstract' string:
```xml
<preface>
		<abstract id="_abstract">
			<title>i.</title>
```
**3**. ... And preface sections have non-sequental numbering:
```xml
<preface>
		<abstract id="_abstract">
			<title>i.</title>
...
<clause id="_c2c7068e-ef7f-4993-afda-73eb893abfa2"
      			type="keyword">
			<title depth="1">v.<tab/>Keywords</title>
...
<foreword id="_df47a85d-7daf-4012-990a-1709f5b1a261"
        			obligation="informative">
			<title depth="1">ii.<tab/>Preface</title>
...
<clause id="_06c9b750-c626-4e19-8046-f0a78f3c54c0"
      			type="submitting_orgs">
			<title depth="1">iii.<tab/>Submitting Organizations</title>

...
<submitters id="_submitters">
			<title depth="1">iv.<tab/>Submitters</title>
```

I.e. :
```
i. 
v. Keywords
ii. Preface
iii. Submitting Organizations
iv. Submitters
```

- **4.** In the xml 17-069.presentation.xml  there is non-correct `name` `[_4a3bc8ad-e1fc-4b36-a0dd-682d342854aa]`:
```xml
<termnote id="_4a3bc8ad-e1fc-4b36-a0dd-682d342854aa"><name>[_4a3bc8ad-e1fc-4b36-a0dd-682d342854aa]</name>
<p id="_28b4a949-d18f-4b66-84c3-a1181d456788">Add link to the informative WFS Guide, once it is available.</p>
</termnote>
```

**Comment by opoudjis** [comment]
"1": Fixed in https://github.com/metanorma/metanorma-standoc/issues/314

**Comment by opoudjis** [comment]
"2". Has gone away, presumably because of the updates to asciidoc branch of code since I generated these.

**Comment by opoudjis** [comment]
"3". The keywords are not being injected in the right place: bug, had mistyped "keywords" as "keyword".

**Comment by opoudjis** [comment]
"4". Points to an underlying bug: a term in a terms section but not under a term is NOT a termnote, but a normal note. Fixing in metanorma-standoc
