### ISSUE TITLE
UN: differences between Metanorma "presentational XML" and "sources PDF/DOC" form

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#314]
- **1.** Tables with attribute `unnumbered="true"` have name 'Table ':
Example ECE_TRADE_C_CEFACT_2019_09.presentation.xml:
```xml
<table id="_c6d8640b-7158-421b-8f44-358cb639ad31" unnumbered="true"><name>Table </name>
<thead>
<tr>
<th align="left">Sector</th>
<th align="left">Only enter if more detail is needed than what is given in the chapter title</th>
```

- **2.** In the xml ECE_TRADE_C_CEFACT_2018_6E.presentation.xml there are `clause/title` with id in brackets instead of normal text. For example `<title>[_e54f3003-7ad4-4c42-b3e3-a1203a3808f9].</title>`:
```xml
<clause id="_benefits_for_traders" inline-header="false" obligation="normative" unnumbered="true">
<title depth="1">Benefits for Traders</title>
<clause id="_e54f3003-7ad4-4c42-b3e3-a1203a3808f9" inline-header="true" obligation="normative">
<title>[_e54f3003-7ad4-4c42-b3e3-a1203a3808f9].</title>...
```

**Comment by opoudjis** [comment]
"1". Do not add caption to tables if unnumbered and no caption already in place.

**Comment by opoudjis** [comment]
"2". The paragraphs are  not being numbered when they are converted into clauses; the fact that the depth of nesting changes is presumably at fault.

**Comment by Intelligent2013** [comment]
> 
> 
> "1". Do not add caption to tables if unnumbered and no caption already in place.

Sorry for misunderstanding, but what does mean 'no caption already in place'?
In presentation XSLT I display table caption from XML element `table/name`. I can process an attribute `unnumbered` in xslt and don't display table caption at all when `unnumbered="true"`. But should I also process text content of `table/name` additionally in case of `unnumbered="true"`?

For clarification of my question, in some xml (example - s63.presentation.xml) there are a cases for `figure` when `unnumbered="true"` but `figure/name` contains a text that should be displayed:
```xml
<figure id="_191daf26-bc79-43e0-a0bc-362798f73860" unnumbered="true">
<name>Userpermit Structure</name>
```
