### ISSUE TITLE
Extracting LaTeXML to a separate gem

### ISSUE THREAD

**Issue by skalee** [metanorma/metanorma-standoc#317]
I need `latexmlmath` for https://github.com/geolexica/geolexica-server/issues/108. I am going to extract https://github.com/metanorma/metanorma-standoc/blob/2fc3253/lib/metanorma/standoc/latexml_requirement.rb to a separate gem, then add the new gem as this project's dependency.

Most likely I will also enable `--preload=amssymb` option in program calls, that is [here](https://github.com/metanorma/metanorma-standoc/blob/2fc3253b202e46a38ae2797fba1cfd3fa1939c0e/lib/metanorma/standoc/latexml_requirement.rb#L32-L36). I need it in order to make some symbols working, e.g. `\backepsilon`. I can make that customizable, if needed.

Any objections, @opoudjis?

**Comment by skalee** [comment]
The other option would be to implement a multi-backend (external tools like LaTeXML, MathJax, Pandoc and some Ruby gems like AsciiMath) converter which translates between MathML, LaTeX Math, and AsciiMath back and forth with consistent API. But I don't think that going that far is really needed. Especially that some of these require additional configuration, hence it won't be that straightforward anyway.

**Comment by ronaldtse** [comment]
@skalee ideally there is a single backend or a composite backend that supports conversion between MathML, LaTeX math and Asciimath. There is also a need to support MathType as output and input. The basis of MathML does not change with configuration, so it should be straightforward (not necessarily easy) -- the difficult part is the LaTeX, since LaTeXML is based on Perl.

**Comment by ronaldtse** [comment]
Maybe we should consider porting http://math.etsu.edu/LaTeXMathML/LaTeXMathML.js to Ruby as a gem. Perl as a dependency is quite heavy for us.

**Comment by skalee** [comment]
We already have separate libs for some conversions, for instance https://github.com/metanorma/mathml2asciimath. This is why I suggested implementing only a minimalistic gem just for LaTeX Math => MathML.

If you mean adding even more formats, then I agree that a generic converter may be a better option. But on the other hand, multi-format converter is a considerably larger project.

Supporting `n` formats in multi-format converter means that there are `n*(n-1)` possible pairs of input and output formats. We can simplify it by using some intermediate format (I presume MathML), so that conversion from X to Y will be split into to steps: from X to MathML, and from MathML to Y. But in this case conversion involves two backends, each of which may require some configuration. This is doable, but it it won't be straightforward in use, at least in some cases. User can hide this complexity under his own helper method however.

----

Regarding performance and Perl, a lot can be memoized or cached. I expect that this will make a huge difference.

**Comment by ronaldtse** [comment]
> But in this case conversion involves two backends, each of which may require some configuration. 

What kind of configuration are you thinking of?

> Regarding performance and Perl, a lot can be memoized or cached. I expect that this will make a huge difference.

I'm more worried about the ongoing maintenance effort we need to keep a Perl stack...

**Comment by skalee** [comment]
In case of LaTeXML, `--preload=amsmath --preload=amssymb` works for us and I presume will suit most needs, but I suppose some folks will have different needs. Also I won't be surprised if users will insist on things like binpath. Similarly for Pandoc backend. And in AsciiMath gem, one can have custom symbol tables, for instance.

Converters are usually configurable to some degree.

**Comment by ronaldtse** [comment]
@skalee I'm going to try getting this setup: https://github.com/metanorma/latexmath/issues/6 Fingers crossed...

**Comment by ronaldtse** [comment]
@manzhikov is going to take care of metanorma/latexmath#6 , a pure Ruby gem for parsing LaTeX math. This will obsolete the Perl toolchain we currently need. Will update this ticket once done.

**Comment by skalee** [comment]
Sounds good. I'll implement simple helpers in Jekyll-Geolexica for now. Perl stack won't hurt in GHA.

**Comment by opoudjis** [comment]
latexmath has now been incorporated into metanorma, and the Perl stack removed as a dependency
