### ISSUE TITLE
Integrate with Relaton BibTeX functionality

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#319]
OGC needs to migrate/re-use bibliography from the BibTeX format in Metanorma.

Given Metanorma uses Relaton for references, this task relies on the completion of 
https://github.com/metanorma/relaton/issues/48 .

This is time-sensitive work. Thanks!

**Comment by ronaldtse** [comment]
From @andrew2net 
> `RelatonBib::BibtexParser.from_bibtex(bibtex)`

@opoudjis this means Metanorma can support BibTeX `.bib` files in Relaton directly.

**Comment by ronaldtse** [comment]
@opoudjis Relaton already supports BibTeX parsing and importing as a Relaton data source: https://github.com/relaton/relaton-bib/issues/57 . 

This was recently requested here:
https://github.com/metanorma/metanorma-ogc/issues/329

**Comment by ronaldtse** [comment]
We currently have a document attribute that sets the relaton dataset as `:local-cache:`, but it should likely be just a generic relaton source location:
https://www.metanorma.org/author/ref/document-attributes/

For BibTeX, we could use:
```adoc
:relaton-data-source: source_one=../bibtex/my_bibtex_file.bib
:relaton-data-source: source_two=../bibtex/my_bibtex_file2.bib
```

and we can refer to as:
```
* [[[internal-reference1, source_one(key)]]] 
* [[[internal-reference2, source_two(key)]]] 
```

**Comment by opoudjis** [comment]
I am not, of course, going to welcome open-ended names of relaton data sources, which can potentially clash with other wrappers around bibliographic tag, and which will make parsing utterly unpredictable. The suggestion of 

````
* [[[internal-reference1, source_one(key)]]] 
* [[[internal-reference2, source_two(key)]]] 
````

is discarded.

The intent is apparently for the bibliographic tag not to indicate what format the bibliographic file is in, because explicitness is not fun enough, and I should instead rely on either the file suffix, or on Metanorma peeking inside the file.

What could possibly go wrong with that.

Going along with the rest of this,

````
:relaton-data-source: source_one=../bibtex/my_bibtex_file.bib
:relaton-data-source: source_two=../bibtex/my_bibtex_file2.bib
````

will be referenced as:

````
* [[[internal-reference1, local-file(source_one, key)]]] 
* [[[internal-reference2, local-file(source_two, key)]]] 
````

and

````
:relaton-data-source: ../bibtex/my_bibtex_file.bib
````

as

````
* [[[internal-reference1, local-file(key)]]] 
* [[[internal-reference2, local-file(key)]]] 
````

I would prefer

````
:relaton-data-source: file=../bibtex/my_bibtex_file.bib,id=source_one,format=bibtex
````

But that's going to be too much for people to enter willingly.

**Comment by ronaldtse** [comment]
```
:relaton-data-source: file=../bibtex/my_bibtex_file.bib,id=source_one,format=bibtex
```

Is okay. Better than having an unpredictable key. Let's do this.

**Comment by opoudjis** [comment]
The proposed markup will not work, the repeated attribute keys will overwrite each other.

Instead, I propose we move the identifier, which is supposed to be unique, into the key:

````
:relaton-data-source-source_one: ../bibtex/my_bibtex_file.bib
:relaton-data-source-source_two: file=../bibtex/my_bibtex_file.bib,format=bibtex
:relaton-data-source: file=../bibtex/my_bibtex_file.bib,format=bibtex
````

If relaton-data-source is present, that is a unique bibliographic source. If relaton-data-source-{id} are present, they are the sources.

**Comment by ronaldtse** [comment]
We need to:
1. provide documentation
2. test it out
3. provide example files

**Comment by opoudjis** [comment]
Documentation has been provided in one of the many metanorma.org updates you have still not approved; in fact it's one of the first ones, https://github.com/metanorma/metanorma.org/commit/3f3ebb227e31b39a5bde9e2a85a3efcb55e2e83b

Testing and example files are already done in https://github.com/metanorma/metanorma-standoc/commit/31e0feab7d1d04e0f01a6bea66cd58b8907168e5#diff-1fd205e7e8774249755dd18f77d0000b36d8885e6c3157d67fa8d35a5e032735

**Comment by opoudjis** [comment]
metanorma.org update lost, resubmitting
