### ISSUE TITLE
Add current metanorma version and XML type to Metanorma XML

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#325]

**Comment by ronaldtse** [comment]
Also need to define the type of MN XML in the header: an external processor that can only read presentation XML will have undefined behavior on reading semantic XML.

Is this an additional namespace or an attribute?

**Comment by opoudjis** [comment]
Attribute: `<{root element} type="presentation|semantic" version="metanorma flavour version">`
