### ISSUE TITLE
Unicode symbols in Asciimath

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#330]
From https://github.com/metanorma/bipm-si-brochure/pull/8:

For example, consider this formula:

![o-cap](https://user-images.githubusercontent.com/33627611/92480674-3f337b80-f1b3-11ea-9688-0288c04dce98.PNG)

I typeset it in several ways:

````
* stem:[""^199 "Hg"^+]

* stem:[" "^199 "Hg"^+]

* stem:["&#x200c;"^199 "Hg"^+]

* stem:["&nbsp;"^199 "Hg"^+]
````

it renders: 

Doc output:
![doc-cap](https://user-images.githubusercontent.com/33627611/92480811-69853900-f1b3-11ea-94de-7db2e7578c9a.PNG)

Html output:
![html-cap](https://user-images.githubusercontent.com/33627611/92480826-6f7b1a00-f1b3-11ea-8b5c-39d82c2005f1.PNG)

As shown, none of the options gives a proper rendering in DOC version. But if I type `^199^Hg^+^`, the result is correct for both versions.  

----

It's curious that the unicode escapes are failing to happen in one or both of MathML, OOXML; worth investigating

**Comment by opoudjis** [comment]
No, `""^199 "Hg"^+` does not render properly in a stem block either. (And with it involving an exponent of an empty string, I'm not surprised it doesn't)

**Comment by manuel489** [comment]
> No, `""^199 "Hg"^+` does not render properly in a stem block either. (And with it involving an exponent of an empty string, I'm not surprised it doesn't)

Oh yes, you are right @opoudjis . I was actually referring to the Unicode symbols cases (`stem:["&#x200c;"^199 "Hg"^+]`,  `stem:["&nbsp;"^199 "Hg"^+]`) . These are the ones that work in stem blocks.

**Comment by opoudjis** [comment]
Inline stem and block stem are processing escapes differently—presumably because stem blocks are passthrough blocks, whereas stem macros are not passthrough. Changing &amp;# to &# peremptorily in AsciiMath. Such changes were already necessary for processing MathML embedded in Asciidoctor. This is not great, because we're randomly changing ampersands, but I don't see that we have much choice.

**Comment by opoudjis** [comment]
&nbsp; is not working; I'm reluctant to change all ampersands in inline AsciiMath expressions. But &# is now processed correctly.
