### ISSUE TITLE
Integrate latexmath gem

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#331]

**Comment by ronaldtse** [comment]
This depends on https://github.com/plurimath/latexmath/issues/9  

This allows us to remove the Perl dependencies. We will need to update install formulas after this.

FYI @CAMOBAP

**Comment by opoudjis** [comment]
Disabling test of malformed LaTeX: as far as I can tell, the latexmath gem catches all errors, and returns an empty mathml expression.
