### ISSUE TITLE
Remove Perl dependency due to usage of Ruby latexmath gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#332]
We now use the latexmath gem so we can deprecate all Perl dependencies.

Let's use this ticket to track removal of the Perl dependencies in all deliverables and GitHub Actions:
- packed-mn
- homebrew-metanorma
- chocolatey-metanorma
- snap-metanorma
- all sample repositories (GitHub Actions)

**Comment by ronaldtse** [comment]
Actually we may not want to do this -- we may still use LaTeXML to generate Metanorma XML.

**Comment by CAMOBAP** [comment]
@ronaldtse yep we still use `latexmlmath` tool which depends on `perl` https://github.com/metanorma/metanorma-standoc/blob/master/lib/metanorma/standoc/latexml_requirement.rb#L32-L36

Should we still keep this ticket?

**Comment by ronaldtse** [comment]
@CAMOBAP we no longer use latexmathml . So we should remove all code related to latexmathml. 

However, we may include latex compilation (tex2mn) that requires latexml, which is the same “requirement”...

**Comment by ronaldtse** [comment]
For better Perl integration I wonder if this works: https://github.com/zephirworks/ruby-perl

**Comment by CAMOBAP** [comment]
Done, metanorma-spap will be committed in the scope of https://github.com/metanorma/metanorma-snap/issues/9
