### ISSUE TITLE
Date format support in yaml2text template

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#344]
When compiling date format values (e.g. `date: 1889-09-28`) in yaml2text blocks, no rendering is shown. They'd need to be enclosed in quotes (`date: '1889-09-28'`) in order to work. Could it be a support issue?

**Comment by ronaldtse** [comment]
Thanks @manuel489 , I wonder if this is a type casting issue - because we will need to support all YAML types in Liquid... ping @w00lf

**Comment by w00lf** [comment]
> Thanks @manuel489 , I wonder if this is a type casting issue - because we will need to support all YAML types in Liquid... ping @w00lf

@ronaldtse the issue was because of Yaml#safe_load, by default it does not allow whitelisted classes, fixed in #345

**Comment by manuel489** [comment]
Issue fixed, confirmed. Thanks @w00lf.  Closing.
