### ISSUE TITLE
Several malformed characters in yaml2text output

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#346]
When compiling some French text with yaml2text, several malformed characters appear.

For exmple:
````
* autorise le Comité international à faire, à tous les certificats des
mètres prototypes des coulées Johnson-Matthey et de 1874, une addition donnant
les nouvelles formules trouvées pour la dilatation de ces alliages, telles qu'elles
résultent des déterminations faites au Bureau international, et les nouvelles
valeurs des règles à 0° qui en sont la conséquence.
````

Output:

![Capture-fr](https://user-images.githubusercontent.com/33627611/93922932-a50a2200-fce0-11ea-8b7f-fcd8d6800ec8.PNG)

Ping @ronaldtse , @w00lf 

Thanks!

**Comment by opoudjis** [comment]
This is almost certainly files not being opened in UTF-8 but in ASCII. Please apply UTF-8 encoding explicitly in file access.

**Comment by w00lf** [comment]
@opoudjis added in #348

**Comment by manuel489** [comment]
Problem solved. Thank you @w00lf  and @opoudjis!  Closing.
