### ISSUE TITLE
(URGENT) yaml2text nesting fails

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#347]
In https://github.com/metanorma/bipm-si-brochure/pull/22 the file:
https://github.com/metanorma/bipm-si-brochure/pull/22/files#diff-8b5e7ad97ed1c17d3424c897e975f844

Uses nesting to define yaml2text within yaml2text. i.e.:

```adoc
[yaml2text,sections-a1-yaml/resolutions.yml,paths]
----
{% for path in paths %}

[yaml2text,cgpm-resolutions/{{ path }},data]
--

== {{ data.metadata.title }}, {{ data.metadata.date | split: "-" | first }}

{% for resolution in data.resolutions %}

=== {{ resolution.title }}

[align=center]
*Resolution {{ resolution.identifier }}*

{% for approval in resolution.approvals %}
{{ approval.message }}
{% endfor %}

...

{% endfor %}
--

{% endfor %}
----

```

The output (if we switch to use `:mn-document-class: iso`) becomes:
<img width="640" alt="Screen Shot 2020-09-23 at 9 43 20 AM" src="https://user-images.githubusercontent.com/11865/93954918-38932f80-fd81-11ea-9765-f360d90fcce9.png">

This means that the inner yaml2text didn't work at all. I noticed that `yaml2text` expects a source code block (`----`), but but this way we cannot enable nesting. We must allow any number of matching `--` (from 2 `-` to n `-`);.

**Comment by w00lf** [comment]
> In [metanorma/bipm-si-brochure#22](https://github.com/metanorma/bipm-si-brochure/pull/22) the file:
> https://github.com/metanorma/bipm-si-brochure/pull/22/files#diff-8b5e7ad97ed1c17d3424c897e975f844
> 
> Uses nesting to define yaml2text within yaml2text. i.e.:
> 
> ```
> [yaml2text,sections-a1-yaml/resolutions.yml,paths]
> ----
> {% for path in paths %}
> 
> [yaml2text,cgpm-resolutions/{{ path }},data]
> --
> 
> == {{ data.metadata.title }}, {{ data.metadata.date | split: "-" | first }}
> 
> {% for resolution in data.resolutions %}
> 
> === {{ resolution.title }}
> 
> [align=center]
> *Resolution {{ resolution.identifier }}*
> 
> {% for approval in resolution.approvals %}
> {{ approval.message }}
> {% endfor %}
> 
> ...
> 
> {% endfor %}
> --
> 
> {% endfor %}
> ----
> ```
> 
> The output (if we switch to use `:mn-document-class: iso`) becomes:
> <img alt="Screen Shot 2020-09-23 at 9 43 20 AM" width="640" src="https://user-images.githubusercontent.com/11865/93954918-38932f80-fd81-11ea-9765-f360d90fcce9.png">
> 
> This means that the inner yaml2text didn't work at all. I noticed that `yaml2text` expects a source code block (`----`), but but this way we cannot enable nesting. We must allow any number of matching `--` (from 2 `-` to n `-`);.

yaml2text and json2text support any delimiters supplied after the block definition. The problem here is implementation of nested yaml2text contexts. The snippet you put in the description is quite complex to implement, we cant render nested yaml2text blocks until we render root level block, because it consists of filenames and we cannot render nested blocks without root context. I tried to implement it but have not got any success so far. I need more time on this.

**Comment by ronaldtse** [comment]
Fixed in latest commits, thanks!
