### ISSUE TITLE
Support for Asciidoc `start` attribute in ordered lists

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#361]
*From https://github.com/metanorma/bipm-si-brochure/issues/24*

The `[start=n]` attribute for ordered lists seems not to be supported in Metanorma.

````
[start=4]
. Step four
. Step five
. Step six
````

Renders as

*Metanorma*
![issue8-generated](https://user-images.githubusercontent.com/33627611/95934072-fa949480-0d9d-11eb-8369-32a9d0ea7b2c.PNG)

*AsciiDoc*
![issue8-original](https://user-images.githubusercontent.com/33627611/95934087-02543900-0d9e-11eb-8859-dfe29980d25e.PNG)

**Comment by opoudjis** [comment]
No, and there is an issue about this already: merging issue. https://github.com/metanorma/metanorma-standoc/issues/349

While it would be possible to implement list start, it would be very cumbersome to implement in Word, and I do not feel that the instance in BIPM, which I have put a workaround for, warrants the effort of introducing it into Metanorma.
