### ISSUE TITLE
French mathematical typesetting

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#367]
From https://github.com/metanorma/bipm-si-brochure/issues/41, it emerges that the French have different conventions on italicisation in mathematics to the Anglosphere; and BIPM follows French practice in both French and English.

* `mi` in MathML contains non-numeric variables and constants
* `mi/@mathvariant` allows italic or normal values to override the MathML default
* The default encoded in jEuclid and MathJax, as stipulated by the MathML, is: normal if multiple characters, italic if single character
* TeX allows the following customisations: 
  * math-style=upright: never italic
  * math-style=ISO: always italic
  * math-style=TeX (default): Greek capital letters normal, lowercase Greek letters and Roman letters italic
  * math-style=French: Greek capital letters normal, lowercase Greek letters normal, uppercase Roman letters normal, lowercase Roman letters italic

https://mirror.aarnet.edu.au/pub/CTAN/macros/latex/contrib/frenchmath/frenchmath.pdf (which does not mention lowercase Greek at all), http://milde.users.sourceforge.net/LUCR/Math/math-font-selection.xhtml#math-style

There is a discrepancy between MathML's single character criterion and this: TeX is talking about runs of text in general, but MathML is referring to mi specifically, which excludes superscripts and subscripts. So ν<sub>1</sub> in MathML is  `<msub><mi>&nu;</mi> <mn>1</mn></msub>` , and the `<mi>&nu;</mi>` will be italicised as one character long. 

This means that we need to introduce configurations on MathML, to insert `mi/@mathvariant` to generate rendering other than the MathML default (which is ISO).

The issue about units in MathML being `mi/@mathvariant = normal` is separate: units have to be semantically identified as such in AsciiMath input, and that needs to translate into `mi/@mathvariant = normal` rendering as semantically derived markup, not as a default based on character set.

Because of the requirement for Greek lowercase to be upright (which, astonishingly, is not supported by the MathJax default font), we need to switch our default MathJax font to STIX. (I've already done this for BIPM, but will generalise it.)

**Comment by opoudjis** [comment]
@ronaldtse You will expect to make this a separate plurimath gem as postprocessing of MathML. Not yet, I request: let's wait till the code settles down, especially in case there's inheritance or other effects to deal with. I'm implementing this for now in standoc.

**Comment by opoudjis** [comment]
Since MathJax v3 does not yet support STIX, but only MathJax TeX, and since MathJax TeX does not support upright Greek characters (my God), we will not be switching to MathJax v3 (released Sept 2019). As of 3.0.4, MathJax deals with upright Greek by plugging in Plane 1 characters instead (https://github.com/mathjax/MathJax-src/pull/455); we are in fact doing that for Word in the same context, https://github.com/metanorma/html2doc/issues/47, but I'd really rather we use a real font like STIX instead, which MathJax v3 will support... eventually.

**Comment by ronaldtse** [comment]
@opoudjis could you file an issue for MathJax so they will fix it someday? Thanks.
