### ISSUE TITLE
Implement "date:[]" macro

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#371]
*In relation to https://github.com/metanorma/metanorma-bipm/issues/38#issuecomment-714850423*

Implement `date:[...]` for localize date formats.

**Comment by opoudjis** [comment]
I don't regard this currently as high priority.

**Comment by opoudjis** [comment]
Format will be:

date:FORMAT[content]

where FORMAT is one of the accepted date format representations from strftime

Need to recover internationalised month and day names from twitter_cldr_rb, but it won't be easy, they are only present abbreviated in DateTime.now.localize(:ja).to_additional_s("E"/"MMM"). Can construct them from pure calendar:

TwitterCldr::Shared::Calendar.new(:de).months(:wide), TwitterCldr::Shared::Calendar.new(:de).weekdays(:narrow)

https://ruby-doc.org/stdlib-2.6.1/libdoc/date/rdoc/DateTime.html

https://github.com/twitter/twitter-cldr-rb/blob/afb5c20aa8eeb23926e78865bf205541974a7dd1/spec/shared/calendar_spec.rb#L55

Lookup via %-m and %a.downcase.to_i

**Comment by opoudjis** [comment]
The format string needs an escape for space, since it must be a string without space. That escape shall be %_

The macro format is instead date:[VALUE], date:[VALUE,FORMAT], with %F as the default supplied format.
