### ISSUE TITLE
Is it possible to typeset list items into footnote blocks?

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#373]
The following table contains unordered list items nested in the footnotes:

![Capture](https://user-images.githubusercontent.com/33627611/98306296-e9543780-1f99-11eb-8d44-c55246192a39.PNG)

Is it possible to reproduce it in Metanorma?

**Comment by opoudjis** [comment]
Not yet, but https://github.com/metanorma/metanorma-bipm/issues/62 will address this.
