### ISSUE TITLE
Use Fontist font manifest to install necessary fonts in Metanorma flavors (and upgrade Fontist to 1.5+)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#375]
Metanorma currently passes required font information to Fontist like this:

https://github.com/metanorma/metanorma-iso/blob/55568ddec7defdefc8126495296e9b4cd04d2b3c/lib/metanorma/iso/processor.rb#L5-L12

We need to migrate this to the Fontist Manifest format (which needs upgrading fontist to 1.5+):
https://github.com/fontist/fontist#install

This is necessary for the completion of metanorma/metanorma-bipm#63

**Comment by ronaldtse** [comment]
In addition, we need to refactor https://github.com/metanorma/metanorma-cli/blob/d6d27e3f25529fb7aa6b5a3faa03583bdc7fbea0/lib/metanorma/cli/setup.rb#L50-L55 so that does not "copy" fonts because it is unnecessary to copy fonts.

**Comment by ronaldtse** [comment]
As per discussion with @opoudjis , we should run Fontist on every run (i.e. check and install fonts using Fontist every time) so that users don't need to manually run `metanorma setup`.

In addition, we should abort the metanorma run if fonts are not available.

* Add CLI flag `--no-install-fonts` to skip the installation process if the fonts are not available.
* Add CLI flag `--continue-without-fonts` to continue even when fonts are missing.

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for the explanation, it's clear what need to be done, but to be on the same page metanorma-standoc have no `self.fonts_used` so there is no changes need to be done for this repo, only for other flavors, metanorma and metanorma-cli, right?

**Comment by opoudjis** [comment]
On the specifics of what's been done in metanorma and metanorma-cli, I can't really say too much: I'm commenting on the bit I'm seeing, which is what's in metanorma-iso

One. The YAML manifest names just "Regular" as the font to use. That is such an appalling idea, it should not be supported by the interface: we can never anticipate when a user will want to use italics or bold (and in fact our interfaces use them even without the user specifies them), so the only sound practice is to download all styles available. Specify only the font.

Two. We are no longer specifying formats for each font. I don't think that's going to disrupt anything, but it does make me nervous.

Three: there shall be no boilerplate repetition of the location of the manifest:

````
 def fonts_manifest
         __dir__ + "/fonts_manifest.yaml"
       end
````

Instead, use the approach of discovering the flavour's file location featured in metanorma-standoc/lib/asciidoctor/standoc/converter.rb : 

````


def initialize()
...
@libdir = File.dirname(self.class::_file || __FILE__)
end

      class << self
        attr_accessor :_file
      end

      def self.inherited(k)
        k._file = caller_locations.first.absolute_path
      end
````

So in metanorma-nist/lib/asciidoctor/nist/boilerplate.rb:        

````
File.join(@libdir, @series == "nist-cswp" ? "nist_intro_cswp.xml" : "nist_intro.xml")
````

The class Asciidoctor::Standoc::Converter, which all flavours inherit, defines `@libdir` in terms of the current flavour's gem's file location. Downstream flavours, like metanorma-nist, can use that variable to call up the file directory of the current file.

Do the same. The fonts_manifest method appears in  lib/metanorma/iso/processor.rb. The class there inherits from Metanorma::Processor

So, in metanorma, lib/metanorma/processor.rb:

````
def initialize
@libdir = File.dirname(self.class::_file || __FILE__)
#       raise "This is an abstract class!" # get rid of that!
    end

class << self
        attr_accessor :_file
      end

      def self.inherited(k)
        k._file = caller_locations.first.absolute_path
      end

def fonts_manifest
         File.join(@libdir, "fonts_manifest.yaml")
       end
````

And we change *all* flavour instances of `class Processor < Metanorma::Processor` in lib/metanorma/*/processor.rb, to add `super` at the start of each `def initialize()`

As a result, each Metanorma::*::Processor will now have inherited a `fonts_manifest`, which will find the manifest file in the current directory.

**Comment by CAMOBAP** [comment]
> The YAML manifest names just "Regular" as the font to use. That is such an appalling idea...

I have tested and font styles can be committed so the syntax:

```
----
Segoe UI:
Roboto Mono:
```

is valid

> The class Asciidoctor::Standoc::Converter, which all flavours inherit, defines @libdir in terms of the current flavour's gem's file location. Downstream flavours, like metanorma-nist, can use that variable to call up the file directory of the current file.

Now I understand why the ticket was reported for metanorma/metanorma-standoc repository )

@opoudjis thanks you a lot for your critics, I will proceed with new implementation

**Comment by ronaldtse** [comment]
> so the only sound practice is to download all styles available. Specify only the font.

We must specify all font faces of a font. For example, Work Sans has over 20 font faces. We only use 10. We’re taking about hundreds of extra MB for fonts — must specify all font faces in the flavor. 

> Two. We are no longer specifying formats for each font. I don't think that's going to disrupt anything, but it does make me nervous.

Each output format must specify specific fonts and font faces. For example, in OGC the PDF and HTML utilize completely different fonts. This must be made clear in the font manifest.

**Comment by CAMOBAP** [comment]
@opoudjis @ronaldtse PRs is ready for review, according the suggestions:
 - metanorma/metanorma-cli#190
 - metanorma/metanorma#147
 - https://github.com/metanorma/metanorma-standoc/pull/377
 - https://github.com/metanorma/metanorma-nist/pull/249
 - https://github.com/metanorma/metanorma-iso/pull/442

Once they done I will convert `used_fonts` to yaml for all flavors

**Comment by ronaldtse** [comment]
@CAMOBAP:

* Some flavor formats, such as OGC, require different fonts in PDF and HTML. We need to make that distinction in the metanorma-{flavor} level to pass to Fontist (in one YAML).
* Some flavors, such as BIPM, require specific font styles of the font (e.g. Regular, Medium, Medium Italic, etc). These need to be listed as well. (see https://github.com/metanorma/mn2pdf/issues/52#issuecomment-732171496)

**Comment by opoudjis** [comment]
> > so the only sound practice is to download all styles available. Specify only the font.
> 
> We must specify all font faces of a font. For example, Work Sans has over 20 font faces. We only use 10. We’re taking about hundreds of extra MB for fonts — must specify all font faces in the flavor.

You are opening the process up to error, @ronaldtse. The test manifest omitted italic font. (!!!) Someone is going to be forced to confirm that italic, bold, bold italic is defined for all fonts. Who is that going to be?

**Comment by ronaldtse** [comment]
> Someone is going to be forced to confirm that italic, bold, bold italic is defined for all fonts. Who is that going to be?

Yes this is a necessity. The font world is too complex to be simplified as "get all fonts".

1. Every font face is licensed separately -- this applies to Regular/Italics/Bold, too. Moreover, there are font styles like "Medium" or "Heavy" that have their own version of "Regular/Italics/Bold".

There is no computer font construct today that logically links "Font X Medium" together with "Font X Medium > Regular". Hence each single font needs to be identified and encoded manually.

For example:
Calibri Regular
```
Family:              Calibri
Subfamily:           Regular
Full name:           Calibri
PostScript name:     Calibri
```

Calibri Bold
```
Family:              Calibri
Subfamily:           Bold
Full name:           Calibri Bold
PostScript name:     Calibri-Bold
```

But, Calibri Bold Italic has "Subfamily" of "Bold Italic". Not just "Italic".
```
Family:              Calibri
Subfamily:           Bold Italic
Full name:           Calibri Bold Italic
PostScript name:     Calibri-BoldItalic
```

And Calibri Light Italic:
```
Family:              Calibri Light
Subfamily:           Italic
Full name:           Calibri Light Italic
PostScript name:     Calibri-LightItalic
```

This is why it is absolutely necessary to define the fonts used explicitly.

2. Some fonts have Italics/Bold completely separate. For example, Cambria comes within a TTC container (Cambria + Cambria Math). But Cambria Italics/Bold come as TTF files.

<img width="602" alt="Screen Shot 2020-11-24 at 4 08 39 PM" src="https://user-images.githubusercontent.com/11865/100065903-522f2100-2e6f-11eb-9c69-0ac2094a42aa.png">

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis should we also remove default_fonts methods from `[Html|Word|Pdf]Convert`, like this https://github.com/metanorma/metanorma-iso/blob/master/lib/isodoc/iso/html_convert.rb#L20

**Comment by ronaldtse** [comment]
@CAMOBAP I think `default_fonts` is used for CSS only. Are you asking if we should streamline all the font names used to a single location to prevent mismatches (font name to use in Word CSS, HTML CSS and PDF)?

We must keep in mind that each format output may use different fonts (OGC uses different fonts in HTML CSS and PDF).

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for explanation, I just asked because I have found fonts in metanorma.yml (in metanorma-generic)

**Comment by ronaldtse** [comment]
> We can just call this:

As @CAMOBAP pointed out, Fontist doesn't support this yet. I have made a ticket https://github.com/fontist/fontist/issues/178 for this.

**Comment by ronaldtse** [comment]
@CAMOBAP Fontist::Install.from_hash is now available since fontist/fontist#180 . This is now actionable. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse PRs ready for review

**Comment by ronaldtse** [comment]
@CAMOBAP if they look good to @Intelligent2013 they look good to me. Thanks!

**Comment by CAMOBAP** [comment]
After end-end testing, I have found a serious issue in my implementation https://github.com/metanorma/metanorma-standoc/pull/377

The key problem that [CLI arguments from metanorma-cli](https://github.com/metanorma/metanorma-cli/blob/master/lib/metanorma/cli/command.rb#L35-L37) didn't reach the [`metanorma-standoc`](https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/converter.rb#L77).

After browsing the code and research on the potential right implementation I see two approaches here:
1. modify each 'downstream' gem (`metanorma`, `isodoc`, and probably some other) to not filter-out options which passed from `metanorma-cli` so they will be delivered to `metanorma-standoc` https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/converter.rb#L77
2. Move https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/converter.rb#L97-L163 logic to `metanorma` gem [(inside this method)](https://github.com/metanorma/metanorma/blob/master/lib/metanorma/compile.rb#L228). AFAIR I started the implementation of this logic in `metanorma` gem but then changed my mind after review/comments

To me the second approach looks much clear:
 - we will be able to remove unsafe logic like [this](https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/converter.rb#L93-L95)
 - also we will no need to fix tests in flavor gems by passing `no_install_fonts` flag

To make sure that this will not break anything else I would like to hear your opinion @ronaldtse @opoudjis 

P.S. @ronaldtse could you please invite to the discussion more developer who can review those ideas

**Comment by ronaldtse** [comment]
The proper approach is to have the CLI delegate different kinds of options:
- Metanorma general options
- Per-flavor options

Some options are to be carried across the stack of gems:
- CLI (metanorma-cli) => input and output processor (metanorma/metanorma-standoc/isodoc)

The only interface between Metanorma CLI and the processors is the "compile" method, and it is wise to keep that as such.

So yes, please:
> Move https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/converter.rb#L97-L163 logic to metanorma gem

Ping @abunashir for comments.

**Comment by CAMOBAP** [comment]
@ronaldtse PRs ready for review (suggestions adressed)
 - https://github.com/metanorma/metanorma/pull/153
 - https://github.com/metanorma/metanorma-standoc/pull/407
 - https://github.com/metanorma/metanorma-cli/pull/206

**Comment by CAMOBAP** [comment]
I suppose we can close this one
