### ISSUE TITLE
Compilation failure upon certain configuration in equations

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#395]
Apparently, there is a conflict issue between vertical bar symbol (`|`) and closing braces (`{: :}`) in math environment.

Consider this example:

````
[stem]
++++
x = {: z/{|y//3 + z|} :}
++++
````

This equation fails to generate in Metanorma, but not in [other generators](https://codepen.io/bqlou/pen/yOgbmb).

This configuration is need for certain cases, like:

````
[stem%unnumbered]
++++
g_X (xi) = 1/{4d} max(ln{:{w+d}/{max(|xi-x|,w-d)}:},0)
++++
````

Present in page 21 of  [JCGM_101_2008_E.pdf](https://github.com/metanorma/mn-samples-bipm/files/5601384/JCGM_101_2008_E.pdf) (among other cases)

**Comment by opoudjis** [comment]
This is the ambiguity in Asciidoc Asciimath between `|` (bar) and `|: :|` (bracket); the latter needs to be used for absolute signs, in order for the context-free grammar of https://github.com/asciidoctor/asciimath/blob/ce84db89cfc3f8f91ef16a19375b4e812b205327/lib/asciimath/parser.rb to parse correctly.
