### ISSUE TITLE
Malformed vertical bar in inline math stem

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#411]
Vertical bars are showing inclined in inline stem blocks:

````
include the relative combined standard uncertainty stem:[u_{"c"}(y)//│y│], stem:[│y│ != 0], when appropriate;
````

renders

![Capture1](https://user-images.githubusercontent.com/33627611/104193727-ceb59900-53f6-11eb-8368-85e61287d769.PNG)

**Comment by opoudjis** [comment]
Remember: in Asciidoctor Asciimath, absolute bars are '|: :|`, not `|`, since the parser needs to know explicitly that they are brackets surrounding an expression. 

However, `stem:[u_{"c"}(y) // │: y :│ ]` is still not working...

**Comment by opoudjis** [comment]
Ah. Manuel, Copy Paste Considered Harmful. AsciiMath expects to see a `|` character. But what you've got in your asciimath is actually U+2502, BOX DRAWINGS LIGHT VERTICAL. Asciimath naturally does not recognise that character at all. Clearly they have inserted a typographically more pleasant variant of `|` for the maths, but you can't use it in AsciiMath.

**Comment by manuel489** [comment]
Thanks @opoudjis ! Changes applied to master.
