### ISSUE TITLE
Model updates to support bilingual PDF generation

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#420]
From https://github.com/metanorma/metanorma-bipm/issues/101:

Proposed attributes:

* The document attribute or flavour default `:align-cross-elements:` is a specification that, say, the elements "p, note, term" shall always be aligned in bilingual text. It is added to //bibdata/ext, as separate tags, not space-delimited. So presumably, a repeating `//bibdata/ext/parallel-align-element` tag. As a document attribute in Asciidoctor, it will be comma delimited.

* `@name` on any element is an identifier that is not guaranteed to be unique in a document (or document collection). It is used to align two block elements with the same `@name` attribute value.

* `@multilingual-rendering` on any block element specifies how a block element may be rendered in a multilingual document. The options are: "common" for an element that is shared across all languages; "all-columns" for elements that span all columns of text, and are displayed consecutively; "parallel" for a block element that is to be aligned to the element occupying the same position in the document hierarchy; and "name" for all block elements sharing the same `@name` attribute as the current element.

**Comment by opoudjis** [comment]
From Ronald:

> Also a note that we will need validation on compilation for the semantic XML, i.e. so that the user won't miss alignments (e.g., "the element foo [en] does not have a corresponding element in [fr]").

**Comment by opoudjis** [comment]
> The document attribute or flavour default :align-cross-elements: is a specification that, say, the elements "p, note, term" shall always be aligned in bilingual text. It is added to //bibdata/ext, as separate tags, not space-delimited. So presumably, a repeating //bibdata/ext/parallel-align-element tag. As a document attribute in Asciidoctor, it will be comma delimited.

This is not an attribute of a document, but of rendering: it will be passed as an argument to isodoc, and thence to PDF generation.

**Comment by opoudjis** [comment]
> `@name` on any element is an identifier that is not guaranteed to be unique in a document (or document collection). It is used to align two block elements with the same @name attribute value.

`@name` is already in use, as is `@label`; make it `@tag`

**Comment by opoudjis** [comment]
@Intelligent2013 I can pass you the contents of `align-cross-elements` as a command line option, you would just need to tell me how.

**Comment by Intelligent2013** [comment]
> 
> 
> @Intelligent2013 I can pass you the contents of `align-cross-elements` as a command line option, you would just need to tell me how.

@opoudjis here https://github.com/metanorma/metanorma-bipm/issues/101#issuecomment-766767378 we've decided:

> - `align-cross-elements` -> `//bibdata/ext/parallel-align-element`

as I understand, now is preferable for you to pass this cmd parameter for mn2pdf, right?

Then you can do so (but I have to add the processing of it):
`java -Xss5m -Xmx2048m -jar mn2pdf.jar --xml-file ... --xsl-file ... ... --align-cross-elements`

Another option - add the tag `metanorma-collection/align-cross-elements` or `metanorma-collection/manifest/align-cross-elements`.
In any case any option is ok for me.

**Comment by Intelligent2013** [comment]
**update**:
@opoudjis sorry, I've forget that `align-cross-elements` isn't true/false element, but contains a list of elements. So then command line is:
```
java -Xss5m -Xmx2048m -jar mn2pdf.jar --xml-file ... --xsl-file ... ... --param align-cross-elements="clause note title terms term termsource"
```
(new parameter is `--param align-cross-elements="clause note title terms term termsource`)

or values separated by comma:
```
java -Xss5m -Xmx2048m -jar mn2pdf.jar --xml-file ... --xsl-file ... ... --param align-cross-elements="clause,note,title,terms,term,termsource"
```
