### ISSUE TITLE
Smart term references not working when terms are placed in term sections

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#433]
Occurs here: https://github.com/metanorma/iso-tc184-sc4-directives

<img width="786" alt="Screenshot 2021-02-26 at 11 21 25 AM" src="https://user-images.githubusercontent.com/11865/109250502-c4bfec00-7824-11eb-9029-6e5dc375befc.png">

But the term "recommendation" is defined here:
<img width="795" alt="Screenshot 2021-02-26 at 11 21 37 AM" src="https://user-images.githubusercontent.com/11865/109250520-cb4e6380-7824-11eb-8160-e09aecb0c052.png">

**Comment by opoudjis** [comment]
The `term:[]` macro presupposes that all term anchors are prefixed with term-, which is indeed what happens automatically. This document has preempted that, and has put its own anchor in front of the term recommendation, `[[recommendation]]`. Therefore, the attempt to resolve `term:[recommendation]`, which is in fact searching for `term[@id = 'term-recommendation]`, fails. 

RTFM. Make the anchor of `=== recommendation` be `[[term-recommendation]]`, or better still, remove the anchor completely, and allow it to be auto-generated.
