### ISSUE TITLE
Make validation optional

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#44]
For huge documents, such as NIST SP 800-53r4, validation potentially adds many minutes to execution time. @ronaldtse: Should we make validation of documents optional?

**Comment by ronaldtse** [comment]
We definitely could, but we should definitely note that it is not recommended — unless the user really knows what’s going on with disabling validation.

**Comment by opoudjis** [comment]
This is already in place: `:novalid:` flag. Making sure it is observed in all gems.
