### ISSUE TITLE
Generating space before UnitsML expression

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#441]
Blank spaces are not always automatically added before the units in generated documents.

If space is explicitly used in source file, e.g. `stem:[f = 563260223513 (5) "unitsml(kHz)"]`, it is generated in output document as well. However, if it is not, e.g. `stem:[f = 563260223513 (5)"unitsml(kHz)"]`, output file is also not generating space.
 
Generated example:
![image](https://user-images.githubusercontent.com/55683568/110867568-430d9b00-82c7-11eb-8196-7fd958585287.png)

Additional note: spaces are not needed in case of `deg`, `prime` and `dprime`.

**Comment by opoudjis** [comment]
> Additional note: spaces are not needed in case of deg, prime and dprime.

Addressed in https://github.com/plurimath/asciimath2unitsml/issues/19

**Comment by opoudjis** [comment]
The condition for inserting space is that the unit is preceded by a literal number, MathML `<mn>`. So `stem:[f = 563260223513"unitsml(kHz)"]` does *not* require a space in the AsciiMath, to insert the space.

`(5)` is not a number, as far as MathML is concerned: it is `<mfenced open="(" close=")"><mrow><mn>5</mn></mrow></mfenced>`. And although you have reported that the space is generated if there is space before the quote, in my instance, it is not.

I'm not enthusiastic about this, but I will insert space before a unitsml expression if there is any MathML element preceding it, not just `mn`.
