### ISSUE TITLE
Bad rendering in closing quotes

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#445]
*I've been noticing this issue since a while. But I wasn't sure about its origin until now.*

When a text is quoted, sometimes the closing quote is shown as an opening quote.
This may happen under two conditions:

1. when the text contains stem expressions, and
2. when the text is a hyperlink followed by punctuation mark (like a comma, period, etc.)

As an example of these two cases, consider this random text:
````
After removal of the native oxide by heating in UHV, and in the case of Si surfaces the (111) shows a "`stem:[7 xx 7]`"...

For more information visit "`link:https://www.metanorma.org/[https://www.metanorma.org/]`", ...
````

which renders:

![Capture2](https://user-images.githubusercontent.com/33627611/111489846-e4a24b80-8710-11eb-8aff-e69c1952e326.PNG)

Files related:  [test.zip](https://github.com/metanorma/metanorma-standoc/files/6157403/test.zip)

**Comment by opoudjis** [comment]
First one has now been fixed, as a result of https://github.com/metanorma/metanorma-nist/issues/301

Second should be a quick fix: the smart quote detector skips `<index>...</index>` text as having non-rendered text, but needs to assume that `<xref>, <eref>, <link>` will in fact contain text, though they don't in Semantic XML.
