### ISSUE TITLE
Adoption documents support

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#458]
ISO STS documents (https://github.com/metanorma/mn-samples-bsi/tree/master/reference-docs) contain additional headers for adoption documents:
- `/standard/front/reg-meta` and 
- `/standard/front/nat-meta`.

For example:
- https://github.com/metanorma/mn-samples-bsi/tree/master/reference-docs/adoptions/bs-en-12973/30314082.xml 
contains only `reg-meta`
-  https://github.com/metanorma/mn-samples-bsi/tree/master/reference-docs/adoptions/bs-en-iso-56000/30421177.xml contains `iso-meta` (usual bibdata), `reg-meta` and `nat-meta`.

To convert such documents into Metanorma format we need to support this additional structures.

Source: https://github.com/metanorma/sts2mn/issues/18

**Comment by opoudjis** [comment]
There is currently support for this, as, `//bibdata/relation[@type = 'adoptedFrom']/bibitem`. Is that enough for your needs?

````
<bibdata>
...
<relation type='adoptedFrom'>
    <bibitem type='standard'>
      <fetched>2021-04-25</fetched>
      <title type='title-main' format='text/plain' language='en' script='Latn'>Codes for the representation of names of languages</title>
      <title type='title-part' format='text/plain' language='en' script='Latn'>Part 2: Alpha-3 code</title>
      <title type='main' format='text/plain' language='en' script='Latn'>
        Codes for the representation of names of
        languages&#8201;&#8212;&#8201;Part 2: Alpha-3 code
      </title>
      <title type='title-main' format='text/plain' language='fr' script='Latn'>Codes pour la repr&#233;sentation des noms de langue</title>
      <title type='title-part' format='text/plain' language='fr' script='Latn'>Partie 2: Code alpha-3</title>
      <title type='main' format='text/plain' language='fr' script='Latn'>
        Codes pour la repr&#233;sentation des noms de
        langue&#8201;&#8212;&#8201;Partie 2: Code alpha-3
      </title>
      <uri type='src'>https://www.iso.org/standard/4767.html</uri>
      <uri type='obp'>https://www.iso.org/obp/ui/#!iso:std:4767:en</uri>
      <uri type='rss'>https://www.iso.org/contents/data/standard/00/47/4767.detail.rss</uri>
      <docidentifier type='ISO'>ISO 639-2</docidentifier>
      <docidentifier type='URN'>urn:iso:std:iso:639:-2:stage-90.20:ed-1:en,fr</docidentifier>
      <docnumber>639</docnumber>
      <contributor>
        <role type='publisher'/>
        <organization>
          <name>International Organization for Standardization</name>
          <abbreviation>ISO</abbreviation>
          <uri>www.iso.org</uri>
        </organization>
      </contributor>
      <edition>1</edition>
      <language>en</language>
      <language>fr</language>
      <script>Latn</script>
      <status>
        <stage>90</stage>
        <substage>20</substage>
      </status>
      <copyright>
        <from>1998</from>
        <owner>
          <organization>
            <name>ISO</name>
          </organization>
        </owner>
      </copyright>
....
</relation>
...
</bibdata>
````

**Comment by ronaldtse** [comment]
@opoudjis there is a logical disconnect here though:

```xml
<document>
  <bibdata> 
    <...content...>
    <relation>... {adopted from} </relaton>
  </bibdata>
  <body>
    {adopted from document content}
  </body>
</document>
```

But the document itself contains the adopted document content. Shouldn't this be represented as:

```xml
<document>
  <outer wrapping>
  <bibdata> 
    <relation>... {adopted from} </relaton>
  </bibdata>
  <body>
    {outer document content}
  </body>
  </outer wrapping>
  <inner wrapping>
  <bibdata> 
    <...content...>
  </bibdata>
  <body>
    {adopted from document content}
  </body>
  </inner wrapping>
</document>
```

**Comment by opoudjis** [comment]
That looks like massive overkill. All @Intelligent2013 is asking for right now is metadata, right?

**Comment by ronaldtse** [comment]
Unless you consider an intro and foreword also part of metadata. 

In addition, some national adoptions contain full document translations.

**Comment by ronaldtse** [comment]
Here's a BS adoption of an EN adoption of an ISO, with associated pages. 

## Sample 1: BS EN ISO 19650-1

This is the preview from techstreet.com:
https://www.techstreet.com/sa/standards/bs-en-iso-19650-1-2018?product_id=2033334

BS cover

<img width="651" alt="Screenshot 2021-04-26 at 3 21 22 PM" src="https://user-images.githubusercontent.com/11865/116044359-66d44700-a6a3-11eb-9705-57554a68f175.png">

BS foreword
<img width="633" alt="Screenshot 2021-04-26 at 3 21 50 PM" src="https://user-images.githubusercontent.com/11865/116044363-6936a100-a6a3-11eb-8927-18f46d957894.png">

EN cover
<img width="655" alt="Screenshot 2021-04-26 at 3 22 00 PM" src="https://user-images.githubusercontent.com/11865/116044396-72c00900-a6a3-11eb-82e6-6b43b24a370f.png">

EN foreword
<img width="640" alt="Screenshot 2021-04-26 at 3 22 05 PM" src="https://user-images.githubusercontent.com/11865/116044414-7784bd00-a6a3-11eb-9918-8e60c444f8f0.png">

ISO TOC
<img width="626" alt="Screenshot 2021-04-26 at 3 24 42 PM" src="https://user-images.githubusercontent.com/11865/116044469-88cdc980-a6a3-11eb-9d85-88001fc1f32e.png">

ISO foreword
<img width="614" alt="Screenshot 2021-04-26 at 3 25 09 PM" src="https://user-images.githubusercontent.com/11865/116044512-984d1280-a6a3-11eb-871f-d3e8fd148832.png">


## Sample 2: BS ISO 30042

From BSI shop preview: https://shop.bsigroup.com/en/ProductDetail/?pid=000000000030338734&_ga=2.175787685.606339662.1619422050-1896932304.1618412432

BS cover
<img width="549" alt="Screenshot 2021-04-26 at 3 28 01 PM" src="https://user-images.githubusercontent.com/11865/116044863-00035d80-a6a4-11eb-86c0-0dc6cafba4cb.png">

BS foreword
<img width="504" alt="Screenshot 2021-04-26 at 3 28 14 PM" src="https://user-images.githubusercontent.com/11865/116044876-0691d500-a6a4-11eb-9c71-219e40e41cae.png">

ISO cover
<img width="483" alt="Screenshot 2021-04-26 at 3 28 32 PM" src="https://user-images.githubusercontent.com/11865/116044919-114c6a00-a6a4-11eb-8de7-73c8e1002f72.png">

ISO inner cover
<img width="471" alt="Screenshot 2021-04-26 at 3 28 48 PM" src="https://user-images.githubusercontent.com/11865/116044947-1ad5d200-a6a4-11eb-84c2-f2a5dba55a03.png">

ISO TOC
<img width="494" alt="Screenshot 2021-04-26 at 3 29 07 PM" src="https://user-images.githubusercontent.com/11865/116044986-26c19400-a6a4-11eb-9b40-26db27be0890.png">

BS back cover
<img width="639" alt="Screenshot 2021-04-26 at 3 18 47 PM" src="https://user-images.githubusercontent.com/11865/116043803-b403e900-a6a2-11eb-9e94-9f4d2149937e.png">

## Sample 3: EVS EN ISO 9001

EVS cover
<img width="588" alt="Screenshot 2021-04-26 at 3 32 16 PM" src="https://user-images.githubusercontent.com/11865/116045380-96378380-a6a4-11eb-985a-b09bb7efbcea.png">

EVS foreword
<img width="599" alt="Screenshot 2021-04-26 at 3 32 26 PM" src="https://user-images.githubusercontent.com/11865/116045408-9c2d6480-a6a4-11eb-90c4-8049d87ee1bb.png">

EN cover
<img width="572" alt="Screenshot 2021-04-26 at 3 32 45 PM" src="https://user-images.githubusercontent.com/11865/116045468-a8b1bd00-a6a4-11eb-9a61-5afe32e981ce.png">

EN foreword
<img width="572" alt="Screenshot 2021-04-26 at 3 33 11 PM" src="https://user-images.githubusercontent.com/11865/116045531-b6ffd900-a6a4-11eb-805c-54344569b59f.png">

ISO TOC
<img width="576" alt="Screenshot 2021-04-26 at 3 33 24 PM" src="https://user-images.githubusercontent.com/11865/116045577-bff0aa80-a6a4-11eb-89ef-4ea36006a86d.png">

## Sample 4: EVS EN ISO 14001

EVS cover
<img width="597" alt="Screenshot 2021-04-26 at 3 34 02 PM" src="https://user-images.githubusercontent.com/11865/116045676-d565d480-a6a4-11eb-8773-63d87b057fcf.png">

EVS foreword
<img width="593" alt="Screenshot 2021-04-26 at 3 34 19 PM" src="https://user-images.githubusercontent.com/11865/116045703-df87d300-a6a4-11eb-9796-31affd2b3623.png">

EN cover
<img width="587" alt="Screenshot 2021-04-26 at 3 34 29 PM" src="https://user-images.githubusercontent.com/11865/116045743-ea426800-a6a4-11eb-8822-1edaf64c396b.png">

Bilingual TOC
<img width="597" alt="Screenshot 2021-04-26 at 3 34 57 PM" src="https://user-images.githubusercontent.com/11865/116045788-f75f5700-a6a4-11eb-872c-f22a6001e352.png">

EN foreword
<img width="599" alt="Screenshot 2021-04-26 at 3 35 13 PM" src="https://user-images.githubusercontent.com/11865/116045813-ffb79200-a6a4-11eb-8866-4915bdb00bbd.png">

Content
<img width="593" alt="Screenshot 2021-04-26 at 3 35 37 PM" src="https://user-images.githubusercontent.com/11865/116045864-0e9e4480-a6a5-11eb-8010-d4a3277592c3.png">

Index (Estonian)
<img width="602" alt="Screenshot 2021-04-26 at 3 36 25 PM" src="https://user-images.githubusercontent.com/11865/116045966-2d9cd680-a6a5-11eb-8d31-8d8e41458d57.png">

Index (English)
<img width="606" alt="Screenshot 2021-04-26 at 3 36 42 PM" src="https://user-images.githubusercontent.com/11865/116045990-34c3e480-a6a5-11eb-8da3-d76720a3ffa0.png">

Empty page
<img width="598" alt="Screenshot 2021-04-26 at 3 36 54 PM" src="https://user-images.githubusercontent.com/11865/116046015-3beaf280-a6a5-11eb-923a-8fe0f2d449e9.png">

EVS back cover
<img width="599" alt="Screenshot 2021-04-26 at 3 37 03 PM" src="https://user-images.githubusercontent.com/11865/116046042-41e0d380-a6a5-11eb-8122-1c2fccf4a172.png">

**Comment by Intelligent2013** [comment]
> That looks like massive overkill. All @Intelligent2013 is asking for right now is metadata, right?

@opoudjis yes, I need Metanorma structures for representing `reg-meta` and `nat-meta` ISO STS data.

**Comment by opoudjis** [comment]
I'm not implementing any of this without an example document instance.

**Comment by opoudjis** [comment]
The rules are as following:

* Only make a distinction between `nat-meta`, `reg-meta`, `iso-meta` if `//bibdata/relation[@type = 'adopted-from']` exists. If not, then all information from `//bibdata` goes to the default metadata container (which I assume is `std-doc-meta`).
* If `//bibdata/relation[@type = 'adopted-from']` exists, `//bibdata` (ignoring all instances of `.//relation[@type = 'adopted-from']/bibitem`) is nat-meta: it is the national standards body's metadata (BSI being a national body)
* If `//bibdata//relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` exists, where xxx = ISO or IEC, then `//bibdata//relation[@type = 'adopted-from']/bibitem[contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']]` goes to iso-meta: it is the ISO (or IEC) metadata of a source document that this document is derived from (adopted from).
* If `//bibdata//relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` exists, where xxx = CEN or CENELEC, then `//bibdata//relation[@type = 'adopted-from']/bibitem[contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']]` goes to reg-meta: it is the metadata of a regional organisation source document that this document is derived from (adopted from). (CEN is the European region counterpart to ISO, CENELEC the European region counterpart to IEC.)
* If BSI ever adopts a standard from a body other than the four I have named, `std-meta` should be used for that body's metadata instead: the tag `iso-meta` is only intended for ISO-like metadata, and `reg-meta` is reserved for regional affiliates of ISO.
