### ISSUE TITLE
Support EMF (Enhanced MetaFile) graphic format

### ISSUE THREAD

**Issue by w00lf** [metanorma/metanorma-standoc#460]
Image macro when used with `emf` image does not get rendered as SVG.

Example of emf file: https://github.com/metanorma/ogc-dggs-xmi/blob/master/xmi-19170-only/Images/EAID_0F7609F1_8B3C_42c2_BCF9_373CAC4CDF97.emf. When used with `image` macro the rendered result displays the blank image:

![image](https://user-images.githubusercontent.com/1158036/115765415-668c3100-a3af-11eb-991e-c064179c4dfb.png)

**Comment by ronaldtse** [comment]
I have tried many EMF converters and most don't really work. In addition, it seems that the EMF files produced by SparxSystems' Enterprise Architect are *borked*.

From: https://github.com/metanorma/ogc-dggs-xmi/issues/17

I've got some interesting findings. The EMF files that Enterprise Architect generates are broken -- they cannot be read by Inkscape, Microsoft Word, and LibreOffice.

## Direct export from Enterprise Architect

To PNG (ID: EAID_2C9EA425_800E_4c1d_8711_80D46838EB11):

![EAID_2C9EA425_800E_4c1d_8711_80D46838EB11](https://user-images.githubusercontent.com/11865/115824395-700eab00-a43a-11eb-9894-179f9f3ea18e.png)


## Inkscape

```sh
$ inkscape EAID_0F7609F1_8B3C_42c2_BCF9_373CAC4CDF97.emf --export-plain-svg x.svg

Emergency save activated!
Emergency save completed. Inkscape will close now.
If you can reproduce this crash, please file a bug at https://inkscape.org/report
with a detailed description of the steps leading to the crash, so we can fix it.
** Message: 13:46:41.414: Error: Inkscape encountered an internal error and will close now.

Segmentation fault: 11
```

## LibreOffice

Which is said to be the best EMF reader on macOS.

```sh
$ soffice --headless --convert-to png EAID_0F7609F1_8B3C_42c2_BCF9_373CAC4CDF97.emf 
convert /Users/me/src/mn/ogc-dggs-xmi/xmi-19170-only/Images/EAID_0F7609F1_8B3C_42c2_BCF9_373CAC4CDF97.emf -> 
  /Users/me/src/mn/ogc-dggs-xmi/xmi-19170-only/Images/EAID_0F7609F1_8B3C_42c2_BCF9_373CAC4CDF97.png using filter : draw_png_Export
```

Works, but:
![EAID_0F7609F1_8B3C_42c2_BCF9_373CAC4CDF97](https://user-images.githubusercontent.com/11865/115824503-9896a500-a43a-11eb-94f0-9b8d3469d9e9.png)


## Microsoft Word

Drag and drop into Word which supports EMF.

<img width="1039" alt="Screenshot 2021-04-23 at 1 49 01 PM" src="https://user-images.githubusercontent.com/11865/115824548-ab10de80-a43a-11eb-8dc3-7cdaf1d00bc8.png">


## Others

I've also tried `unoconv`, which depends on LibreOffice, and will crash on this file.

## libqemf

It renders the image, but the text placement is wrong. It is published with GPL3, but it uses Qt which I don't know how easy it is to fix.
https://sourceforge.net/projects/libqemf/

<img width="1112" alt="Screenshot 2021-06-21 at 4 28 27 PM" src="https://user-images.githubusercontent.com/11865/122731318-bdc65900-d2ad-11eb-89df-f0ca742acc26.png">


## Moving ahead

The only reasonable EMF reader I found was this:
https://github.com/kakwa/libemf2svg

It properly converts normal EMF files (including those from ISO 10303 STEPmod), but it crashes on these particular files.

I suggest that we fix this library to see whether we can render these images.

**Comment by ronaldtse** [comment]
We're continuing this at metanorma/libemf2svg#1 .

**Comment by ronaldtse** [comment]
Now at metanorma/libemf2svg#5

**Comment by ronaldtse** [comment]
This will be fixed here: https://github.com/metanorma/libemf2svg/issues/14

**Comment by ronaldtse** [comment]
The Ruby gem emf2svg is now available at https://github.com/metanorma/emf2svg-ruby . This task is now live.

The work to be done here is to integrate into Metanorma the image file conversion from `*.emf` to `*.svg`.

**Comment by opoudjis** [comment]
@Intelligent2013 We have an issue now that Word prefers EMF files, and HTML and PDF prefer SVG. If I find an EMF file in source, I'd rather not convert it to SVG in Presentation XML, and then convert to EMF again for Word: the round trip conversion may be lossy. Instead, I'd like to mark up images in Presentation XML to contain both svg and emf, so that Word can pick the latter, and HTML and PDF can pick the former.

**Comment by Intelligent2013** [comment]
> I'd like to mark up images in Presentation XML to contain both svg and emf, so that Word can pick the latter, and HTML and PDF can pick the former

@opoudjis ok, no problem, then xslt will just ignore the element `emf`, and display `svg` as currently.

**Comment by opoudjis** [comment]
efm2svg is forcing update to Nokogiri 1.12

**Comment by ronaldtse** [comment]
> Instead, I'd like to mark up images in Presentation XML to contain both svg and emf, so that Word can pick the latter, and HTML and PDF can pick the former.

Agree and good solution, thanks.

**Comment by opoudjis** [comment]
@Intelligent2013 

Henceforth, any svg in the PresentationXML will be marked up as `<image><svg/><emf/></image>` for this reason. So:

````
                <image id='_d3731866-1a07-435a-a6c2-1acd41023a4e' src='' mimetype='image/svg+xml' height='auto' width='auto'>
                 <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'>
                   <circle fill='#009' r='45' cx='50' cy='50'/>
                   <path d='M33,26H78A37,37,0,0,1,33,83V57H59V43H33Z' fill='#FFF'/>
                 </svg>
                 <emf src='data:application/x-msmetafile;base64,AQAAAPgAAAAAAAAAAAAAAPsEAAD7BAAAAAAAAAAAAACLCgAAiwoAACBFTUYAAAEAVAQAACgAAAACAAAARgAAAGwAAAAAAAAA3ScAAH0zAADYAAAAFwEAAAAAAAAAAAAAAAAAAMBLAwDYQQQASQBuAGsAcwBjAGEAcABlACAAMQAuADEAIAAoAGMANABlADgAZgA5AGUALAAgADIAMAAyADEALQAwADUALQAyADQAKQAgAAAAaQBtAGEAZwBlADIAMAAyADEAMAA5ADIANQAtADMANQAzADAAOAAtADEAaAA2AG8AeABmAGYALgBlAG0AZgAAAAAAAAARAAAADAAAAAEAAAAkAAAAJAAAAAAAgD8AAAAAAAAAAAAAgD8AAAAAAAAAAAIAAABGAAAALAAAACAAAABTY3JlZW49MTAyMDV4MTMxODFweCwgMjE2eDI3OW1tAEYAAAAwAAAAIwAAAERyYXdpbmc9MTAwLjB4MTAwLjBweCwgMjYuNXgyNi41bW0AABIAAAAMAAAAAQAAABMAAAAMAAAAAgAAABYAAAAMAAAAGAAAABgAAAAMAAAAAAAAABQAAAAMAAAADQAAACcAAAAYAAAAAQAAAAAAAAAAAJkABgAAACUAAAAMAAAAAQAAADsAAAAIAAAAGwAAABAAAACkBAAAcQIAAAUAAAA0AAAAAAAAAAAAAAD//////////wMAAACkBAAAqAMAAKgDAACkBAAAcQIAAKQEAAAFAAAANAAAAAAAAAAAAAAA//////////8DAAAAOgEAAKQEAAA/AAAAqAMAAD8AAABxAgAABQAAADQAAAAAAAAAAAAAAP//////////AwAAAD8AAAA6AQAAOgEAAD8AAABxAgAAPwAAAAUAAAA0AAAAAAAAAAAAAAD//////////wMAAACoAwAAPwAAAKQEAAA6AQAApAQAAHECAAA9AAAACAAAADwAAAAIAAAAPgAAABgAAAAAAAAAAAAAAP//////////JQAAAAwAAAAFAACAKAAAAAwAAAABAAAAJwAAABgAAAABAAAAAAAAAP///wAGAAAAJQAAAAwAAAABAAAAOwAAAAgAAAAbAAAAEAAAAJ0BAABFAQAANgAAABAAAADPAwAARQEAAAUAAAA0AAAAAAAAAAAAAAD//////////wMAAABfBAAA7QEAAGQEAADjAgAA2wMAAJEDAAAFAAAANAAAAAAAAAAAAAAA//////////8DAAAAUgMAAD4EAABhAgAAcwQAAJ0BAAAOBAAANgAAABAAAACdAQAAyQIAADYAAAAQAAAA4gIAAMkCAAA2AAAAEAAAAOICAAAaAgAANgAAABAAAACdAQAAGgIAAD0AAAAIAAAAPAAAAAgAAAA+AAAAGAAAAAAAAAAAAAAA//////////8lAAAADAAAAAUAAIAoAAAADAAAAAEAAAAOAAAAFAAAAAAAAAAAAAAAVAQAAA=='/>
               </image>
````

Please replace any instances of `//img[svg]` with `svg` in the XML you receive, to get the same results as before.

**Comment by Intelligent2013** [comment]
@opoudjis done.
