### ISSUE TITLE
Support smart terms references in normal content

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#468]
In ISOSTS documents they have a `<named-content>` tag used in normal content like this:

```xml
activities of <named-content content-type="term" xlink:href="#term_3.19">organizations</named-content>.
```

sts2mn currently converts this to:
```adoc
activities of <<term-organization,organizations>>.
```
(notice the pluralisation) (see https://github.com/metanorma/bs-202000/pull/5)

This is clearly our "smart terms reference" and should be encoded as:
```
activities of term:[organizations,organization].
```

However, since the "smart terms reference" functionality was originally only used in Clause 3 (and in SMRL), the formatting goes like this: "_italicized term_ (3.11)".

(how it looks now)
<img width="863" alt="Screenshot 2021-05-07 at 12 48 01 AM" src="https://user-images.githubusercontent.com/11865/117335580-e34dfd80-aecd-11eb-94e7-2f1fe509e790.png">

In this case, we don't want italicisation and we don't want the clause number.

We have two options:
1. Implement a different macro that has no italicisation and no clause number, such as `terml:[]` (term link) or `ter:[]` (term without the m)
2. By default, `term:[]` italicises and provides a clause number if in a terminology clause (also consider the case of an ISO vocabulary document), but when outside a terminology clause, it defaults to no italicisation and no clause number.

Even if we do 2, we might also want to do 1.

Thoughts @opoudjis ?

**Comment by opoudjis** [comment]
I am not going to implement a distinct macro, and pointlessly proliferate code for every truculent piece of inconsistency an SDO can elect to befoul its style with. Nor am I going to implement business rules like (2), formulated by the same SDOs who are so incapable of sticking to their own citation style, and who therefore cannot be trusted to stick by any such business rule either. 

If the rendering is to be different for a concept, then that shall be an added argument to the concept macro, taking the form of a percent argument, as we have done elsewhere:

`{{organization,organizations,%noital,%noclausenum}}`

**Comment by ronaldtse** [comment]
Following up on our discussion, we will use `{{term, render, options="foo, bar"}}`.

**Comment by opoudjis** [comment]
Hence: `options="noital,noref"`

**Comment by ronaldtse** [comment]
Are you saying that this syntax:
```
{{<<IEV:171-05-02>>,immature kernel,option="noital,noref"}}
```

Is required for content in the document outside of the T&D section? Because this will be very cumbersome.

As you can imagine, there are a lot more terms in content vs in T&D.

**Comment by opoudjis** [comment]
Not at all, the ISO options will override these.

Am switching the options to include explicit ital, ref, as well, since we will also want to assert that there should be italics or references when by default there isn't.

**Comment by ronaldtse** [comment]
> Am switching the options to include explicit ital, ref, as well, since we will also want to assert that there should be italics or references when by default there isn't.

Thank you -- this is a sane addition. I wonder if the `noital` stuff can be generalised as `!{option name}` or `no{option name}`.

**Comment by opoudjis** [comment]
Generalising no as prefix is fine
