### ISSUE TITLE
Extracted source code with filenames

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#47]
@opoudjis given that we can extract source code now (#42), it might make sense to have the input document also provide an output filename for extraction.

Currently the extracted source code has no file extension. We probably should allow the user to enter a filename for each piece of source code.

In fact, this should be the approach for MRR as well.

**Comment by opoudjis** [comment]
Documented in metanorma.com under author/topics/document-format/text.adoc
