### ISSUE TITLE
Stray whitespaces all over XML in new version

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#48]
These stray whitespaces should not exist. While they don't affect the eventual presentation output, they pollute the canonical format, and trigger lots of highlighting by text editors (and GitHub).

Key point is they did not exist in a very recent version, this issue is a regression.

Document attributes:
<img width="330" alt="Screen Shot 2019-03-16 at 7 50 16 PM" src="https://user-images.githubusercontent.com/11865/54474845-fd777e00-4824-11e9-8148-4c644d2e674e.png">

Version (one of the examples):
<img width="399" alt="Screen Shot 2019-03-16 at 7 50 02 PM" src="https://user-images.githubusercontent.com/11865/54474840-f81a3380-4824-11e9-9151-18a488d00bd1.png">

Actual text:
<img width="625" alt="Screen Shot 2019-03-16 at 7 50 31 PM" src="https://user-images.githubusercontent.com/11865/54474848-023c3200-4825-11e9-9376-5de2426604b4.png">

**Comment by opoudjis** [comment]
This is in the aftermath of https://github.com/metanorma/metanorma-standoc/issues/39 (modified by https://github.com/metanorma/metanorma-standoc/issues/43), and that was a bug. You will see that I struggled for the next 10 days to come up with an acceptable solution:

* https://github.com/metanorma/metanorma-standoc/commit/488e3cfd68066df4305c72a6dac511a43bccc9a9#diff-be77a66b6aa29ad95cca1942dcddda8a
* https://github.com/metanorma/metanorma-standoc/commit/ebf5f4a22563462af0bb4636368a0f503b27cabc#diff-be77a66b6aa29ad95cca1942dcddda8a
* https://github.com/metanorma/metanorma-standoc/commit/7cd744f0562676ae0e55ae0610c5e43ec417cd26#diff-be77a66b6aa29ad95cca1942dcddda8a
* https://github.com/metanorma/metanorma-standoc/commit/4e3da075f84fb25c19cad69b6e8f9ab54ea1a5fb#diff-be77a66b6aa29ad95cca1942dcddda8a

**Comment by opoudjis** [comment]
Removed end-of-line spaces in postprocessing; works, and does not impact the fix to #39.
