### ISSUE TITLE
Eliminate duplicate ids in nested bibitem

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#482]
From https://github.com/relaton/relaton-ietf/issues/24

> The message Bibliography: ERROR: No title retrieved for IETF BCP 47 isn't actually an error. It is a warning and seems it comes from metanorma. In fact, the "BCP 47" is a composition of 2 documents: "RFC 4647" and "RFC 5646". The composition doesn't have its own title.
> The crash is caused by document duplicating:

>> Anchors: (XML Line 000324): Anchor RFC5646 has already been used at line 324
>> Error: multiple instances of same ID
> It says that document "RFC 5646" is duplicated in concatenation. Please check your sources for this duplication.

> So I cannot refer to BCP 47 (the whole) and RFC 5646 (the single RFC) in the same document?

If IETF BCP 47 citation includes IETF RFC 5646, and both top level and nested instances of IETF RFC 5646 have the same anchor, that will result in a duplicate id error. In fact, that error should have been eliminated already, by removing the ids of nested bibitem//bibitem instances within Metanorma: this has come up before.

**Comment by opoudjis** [comment]
Ok, fixed, @ryzokuken . Next release is in two weeks; if you want to use this before then, add to your Gemfile (once I've finished running GitHub Actions):

````
gem "metanorma-standoc, git: "https://github.com/metanorma/metanorma-standoc"
````

**Comment by ryzokuken** [comment]
@opoudjis will do.

**Comment by ryzokuken** [comment]
still seeing this error on 1.10.0 @opoudjis

**Comment by ronaldtse** [comment]
Reopening. Sorry @ryzokuken about this. @opoudjis could you help check? Thanks.

**Comment by ryzokuken** [comment]
No worries @ronaldtse, hope we @opoudjis can figure out what's wrong :smile:

**Comment by opoudjis** [comment]
The error is eliminated in the standoc gem, but there is a routine in metanorma-ietf that was putting it right back in. Fixed.

You will need to 

````
gem "metanorma-ietf, git: "https://github.com/metanorma/metanorma-ietf"
````

until next Monday.
