### ISSUE TITLE
Support EPS image format

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#484]
Somehow, I thought we did but apparently we don't.

Metanorma should support the EPS image format. ISOSTS files often come with EPS content and we need to support EPS.

This can be done using Inkscape to convert the EPS to (SVG + EMF).

Command:
```sh
inkscape --export-plain-svg image.eps -o image.svg
```

**Comment by ronaldtse** [comment]
The converted SVGs can sometimes be even larger than EPS. We may want to minimise them.

I've tried both SVGO and Scour. SVGO works for smaller files but it hung on an 18MB file. [Scour](https://github.com/scour-project/scour) worked for all in reasonable time.

**Comment by opoudjis** [comment]
EMF is converted to SVG in Presentation XML. The same will be done for EPS.

**Comment by opoudjis** [comment]
No scour for now

**Comment by ronaldtse** [comment]
There is a partial SVGO port in Ruby https://github.com/fnando/svg_optimizer , but the performance from this image was dismal compared with the original:
![original](https://user-images.githubusercontent.com/11865/184548036-ad7331ae-b9cc-425f-b16c-d8a0d6c8f3ef.svg)

```
215K original.svg
196K optimized-svg_optimizer.svg
 26K optimized-svgo.svg
```
