### ISSUE TITLE
Extend terms:() macro to abbreviations/symbols

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#488]
Requested functionality in https://github.com/metanorma/metanorma-bsi/issues/37 is that terms:[] macro apply to definitions as well as terms. This may or may not be appropriate...

**Comment by opoudjis** [comment]
Because of possibility of a term and a symbol/abbreviation being the same string, we will provide a distinct macro, `symbol:[]`. We use symbol rather than abbrev as a more generic expression.

**Comment by ronaldtse** [comment]
Thank you!
