### ISSUE TITLE
Getting latexmlmath to work in travis

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#49]
Can't get it to, the .travis test involving latexmlmath for metanorma-standoc is failing. I have made travis do a apt-get of latexml, but that does not seem to have any impact. I am trying to test whether latexmlmath is installed at all, but I can't get anything meaningful to output to stderr or stdout!

@CAMOBAP795  ... You seem to know what you're doing with testing latexml; could you help here?

**Comment by CAMOBAP795** [comment]
@opoudjis let me have a look

**Comment by ronaldtse** [comment]
@camobap795 and we need to update the metanorma Linux installation script too.

**Comment by CAMOBAP795** [comment]
> and we need to update the metanorma Linux installation script too.

Ok, https://github.com/metanorma/metanorma-linux-setup/issues/3 reported 

@ronaldtse @opoudjis how do you think maybe better distribute deb/rpm packages instead https://github.com/metanorma/metanorma-linux-setup ?

**Comment by ronaldtse** [comment]
It will be very difficult to do so because many dependent packages are not available in rpm/deb. Eg. LaTeXML and puppeteer. If you can find a way to do so, please go ahead. 

Can you also update the Linux script for LaTeXML? Thanks!

**Comment by CAMOBAP795** [comment]
> Can you also update the Linux script for LaTeXML? Thanks!

Yes sure

**Comment by CAMOBAP795** [comment]
For me test works locally too, but no CI I see
```
Fatal:missing_file:amsmath Couldn't find amsmath to preload at /usr/share/perl5/LaTeXML/Global.pm line 207, <> line 1.
```

Investigation in progress

**Comment by CAMOBAP795** [comment]
I have replaced `sudo apt-get install -y latexml` with 
```
sudo apt-get install -y cpanminus
cpanm LaTeXML@0.8.2
export PATH=~/perl5/bin:$PATH
which latexml
```

Test still fails https://travis-ci.org/metanorma/metanorma-standoc/jobs/507519767 investigation in progress

@opoudjis which version of latexml you are using locally?

**Comment by CAMOBAP795** [comment]
I have found solution:

```
curl -L http://cpanmin.us | perl - App::cpanminus
cpanm LaTeXML@0.8.2
```

with `--sudo` arg to install it on system level, waiting for CI

**Comment by CAMOBAP795** [comment]
@opoudjis @ronaldtse two PRs ready for review:
 - https://github.com/metanorma/metanorma-linux-setup/pull/5
 - https://github.com/metanorma/metanorma-standoc/pull/50
