### ISSUE TITLE
Terms mention

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#491]
Currently, the `term:[name,name2]` macro is temporarily mapped to `<em>name</em> (<termxref>name2</termxref>)`, and ultimately (after the term is looked up) mapped to `<em>name</em> (<xref target="term-name2"/>)`

That is the desired rendering of the macro; but the intent was to capture the fact that this is a term *mention*, so that it can be treated differentially to other cross-references (in particular, allowing loading of the term definition).

So, I am going to introduce a `<mention>` tag in the Semantic XML for these instances, since they are tracking mentions of a semantic element. We will need to make the mention able to cope with both terms and symbols/abbreviations (https://github.com/metanorma/metanorma-standoc/issues/488). And we need the Presentation XML counterpart to this tag able to differentiate symbol and term references: they are both rendered differently, and annotated differently.

So: `term:[name,name2]` is mapped to `<termxref target="name2">name</termxref>`, internally, and is output as `<mention type="term" target="term-name2">name</mention>` in Semantic XML.

This in turn is mapped in Presentation XML to `<em>name</em>  (<xref target="term-name2" type="term-mention"/>)` to `<em>name</em>  (<xref target="term-name2" type="term-mention">{clause of term-name2}</xref>)`. And downstream HTML (I assume) can do whatever it needs to do with xrefs of type "term-mention".

**Comment by opoudjis** [comment]
In fact, we already have term mention, as `concept`. So I need to work out the overlap between the existing concept markup, and the term macro, and allow the rendering of concept to fall in line with that of current term:[].

**Comment by opoudjis** [comment]
Concept currently has the text to be displayed as an attribute. It should be an element, given that it can contain markup.

**Comment by opoudjis** [comment]
We will get rid of the distinct term:[] macro. Instead, we will support the following syntax for concepts:

* {{<<id>>,term}}
* {{<<id>>,term,text}}
* {{termbase:id,term}}
* {{termbase:id,term,text}}
* {{term}}
* {{term,text}}

This will be a breaking change, major version of standoc and isodoc.

The term:[] rendering currently in metanorma-iso will become the rendering of `<concept>`.

**Comment by opoudjis** [comment]
I am disinclined to get rid of term:[], I don't want to break things if I can avoid it. I'll keep it as equivalent to {{term}}, {{term,text}}.

**Comment by opoudjis** [comment]
Concept will be modified as follows:

1. The ID will contain the localities for erefs, and will always be in `<<>>`, including for termbases. So, `<<xref>>`, ``<<eref>>`, `<<eref,locality=value,locality=value>>`, `<<termbase:id>>`. This will involve overriding the asciidoc macro parser, and doing our own parsing of arguments, since Asciidoc breaks up arguments at the first comma it sees
2. We will introduce a separate `concept/renderterm` argument, rather than embed the rendering of the term inside the crossreference element, since the content of the crossreference should be used instead to present the crossreference differently
3. For consistency, I need to ensure refterm and renderterm are always populated
4. In anticipation of https://github.com/metanorma/metanorma-standoc/issues/468, we will introduce options arguments to the macro, to control rendering
5. The Macro them becomes: `{{<<ID>>?,term,rendering?,crossreference-rendering?,options="..."?}}`
6. Execution should abort if the internal target of `<<ID>>` is not a term (or acronym/symbol, when I get to https://github.com/metanorma/metanorma-standoc/issues/488
7. I am to write a blog post, explaining inter alia the reversal of the `term:[rendering,term]` arguments

**Comment by ronaldtse** [comment]
Agreed, thanks @opoudjis.

**Comment by opoudjis** [comment]
Done 1,2,3,4,5. To go: 6,7, isodoc and metanorma-iso rendering.

**Comment by ronaldtse** [comment]
Just FYI that https://github.com/metanorma/bs-202000/issues/3 will have issues solved once this is done.

**Comment by opoudjis** [comment]
If cross-reference text is supplied, it overrides "term defined in %" boilerplate text, not just the % component: `{{term,text,ibid.}}` should be rendered as 

> _text_ [ibid.]

not

> _text_ [term defined in ibid.]

**Comment by opoudjis** [comment]
And termref content must be rendered, if present.

**Comment by opoudjis** [comment]
Blog post created
