### ISSUE TITLE
Switch to using mnconvert instead of mn2sts and sts2mn

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#492]
mnconvert (https://github.com/metanorma/mnconvert) is the successor of mn2sts and sts2mn, where it combines functionality of both in the same package. 

Ongoing improvements to these functions will only be done in the new mnconvert. 

This ticket is to replace the two now deprecated tools with mnconvert. 

This work is dependent on the creation of the corresponding gem for mnconvert. https://github.com/metanorma/mnconvert/issues/16

**Comment by ronaldtse** [comment]
@opoudjis current, but needs to wait for @CAMOBAP for the wrapper.

**Comment by opoudjis** [comment]
Which means it isn't current, it's blocked.
