### ISSUE TITLE
`keep-separate` not working when a table precedes a NOTE block (NOTE not kept separate)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#520]
From @opoudjis :

> Notes that are not at the end of a clause are folded into the preceding block, if that block is not delimited (so that the user could not choose to include or exclude a note). That is, notes are folded into a preceding list, formula, or figure.
> 
> To prevent that behaviour, add the attribute keep-separate to the note [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.29].

Unfortunately that method is not working when the preceding block is a table where the NOTE block follows.

e.g.

```adoc
[cols="2,6",options="headers"]
|===
| Class | Description
|<<AbstractLogicalSpace-section,AbstractLogicalSpace>> 
...
|===

[.keep-separate]
NOTE: This should not be folded into the table.
```

**Comment by opoudjis** [comment]
It's

````
[NOTE,keep-separate=true]
====
This should not be folded into the table.
====
````

Implementing now.
