### ISSUE TITLE
Term source linking to URI should display in capital letters "URI" not "Uri"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#526]
From https://github.com/metanorma/ogc-citygml-xmi/pull/70:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/11865/132445273-795e85d6-7284-46be-a591-7b9b7a0b7995.png">

**Comment by opoudjis** [comment]
That's been anticipated, but you need to pull isodoc and metanorma-utils as well. Please confirm.

**Comment by ronaldtse** [comment]
Confirm fixed. Thanks @opoudjis !

<img width="977" alt="Screenshot 2021-09-09 at 8 34 01 AM" src="https://user-images.githubusercontent.com/11865/132603298-ca357434-d171-427b-a673-28273e40f6ec.png">
