### ISSUE TITLE
AsciiMath in presentation XML for BIPM SI Brochure

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#528]
Source: https://github.com/metanorma/metanorma-standoc/issues/507

@opoudjis how can I enable AsciiMath generation in the comments for BIPM brochure?
xml generated  by `bundle exec metanorma -t bipm -x presentation sources/si-brochure-en.adoc` doesn't contain comments in math.

AsciiMath generation in the comments working, in principle, for some cases. For example, for BSI documents, if source adoc contains MathML like this:
```adoc
[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML" id="mml_m1">
<mrow>
<msub>
<mi>P</mi>
...
```
then resulted metanorma xml contains AsciiMath in the comment after mathml:
```xml
...</math><!-- P_t + P_c = [ ( C_((dev)) + C_((mkt)) ) // Q_((at)) ] + C_((mat)) + C_((ma)) + C_((de)) --></stem>
```

gem current versions:
    metanorma-standoc (1.10.5),
    metanorma-bipm (1.1.8)

**Comment by opoudjis** [comment]
Omission particular to BIPM (which has its own approach to generating math expressions): fixed.
