### ISSUE TITLE
Root path should be based on original path that had `include` directive

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#54]
In https://github.com/riboseinc/iso-geodetic-register-docs , the compilation (`make`) fails because:

* the main `iso-geodetic-register-guide.adoc` document is under `sources/`
* it includes files from `sources/sections` via `include::sections/xxx.adoc`

This command throws an error:
```sh
bundle exec metanorma sources/iso-geodetic-register-guide.adoc
```

Error:
```
asciidoctor: ERROR: iso-geodetic-register-guide.adoc: line 32: include file not found: /.../iso-geodetic-register-docs/sections/00-foreword.adoc
asciidoctor: ERROR: iso-geodetic-register-guide.adoc: line 33: include file not found: /.../iso-geodetic-register-docs/sections/00-intro.adoc
...
...
```

**Comment by opoudjis** [comment]
This is an abuse of how asciidoctor works, and it can only be addressed by manipulating the asciidoctor source in metanorma-cli.
