### ISSUE TITLE
Missing terms references (in the different sections)

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#542]
Source: https://github.com/metanorma/mnconvert/issues/79#issuecomment-938975648

From: https://github.com/metanorma/mnconvert/issues/79#issuecomment-939066397
> yes it is only the first instance that will become a link, but it is the first instance in a section. If a term is referenced once in 3.7 and once in 3.12, both instances should have been linked.

Source STS pdf: https://github.com/metanorma/mn-samples-bsi/blob/master/reference-docs/standards/bs-202000/BS-202000.pdf

Adoc: https://github.com/metanorma/mn-samples-bsi/blob/master/sources.mnconvert/standards/bs-202000/sections/03-terms.adoc

In `03-terms.adoc` there are a few references to the 'organization' term - {{organization}}:
```
=== audit
...
NOTE: An internal audit is conducted by the organization ({{organization}}), or by an external party on its behalf.
...
=== continual improvement
...
NOTE: Enhancing performance relates to the use of the standardization management system ({{standardization management system (SMS)}}) to enhance standardization performance ({{performance}}) consistent with the organization’s ({{organization}}) standardization management policy ({{standardization management policy}}).
...
=== documented information

information required to be controlled and maintained by an organization (see {{organization}}) and the medium on which it is contained
...
=== interested parties

person or organization (see {{organization}}) that can affect, be affected by, or perceive itself to be affected by a decision or activity
...

```

but in the generated presentation xml there is only one reference to 'organization' - in the first instance (in the section for term 'audit'):
```xml
<term id="term-audit">
	<name>3.2</name>
	<preferred>audit</preferred>
...
	<termnote id="_">
		<name>NOTE  3</name>
		<p id="_">An internal audit is conducted by the organization (<em>organization</em> (<xref target="term-organization">
				<strong>3.19</strong>
			</xref>)), or by an external party on its behalf.</p>
	</termnote>
	...
<term id="term-continual-improvement">
	<name>3.6</name>
	<preferred>continual improvement</preferred>
	...
	<termnote id="_">
		<name>NOTE  1</name>
		<p id="_">Enhancing performance relates to the use of the standardization management system (<em>standardization management system (SMS)</em> (<xref target="term-standardization-management-system-_sms_">
				<strong>3.30</strong>
			</xref>)) to enhance standardization performance (<em>performance</em> (<xref target="term-performance">
				<strong>3.20</strong>
			</xref>)) consistent with the organization&#8217;s (organization) standardization management policy (<em>standardization management policy</em> (<xref target="term-standardization-management-policy">
				<strong>3.29</strong>
			</xref>)).</p>
	</termnote>
	...
<term id="term-documented-information">
	<name>3.7</name>
	<preferred>documented information</preferred>
	<definition>
		<p id="_">information required to be controlled and maintained by an organization (see organization) and the medium on which it is contained</p>
	</definition>
```

**Comment by opoudjis** [comment]
I had misunderstood the wording in 

https://github.com/metanorma/metanorma-iso/issues/517

> In terms and definitions clauses, only the "first mention" of a term should be formatted as "my term (1.1.1)", subsequent mentions are to be rendered as normal.

to mean an entire terms and definitions clause. What was actually meant was a single term entry (which we have already established is not a clause at all!): https://www.iso.org/ISO-house-style.html

> To cross-reference another term listed in Clause 3 as part of a terminological entry, put the referenced term in italics with its reference number given in brackets afterwards. The term number will become a hyperlink in the XML-processed PDF document. Do this for the first usage only within each terminological entry – there is no need to repeat the cross-reference formatting multiple times within each entry.
