### ISSUE TITLE
Index terms processing messing with cross-reference terms

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#550]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

Terms that include index terms do not render properly:

From *bs-0*:

![issue3-generated](https://user-images.githubusercontent.com/33627611/138360335-16961f84-7c99-43ab-ae87-c8f8acf62d43.PNG)

````
== Terms and definitions

=== consumer(((consumer, definition)))
...

=== regulation(((regulation)))
...

=== expert(((experts)))
...

=== committee(((committees, definition)))
...

=== consensus(((consensus, definition)))
...

````

**Comment by Intelligent2013** [comment]
Another example (https://github.com/metanorma/mn-samples-bsi/blob/main/sources.mnconvert/adoptions/bs-en-iso-56000/sections/03-terms.adoc):
adoc
```
==== ((entity))

...
```
in metanorma xml, term's id contains `entity` prefix from bookmark after `term-entity`:
```xml
<term id="term-entityentity"><name>3.2.5</name><preferred>entity<bookmark id="_"/></preferred>
```

**Comment by Intelligent2013** [comment]
@opoudjis thanks!
