### ISSUE TITLE
Handling smallcap in the middle of word

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#556]
Source: https://github.com/metanorma/mnconvert/issues/93

Adoc:
```adoc
* [[[ref_16,15]]] I[smallcap]#nternational# T[smallcap]#est# C[smallcap]#ommission#(2017). The ITC Guidelines for Translating and Adapting Tests (Second edition). http://www.intestcom.org[www.intestcom.org]
```

Metanorma xml contains `[smallcap]` instead of xml tags `<smallcap>`:
```xml
<formattedref format="application/x-isodoc+xml">I[smallcap]nternational T[smallcap]est C[smallcap]ommission(2017). The ITC Guidelines for Translating and Adapting Tests (Second edition). <link target="http://www.intestcom.org">www.intestcom.org</link>
</formattedref>
```

**Comment by opoudjis** [comment]
Good news and better news.

Good news, although this isn't actually documented properly, if you use double ##, the markup will be recognised mid-word, as is the case for other unconstrained inline markup (`text__text__text`, `text**text**text`). So `I[smallcap]##nternational##` works.

Better news: just use `[smallcap]#International#`. smallcap only applies to lowercase letters: the smallcap of a capital letter is still capital.

**Comment by Intelligent2013** [comment]
@opoudjis thanks.
