### ISSUE TITLE
Handling localities with custom cross-reference text

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#557]
Source: https://github.com/metanorma/mnconvert/issues/94

From https://www.metanorma.org/author/topics/document-format/bibliography/#localities:
> Any text after the bibliographic localities is still treated as custom cross-reference text; for example:
```adoc
<<ISO7301,clause=5,table=1,the foregoing reference>>
```

I've tried these cases:
### TC1 (OK). without any text, localities only:
```adoc
Test1: <<ref_3,clause=5,table=1>>.
```
generated metanorma xml contains pre-rendered localities `Clause <strong> 5</strong>, Table  1`:
```xml
<p id="_">Test1: <eref type="inline" bibitemid="ref_3" citeas="[27]">
<localityStack>
	<locality type="clause">
		<referenceFrom>5</referenceFrom>
	</locality>
	<locality type="table">
		<referenceFrom>1</referenceFrom>
	</locality>
</localityStack>[27], Clause <strong> 5</strong>, Table  1</eref>.</p>
```
### TC2 (NOT OK). with custom cross-reference text
```adoc
Test2: <<ref_3,clause=5,table=1,the foregoing reference>>.
```

generated metanorma xml doesn't contain pre-rendered localities, there is the text `the foregoing reference` only:
```xml
<p id="_">Test2: <eref type="inline" bibitemid="ref_3" citeas="[27]">
<localityStack>
	<locality type="clause">
		<referenceFrom>5</referenceFrom>
	</locality>
	<locality type="table">
		<referenceFrom>1</referenceFrom>
	</locality>
</localityStack>the foregoing reference</eref>.</p>
```

**Comment by opoudjis** [comment]
The intent is what you're seeing, that the supplied text overwrites any attempt to provide autogenerated text.

* If I want to provide localities, and have custom text reflecting the localities, I can still supply custom text that reflects the localities. So `<<ref_3,clause=5,table=1,"Clause 5, Table 1, the foregoing reference">>`.
* But if I want to provide localities (for machine readability reasons), but suppress the locality display, forcing pre-rendering prevents me from doing so.

Will update the documentation text.
