### ISSUE TITLE
Ruby 3.0 compatibility: remove `byebug` from all gems

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#560]
`byebug` is only available on Ruby 2.x and has no replacement on Ruby 3.0. We need to remove all dependencies and mentions of `byebug` from all gems (and gemspecs).

**Comment by opoudjis** [comment]
I am using byebug successfully in Ruby 3.0, but I'm noticing that people are starting to have trouble with it, and that it hasn't been updated in a year.

I don't see why I need to switch, but I will switch to https://github.com/ruby/debug ; Rails will switch to it in v7, and it will be included in Ruby as of Ruby 3.1.

**Comment by opoudjis** [comment]
Addressed the gems I maintain; those maintaining the other gems will need to do likewise.
