### ISSUE TITLE
(URGENT) Consistent naming of `fieldofapplication` `usageinfo` attributes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#564]
See https://github.com/metanorma/isodoc/commit/b28ccedccbf46866b3dbf1d961fd5232c21b6d86#r60653980 and https://github.com/metanorma/metanorma.org/pull/518#pullrequestreview-812024381

We need a consistent way of naming attributes.

In the implementation you're using `fieldofapplication` (just lowercase), in documentation it is `fieldOfApplication` (lower camelcase). The AsciiDoc convention is hyphenation (`field-of-application`), and in XML we can also stick with `field-of-application`.

Same for `usageinfo`.

Before making this publicly available we ought to fix this.

**Comment by opoudjis** [comment]
Changes:

* `link/@updatetype` to  `link/@update-type`, with synonym: `link:../parent[update-type=true]`, `link:../parent[updatetype=true]`
* geographic-area, field-of-application, usage-info, grammar-value, grammar-info, verbal-definition, non-verbal-representation
