### ISSUE TITLE
Support PDF watermark labels (support multiple languages)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#567]
From @intelligent2013:

> The word for draft watermark will be used from the resource `localized-string key="draft_label"`:
> 
> ```
> <localized-string key="draft_label" language="en">draft</localized-string>
> ```
> 
>  ```
> <localized-string key="draft_label" language="fr">brouillon</localized-string>
> ```
> 
> The draft watermark will be displayed if:
> 
> * exists `..bibdata/version/draft` (example `<draft>v1.07</draft>`)
>   or
> * `status/stage` contains `draft` or `projet` (fr)

_Originally posted by @ronaldtse in https://github.com/metanorma/bipm-si-brochure/issues/164#issuecomment-979714544_

**Comment by opoudjis** [comment]
As https://github.com/metanorma/bipm-si-brochure/issues/164#issuecomment-979794554 makes clear, there is absolutely nothing for me to do here, that content all exists in Presentation XML already.

**Comment by ronaldtse** [comment]
@opoudjis we wish to have a way to customise those watermarks.

**Comment by ronaldtse** [comment]
@opoudjis says that the "draft" labels are internationalised (in metanorma-standoc) and can be overridden in flavor gems. Let's leave the watermark customization until later, until someone really needs it.
