### ISSUE TITLE
Add image validity check on incorporation (PNG)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#572]
From https://github.com/metanorma/metanorma-ogc/issues/323#issuecomment-986413687

The invalid PNG below was given to Metanorma and failed at Java processing as OpenJDK is unable to read it.

![144447885-088bce62-1c6b-4e04-bffd-531a817e5788](https://user-images.githubusercontent.com/11865/144785806-ab28f3ec-1f00-4509-8235-db7ae5a0996f.png)

This image run through `pngcheck` and it gave the following error:

```sh
$ pngcheck ~/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png
/Users/me/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png  invalid bKGD length
ERROR: /Users/me/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png

$ pngcheck -cvt ~/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png 
File: /Users/me/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png (136226 bytes)
  chunk IHDR at offset 0x0000c, length 13
    2250 x 922 image, 32-bit RGB+alpha, non-interlaced
  chunk gAMA at offset 0x00025, length 4: 0.45455
  chunk cHRM at offset 0x00035, length 32
    White x = 0.3127 y = 0.329,  Red x = 0.64 y = 0.33
    Green x = 0.3 y = 0.6,  Blue x = 0.15 y = 0.06
  chunk pHYs at offset 0x00061, length 9: 9448x9448 pixels/meter (240 dpi)
  chunk bKGD at offset 0x00076, length 2:  invalid length
ERRORS DETECTED in /Users/me/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png
```

We should add a PNG validation step, produce an error message and a suggested solution on invalid images. 

NOTE: Otherwise users will blame Metanorma for crashing / missing the image on render.

**Comment by ronaldtse** [comment]
We will incorporate [`pngcheck`](http://www.libpng.org/pub/png/apps/pngcheck.html) as a validation routine, as a Ruby gem that wraps/compiles pngcheck: https://github.com/metanorma/pngcheck-ruby/issues/1

**Comment by opoudjis** [comment]
Pending https://github.com/metanorma/pngcheck-ruby/issues/1

**Comment by ronaldtse** [comment]
pngcheck is now released. We need to use the code as demonstrated here:
https://github.com/metanorma/pngcheck-ruby#pre-validation-with-libpng-ruby
