### ISSUE TITLE
When `inkscape` command is missing from PATH, raise a hard error

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#573]
Originally encountered in html2doc where the "image path" specified was empty. 

The culprit is a missing `inkscape` command being missing from PATH

Metanorma should immediately fail when Inkscape is not found or when inkscape processing fails.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-ogc/issues/327#issuecomment-986842520_

**Comment by ronaldtse** [comment]
@CAMOBAP would you be able to handle this? Thanks!

**Comment by CAMOBAP** [comment]
In progress

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
