### ISSUE TITLE
Allow documents to be part-of other documents

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#58]
Add a document attribute, and expose it in isodoc metadata.

**Comment by ronaldtse** [comment]
@opoudjis is this going to part of Relaton relationships? Do we need a consolidated way of specifying bibliographic relationships in Metanorma AsciiDoc?

**Comment by ronaldtse** [comment]
I gather that this issue is about the underlying attribute/modeling. The other issue (https://github.com/metanorma/metanorma-itu/issues/7) is about rendering. Correct?

**Comment by opoudjis** [comment]
Correct.

**Comment by opoudjis** [comment]
> is this going to part of Relaton relationships? 

Yes.

> Do we need a consolidated way of specifying bibliographic relationships in Metanorma AsciiDoc?

The document attributes to date have been specific to flavours, there has not been a generic set of document attributes specified in metanorma-standoc. We probably do need to specify them generically, yes. The problem with that is, we will also need to fetch bibliographic data about document relations, which turns this into references handling through the relaton gem.

**Comment by ronaldtse** [comment]
> We probably do need to specify them generically, yes. The problem with that is, we will also need to fetch bibliographic data about document relations, which turns this into references handling through the relaton gem. (That can be avoided in the part-of relation, presumably. The only attribute guaranteed to be present is the document identifier.)

We probably should give users the option of filling in manually -- not all relating documents will be fetch able via the relaton gem?

**Comment by opoudjis** [comment]
The problem with filling them in manually is what I've already objected to for NIST: populating them through asciidoctor document attributes is a nightmare. We should instead refer to a relaton YAML document or relaton XML document.

**Comment by ronaldtse** [comment]
@opoudjis we've discussed about this a number of times without a resolution. It's easy to link a Relaton YAML from the document via a path attribute. The question is whether people can accept this?

**Comment by opoudjis** [comment]
The alternative, having them try to do it with tagging within Metanorma, is worse. 

This is holding up this issue unnecessarily:

* If the document identifier is recognised by relaton, then relaton can fetch the entire record. We will attempt that. If there is no registered record:
  * The bare minimum is to specify the document this is part of by document identifier. That can be implemented.
  * The one enhancement we can do readily (and have done in references) is specify document identifier + document title. As with references, we can allow that by the convention ID, TITLE.
  * Anything else needs an external relaton document, and that means either relaton XML or relaton YAML. Recall that this is an asciidoctor document variable: there is no scope to do anything else.
  * If people can't accept that, then they can limit themselves to ID + TITLE, or their standards organisation can register the containing document early, so that relaton can fetch it.

Suggest you not let the perfect be the enemy of the good. Especially as I don't see any perfect alternative here.

**Comment by opoudjis** [comment]
Have implemented in metanorma-standoc (`:part-of:` document identifier) and extracting in isodoc.

**Comment by ronaldtse** [comment]
> * If the document identifier is recognised by relaton, then relaton can fetch the entire record. We will attempt that.

Agree.

> * If there is no registered record:
>   * The bare minimum is to specify the document this is part of by document identifier. That can be implemented.

Agree.

>   * The one enhancement we can do readily (and have done in references) is specify document identifier + document title. As with references, we can allow that by the convention ID, TITLE.

Are you saying this is a structured (document identifier + document title)?

>   * Anything else needs an external relaton document, and that means either relaton XML or relaton YAML. Recall that this is an asciidoctor document variable: there is no scope to do anything else.

Yes, and now we have AsciiBib, that would also work (https://github.com/metanorma/relaton/issues/33)

>   * If people can't accept that, then they can limit themselves to ID + TITLE, or their standards organisation can register the containing document early, so that relaton can fetch it.

I suspect the best way is to allow them to use AsciiBib for a structured reference so Relaton can know which part is the "document identifier", and which part is the "document title".

**Comment by opoudjis** [comment]
> Are you saying this is a structured (document identifier + document title)?

Yes.  Should I implement it?

**Comment by ronaldtse** [comment]
> Yes. Should I implement it?

Yes please -- are you planning to do it via AsciiBib or the old AsciiDoc reference format?

**Comment by opoudjis** [comment]
Wait. Wait wait wait. We are not talking about bibliographies here. We are talking about bibdata, document metadata. So this has to fit in document attributes. 

Please do not conflate AsciiBib, which is the use of Asciidoctor definition lists to specify bibliographies, with Relaton YAML. AsciiBib is completely irrelevant to bibdata, which is what this ticket is about, and so is AsciiDoc references: I am not talking about bibliographies and bibitem. That is why I am referring to document identifier + document title: if this was a bibliography entry and not a document attribute, I would have more room to play.

**Comment by ronaldtse** [comment]
Since https://github.com/metanorma/metanorma-itu/issues/7 is now implemented maybe this is the generic solution we need...

**Comment by opoudjis** [comment]
I don't think it is at all. ITU has only implemented an added identifier. Doesn't this require more?

And i still need to implement "structured (document identifier + document title)" for the document relations embedded inside of document attributes. I'm going to do that now.

**Comment by opoudjis** [comment]
This has ... been confused.

This ticket is about document attributes with part-of nominating a document identifier.

The ITU ticket is about *one* rendering, but that is idiosyncratic. And I think all renderings of part-of documents are going to be idiosyncratic (although they will likely be similar.)

**Comment by opoudjis** [comment]
Added complication: we already use `,` as a delimiter separating document identifiers.

We will rescind this: `;` will henceforth separate document identifiers, and `,` will delimit title from identifier. So `NIST SP 800-1,Title 1;NIST SP 800-2,Title2`.

**Comment by opoudjis** [comment]
I have just implemented that last bit, which completes https://github.com/metanorma/metanorma-standoc/issues/58#issuecomment-487329710

I wish to now close this ticket.

**Comment by opoudjis** [comment]
Down the road, these document attributes may  reference external relaton: if there is a document ID included in an external bibliography, then relaton will be looking for identifier resolution first in such an external file, before going online.
