### ISSUE TITLE
Consolidate Ruby module namespace under `Metanorma`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#586]
All code should be consolidated under the `Metanorma` module namespace.

Metanorma relies on three core gems, [`metanorma`](https://github.com/metanorma/metanorma), [`metanorma-standoc`](https://github.com/metanorma/metanorma-standoc) and [`isodoc`](https://github.com/metanorma/isodoc).

Each flavor uses its own `metanorma-XXX` gem that inherits from `metanorma-standoc`.

The problem lies in `metanorma-standoc` and `isodoc`, where it uses a module namespace called `Asciidoctor`, the AsciiDoc parser used. We have for a long while added parser and XML generation code to that namespace, which is incorrect.

This ticket is to rename all modules under the wrong namespace and bring them back into the main `Metanorma` namespace. Hacks to the parser should also be extracted and only called with Ruby's include/extends on the Asciidoctor classes.

There are two solvable challenges when performing this task:
* Carefully distinguish calls to "Metanorma code placed within Asciidoctor namespace" or to the actual Asciidoctor parser. We have extensive tests so it won't be hard to determine accuracy. 
* We need to apply this refactor to all Metanorma flavor gems (metanorma-XXX gems), so this is a matter of being careful in issuing PRs.

**Comment by ronaldtse** [comment]
Things like "Asciidoctor::Standoc::Base" should just be "Metanorma::Standoc::Base".

**Comment by webdev778** [comment]
The PRs that pass the tests can be merged instantly. The docs can be merged last. Others will either require previous PRs to be merged first or will need some fixes. I included a compatibility layer that we may remove in the future.

**Comment by webdev778** [comment]
Do note a test failure in metanorma-iso - it was failing before.

**Comment by webdev778** [comment]
The three gems: iso, standoc and generic are required by other gems. Therefore they include a compatibility layer (`lib/asciidoctor`) which can be preserved after we finish this process or we can remove it. The next ones won't, because there's no reason to have it.

**Comment by webdev778** [comment]
A test failure in ietf: was failing before.

**Comment by webdev778** [comment]
A test failure in un: was failing before.

**Comment by webdev778** [comment]
A test failure in ribose: was failing before

**Comment by webdev778** [comment]
Done!

**Comment by webdev778** [comment]
The repos that are unmaintained yet would also benefit from an upgrade if they were up to date:

- metanorma-vg
- metanorma-sample
- metanorma-gb
- asciidoctor-rfc

**Comment by ronaldtse** [comment]
We need to merge these:

Crucial, part 1
* https://github.com/metanorma/metanorma-standoc/pull/589

Crucial, part 2 (After part 1 merged)
* https://github.com/metanorma/metanorma-generic/pull/67
* https://github.com/metanorma/metanorma-iso/pull/574

Porting (the rest will pass once Crucial ones merged)
* https://github.com/metanorma/metanorma-cc/pull/136
* https://github.com/metanorma/metanorma-bipm/pull/159
* https://github.com/metanorma/metanorma-iho/pull/53
* https://github.com/metanorma/metanorma-itu/pull/308
* https://github.com/metanorma/metanorma-ietf/pull/174
* https://github.com/metanorma/metanorma-ogc/pull/346
* https://github.com/metanorma/metanorma-un/pull/103
* https://github.com/metanorma/metanorma-iec/pull/131
* https://github.com/metanorma/metanorma-mpfa/pull/79
* https://github.com/metanorma/metanorma-m3aawg/pull/81
* https://github.com/metanorma/metanorma-ribose/pull/126
* https://github.com/metanorma/metanorma-csa/pull/69

Docs
* https://github.com/metanorma/metanorma.org/pull/557

**Comment by ronaldtse** [comment]
All done. Thank you @webdev778 @opoudjis !
