### ISSUE TITLE
PDF: allow inclusion of table of contents of figures, tables, requirements in all flavours

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#605]
Follow-on from https://github.com/metanorma/metanorma-standoc/issues/158

* A placeholder for any one of these optional tables of contents shall be signalled by the inclusion in PresentationXML of the element `<toc type="table|figure|requirement"><title>...</title></toc>` within the misc-container, where title is the localised title of the type of table of contents.
* ToC are currently implemented only for Word and PDF.

**Comment by Intelligent2013** [comment]
Xslt updated.
Notes:
- BSI: contains figures and tables titles already as entries in the main ToC
- IEC: ToC contains list of tables and figures already
- ITU: ToC contains list of tables and figures for 'Technical Report' and 'Technical Paper' by default
- NIST-CSWP: there isn't ToC at all
- OGC White-paper: consolidated list of tables and figures displayed under the title 'Table of Figures' already
- UN Plenary: there isn't ToC at all
