### ISSUE TITLE
Do not hyperlink to hidden bibitem

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#608]
Follow-on from https://github.com/metanorma/metanorma-standoc/issues/547

`<eref bibitem="X"/>` in HTML and Word hyperlinks either to `bibitem[@id = 'X']/uri[@type = 'citation']`, if provided, or else to `bibitem[@id = 'X']`. So:

````
<eref bibitem="X">Text1</eref>
<eref bibitem="Y">Text2</eref>

....

<bibitem id="X">
<uri type="citation">http://example.com</uri>
</bibitem>

<bibitem id="Y">
</bibitem>
````

renders as:

````
<a href="http://example.com">Text1</a>
<a href="#Y">Text2</a>
````

In  https://github.com/metanorma/metanorma-standoc/issues/547, I am changing this behaviour if `bibitem[@type = 'hidden']`: 

If `bibitem[@id = 'X']/uri[@type = 'citation']` is provided, I still hyperlink to it. Otherwise, I do not hyperlink to anything (because `bibitem[@id = 'X']` is no longer included in the document.

I'm seeing that hyperlinking is not implemented in Presentation XML. If you are implementing hyperlinking of references in PDF, and have not already anticipated this issue with hidden citations, please do likewise.

**Comment by Intelligent2013** [comment]
Xslt updated.
