### ISSUE TITLE
tag on notes, admonitions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#629]
Currently, if a note or admonition has no caption in the Presentation XML, you and I both supply the type of the admonition of a label; so:

````
<admonition type="important"><p>Hello</p></admonition>
````

is rendered as:

````
IMPORTANT

Hello
````

But this is not doing internationalisation, and it is not allowing for the dropping of labels.

I will be addressing this in Presentation XML for https://github.com/metanorma/metanorma-iso/issues/642. I will be populating `note/name` and `admonition/name` with the admonition type label in Presentation XML. If you do not see `note/name` or `admonition/name` henceforth, do NOT populate them: the caption is meant to be missing.

**Comment by Intelligent2013** [comment]
Done.
