### ISSUE TITLE
Support internationalisation for custom localities 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#633]
Custom localities today only work for English, as it is a direct rendering of the locality type.

e.g.
```
<<foo,locality:appendix=1>>
=> Appendix 1
```

But this is poor practice, and does not work for say, French, which can contain accents.

This task is to make custom localities work with internationalisation (and English should also be rendered according to a text, not "verbalisation" of the type).

**Comment by opoudjis** [comment]
The flavour i18n files will have partial definitions of the locality hashes, so they require deep_merge with their ancestor i18n files, as has already been done for relaton-render.
