### ISSUE TITLE
Should we use hyphen to encode numeric ranges?

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#641]
Since quite some time, I've been noticing that n-dashes are used for
representing numeric ranges:

![capture3](https://user-images.githubusercontent.com/33627611/176478113-1bf5f6b3-f8c7-4663-a0c5-a17750e780a3.PNG)

However, there is no encoding to render n-dashes in AsciiDoc (at time of publication).
So my question is, should we use hyphens instead? (e.g `69-161`)

**Comment by manuelfuenmayor** [comment]
In private chatting, we concurred on using `&ndash;` (or `&#2013;`) for encoding en-dashes.
Closing.

**Comment by ronaldtse** [comment]
Numeric ranges should be semantically encoded as numeric ranges, similarly for dates (and years). In the future perhaps something like `range:[n,m]` or shorthands like `n...m` would be more suitable.

To ask users to encode using entity codes or entity names is sidestepping the real issue -- no normal user would bother entering the `&ndash;` for a numeric range.

**Comment by ronaldtse** [comment]
@manuelfuenmayor can you please help add the "Numeric range" encoding guidance to metanorma.org? Thanks.
