### ISSUE TITLE
Remove deprecated, alternative tags in favour of related terms

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#642]
`related[@type=deprecates]` = deprecated

`related[@type=equivalent]` = equivalent

@Intelligent2013 This will impact you too.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 This will impact you too.

@opoudjis what should I do here?

**Comment by opoudjis** [comment]
Eventually, remove all references to the tags `deprecated` and `admitted`, and replace them with references to `related[@type = 'deprecates']` and `related[@type = 'equivalent']`. But wait for me to start this.

**Comment by opoudjis** [comment]
No, I've thought better of it: deprecated and admitted as designations can still take metadata, whereas related terms cannot, because they are purely cross-references. Ticket annulled.
