### ISSUE TITLE
Appveyor not fetching references

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#65]
https://ci.appveyor.com/project/ribose/metanorma-standoc/builds/23680697/job/xwtwjd0kdnikmwe1

Note that this only fails in Ruby 2.5, and only in branch; so I suspect it's not a real failure.

**Comment by ronaldtse** [comment]
Thanks @opoudjis for posting!

**Comment by CAMOBAP795** [comment]
Fixed
