### ISSUE TITLE
Optimise smartquote processing

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#652]
Parsing iso-10303-2 for https://github.com/metanorma/metanorma-iso/issues/601 brings up that once again, smartquote processing is a massive time-sink, and needs to be optimised. (Gave up waiting after an hour.) The problem with the current implementation is that it uses Nokogiri traverse to go through all text nodes in textual sequence, but it relies heavily on Nokogiri ancestor search to work out appropriate behaviour for each text node. What is needed is a stack of elements containing the current text node, rather than having each node launch a dynamic ancestor query.

**Comment by opoudjis** [comment]
Sample file of 12k lines took 12 sec to process smartquotes traversal. Sample file of 24k lines (duplicated terms section) took 54 sec, which suggests O(n^2) (!) performance. 30k goes 98 sec. 

Using path query for each node and checking its elements, rather than dynamic ancestor query, Sample file of 30k lines  goes from 98 sec to 1.04 sec.

I'd given up on processing iso-10303-2 after 1h15 min, it was still doing smart quotes (although a sizeable chunk of that time was fetching references, maybe 15 mins).

Now smart quotes are done in 5 seconds.

I deem that a success.

**Comment by ronaldtse** [comment]
Thank you! I’m glad this worked out.
