### ISSUE TITLE
Windows image processing broken

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#672]
https://github.com/metanorma/metanorma-standoc/runs/8190807527?check_suite_focus=true

Breakage in Metanorma::Standoc::Datamodel::DiagramPreprocessor. Not my code, no idea how it works, and it's only crashing on PC.

**Comment by opoudjis** [comment]
https://github.com/metanorma/pngcheck-ruby/actions

**Comment by opoudjis** [comment]
@ronaldtse If there is no immediate resolution to this issue, I will need to remove the pngcheck functionality from the gem.

**Comment by ronaldtse** [comment]
From https://github.com/metanorma/pngcheck-ruby/issues/11 it is clear that pngcheck is not the issue, it is whatever that generates that corrupt PNG image.

**Comment by opoudjis** [comment]
@CAMOBAP I'm going to need your help.

At issue is this line:

````
def image_validate(doc)
        doc.xpath("//image[@mimetype = 'image/png']").each do |i|
          d = Metanorma::Utils::datauri(i["src"], @localdir)
          d.chars.to_a.each_slice(80).to_a.map { |s| s.join }.each { |s| warn s }
          png_validate1(i, Base64.strict_decode64(d.sub(/^.+?base64,/, "")))
        end
      end
````

Metanorma::Utils::datauri(i["src"], @localdir) in Windows is returning empty for PlantUML-generated images, so nothing is being passed on to png_validate1.

This happens in standoc, bin/rspec --format doc spec/metanorma/datamodel/diagram_preprocessor_spec.rb

There may well be a Windows-specific bug in metanorma-utils, but I can't identify what it is.

**Comment by ronaldtse** [comment]
I’m looking at this code and it is missing several sanity checks, eg. Whether the datauri data is nil or empty. @CAMOBAP when you handle this can you add those checks? Eg output an Error message if a bad situation arises. Validation failure of an image should not kill the generation of a document.

**Comment by ronaldtse** [comment]
> I’m looking at this code and it is missing several sanity checks, eg. Whether the datauri data is nil or empty. @CAMOBAP when you handle this can you add those checks? Eg output an Error message if a bad situation arises. Validation failure of an image should not kill the generation of a document.

I have done these checks in #675 but the specs are still failing due to relaton-iso.

**Comment by opoudjis** [comment]
Removing fatal error, as requested by @ronaldtse

**Comment by opoudjis** [comment]
VCR cassettes refreshed, will pass.

Ticket remains open, @CAMOBAP still working on the Windows issue.

**Comment by CAMOBAP** [comment]
Already done by @opoudjis
