### ISSUE TITLE
Support unit statements for figures and tables

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#688]
Source issues: https://github.com/metanorma/mnconvert/issues/224, https://github.com/metanorma/mnconvert/issues/228.

ISO and IEC documents may contain the text describing the units used in the tables and figures (unit statements).

From [Guidelines for coding IEC and ISO standards in NISOSTS.pdf](https://github.com/metanorma/mnconvert/files/9429314/Guidelines.for.coding.IEC.and.ISO.standards.in.NISOSTS.pdf)

- for figures (from `8.4 Unit statements in figures`):
> When a figure contains a unit statement such as “Dimensions in millimetres”, this is coded as as `<p>` with `@content-type=”dimension”`.
> ![image](https://user-images.githubusercontent.com/5559926/194920150-ac09708e-214b-47e8-9384-abbdefefce31.png)

- for tables (from `6.6.5 General unit statements in tables`)
> When a table contains text describing the units used in the table it is captured as `<p>` with `@content-type=”dimension”` in `<table-wrap-foot>`.
> For example:
![image](https://user-images.githubusercontent.com/5559926/188876169-a0f33331-825a-4806-9cf1-cfb01da9af1f.png)
>is coded as (NISO STS XML):
> ```xml
> </table>
> <table-wrap-foot>
> <p content-type="Dimension" specific-use="100">Mass fractions in per cent</p>
> </table-wrap-foot>
> </table-wrap>
> ```

Also, this feature is using in BSI documents. For instance, https://github.com/metanorma/mn-samples-bsi/blob/main/reference-docs/standards/bs-9999/BS%209999.pdf, page 90:
![image](https://user-images.githubusercontent.com/5559926/194921966-59c388b1-70e0-4897-b7c3-bd67bd7c9a94.png)

This needs to be supported by metanorma-standoc.

**Comment by ronaldtse** [comment]
This issue is also mentioned here: https://github.com/metanorma/metanorma-iso/issues/754

**Comment by opoudjis** [comment]
We allow a type attribute on paragraphs:

````
[type="dimension"]
Blah blah
````

I'm not going to put in numerical values into attributes on an adhoc basis. We need a global solution for RDF microformatting of Metanorma documents, in line with Smart documents, and that is the only context I will insert numeric values with.

Does `@type` address your need?

**Comment by ronaldtse** [comment]
@opoudjis look at https://github.com/metanorma/metanorma-iso/issues/754 please.

**Comment by opoudjis** [comment]
This is not a key, and in the first figure, it occurs alongside the key. 

Instead, this is some sort of bizarre extraneous note to a table or figure, which is idiosyncratically rendered.

So, the solution to this is:

````
[NOTE,type=units]
Dimension in millimeters
````

I'll implement that.

**Comment by ronaldtse** [comment]
@opoudjis as @Intelligent2013 alluded to -- should we consider this not as a note but as a secondary caption?

**Comment by opoudjis** [comment]
... We haven't defined secondary captions, and that  seems an unnecessary complication to the model.

**Comment by ronaldtse** [comment]
OK I'm happy with `NOTE=units`.

**Comment by opoudjis** [comment]
Stop requirement that notes at the end of a clause must not fold into a preceding block; it is bogus, and "keep-separate" attribute takes care of such notes if needed.

**Comment by opoudjis** [comment]
Units notes need to not be numbered.

**Comment by Intelligent2013** [comment]
@opoudjis confirmed. But there is the issue with note numbering (see `NOTE 2` at bottom):

![image](https://user-images.githubusercontent.com/5559926/220237559-fe55dcdb-ee56-4b3c-aa0a-5c568e4c02e2.png)

> Units notes need to not be numbered.

but non units notes should be numbered without units notes counter.

**Comment by ronaldtse** [comment]
This is back to @opoudjis : the first figure NOTE is now called "NOTE 2" due to presence of unit note.

**Comment by opoudjis** [comment]
Needing to fix the counting of notes when units and other skippable notes are present.

**Comment by opoudjis** [comment]
Should be fixed, please review.

**Comment by Intelligent2013** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/5559926/222941122-f3450100-7aa9-4a08-ade6-79435a89d986.png)

@opoudjis thank you!
