### ISSUE TITLE
Enable combination of cross-references for bibliographic items

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#691]
It is currently possible to use conjunctions `and`, `or`, `from` and `to` for clauses, tables, etc., but not for bibliographic items. 

Following markup:
````
<<from!margolis;to!riehle>>

<<margolis;to!riehle>>

<<from!margolis;riehle>>

<<margolis;and!riehle>>

<<margolis;or!riehle>>
````

creates this output:
![image](https://user-images.githubusercontent.com/55683568/196528557-a0269173-7514-4a0b-a511-f78b70b107ae.png)

It would be useful to add `and` and `to` conjunctions for bibliographic items as well.

**Comment by opoudjis** [comment]
Made urgent, because it's SI Brochure. (On the other hand, the ITU WHO tickets are currently bottom of the pile.)

**Comment by opoudjis** [comment]
xref with conjunctions (locations) is currently outputting as

`<xref target="id1"><location target="id1" connective="from"/><location target="id2" connective="to"/></xref>`

with its text resolved in Presentation XML:

`<xref target="id1"><location target="id1" connective="from"/><location target="id2" connective="to"/>Clause 1 to 2</xref></p>`

If the contents of the cross-reference are bibitems, they are rendered instead as

`<eref type="inline" bibitemid="A" citeas="A"><eref connective="from" bibitemid="A" citeas="A"/><eref connective="to" bibitemid="B" citeas="B"/></eref>`

I will convert this to

`<erefstack><eref connective="from" bibitemid="A" citeas="A" type="inline" /><eref connective="to" bibitemid="B" citeas="B" type="inline" /></erefstack>`

Rendering this then becomes simply a matter of rendering the individual cross-references, and the connective between  them, reusing existing code for xrefs.
