### ISSUE TITLE
Bibliographic spans: unrecognised `span:` warning not provide enough information for debugging

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#723]
This has been reported here by IEEE:
* https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/issues/19

The error of:
```
unrecognised `span:`
unrecognised `span:`
```

Really gives no indication on what the error is or where this span problem comes from.

We need to give more information, including details of the actual bibliographic item, what "span keyword" isn't allowed, to allow the user to fix the issue.

**Comment by opoudjis** [comment]
Error message is now:

> unrecognised key 'surname1' in `span:surname1[Wozniak]`
