### ISSUE TITLE
Request for new citation span elements: edition and comment

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#738]
From @intelligent2013 on BSI STS `mixed-citation`:

I've analyzed `mixed-citation` structure in BSI reference documents ([Mapping_mixed_citation_metanorma.docx](https://github.com/metanorma/mn-samples-bsi/files/10689310/Mapping_mixed_citation_metanorma.docx)) and at this moment there aren't mapping for these elements:

- `edition`:

```
<ref id="ref_23">
	<label>[22]</label>
	<mixed-citation publication-type="book">
		<person-group person-group-type="author">
			<name>
				<surname>Manual</surname>
				<given-names>Oslo</given-names>
			</name>
		</person-group>
		<year>2018</year>, <source>Guidelines for collecting, reporting and using data on innovation</source>. <publisher-name>OECD</publisher-name>
		<italic>,</italic>
		<edition>Fourth Edition</edition>
	</mixed-citation>
</ref>
```
(Source XML example: https://github.com/metanorma/mn-samples-bsi/blob/master/reference-docs/adoptions/bs-en-iso-56002/30421181.xml)

- `comment`

```xml
<ref id="ref_19">
	<label>[18]</label>
	<mixed-citation publication-type="book">
		<person-group person-group-type="author">
			<collab>NIP</collab>
		</person-group>(2004). <source>Algemene Standaard Testgebruik.</source>
		<comment>[General Standard Test Use]</comment>. <publisher-loc>Amsterdam</publisher-loc>: <publisher-name>NIP</publisher-name>
	</mixed-citation>
</ref>
```
(Source STS XML: https://github.com/metanorma/mn-samples-bsi/blob/master/reference-docs/adoptions/iso-10667-1/30386407.xml)

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn-samples-bsi/issues/10#issuecomment-1423140928_

**Comment by opoudjis** [comment]
Already actioned in https://github.com/metanorma/mn-samples-bsi/issues/10
