### ISSUE TITLE
Figure block with Key and Notes?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#744]
Is this a valid encoding with Key and Notes?

I know that we can place the key and notes outside, but this seems to be a more intuitive way of encoding: the entire thing technically belongs to the same Figure.

(This method is not described by our documentation on metanorma.org)

```adoc
.Scope of <<BS_7273_4>>
====
image::2013-02348_BS7273-4_01.png[]

[%key]
image:2013-02348_BS7273-4_01KEY1.png[] {blank}:: Within the scope of this standard
image:2013-02348_BS7273-4_01KEY2.png[] {blank}:: Outside the scope of this standard

NOTE: Any special recommendations for provision and siting of fire detectors and {{manual call point,manual call points}} are within the scope of this standard. +

NOTE: The effect of failures of power supply for the devices is within the scope of this standard.
====
```

**Comment by opoudjis** [comment]
> Is this a valid encoding with Key and Notes?

Only if you put a `[figure]` style attribute before the example.
