### ISSUE TITLE
Plantuml failing to install on GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#755]
https://github.com/metanorma/metanorma-standoc/actions/runs/4304265729/jobs/7505063262

**Comment by CAMOBAP** [comment]
Looks like temporally network issue on brew, checking...

**Comment by opoudjis** [comment]
Specific to Mac?

**Comment by CAMOBAP** [comment]
Gone https://github.com/metanorma/metanorma-standoc/actions/runs/4304265729/jobs/7506091095
