### ISSUE TITLE
Refactoring of relaton

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#76]
@andrew2net do not action any of this yet. This may take a whole to realise

* ~~Add dataset to document types~~
* ~~Add number attribute to edition~~
* ~~Add scope to docidentifier~~
* ~~Document discontinuous page ranges (already supported by the model)~~
* ~~Series run in references~~
* ~~Price~~
* ~~Move keyword into relaton~~
* Model ICS, CCS as classifications
* License

**Comment by ronaldtse** [comment]
@opoudjis is this ready for @andrew2net ?

**Comment by opoudjis** [comment]
No, would like to do the explicit modelling, and this has never been a priority. Would you like me to prioritise now?

**Comment by ronaldtse** [comment]
@opoudjis yes 690 is now in FDIS and we need to make it work. Will prioritize.

**Comment by opoudjis** [comment]
Most of these have already been done.

**Comment by opoudjis** [comment]
... In fact, they all have.
