### ISSUE TITLE
Support source code blocks with target item annotations, render as Figure with Key

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#764]
This source code block should be rendered as a Figure with Key:

```adoc
.Terms and definitions in Metanorma AsciiDoc
[source,adoc]
----
== Terms and definitions <1>

==== conceptual model <2>
alt:[CM] <3>

model that defines concepts of a universe of discourse <4>

[.source]
<<ISO_19101-1,clause=4.1.5>> <5>

==== logical model

model that implements a {{conceptual model}} at a logical level <6>
----
<1> Mandatory clause title
<2> Term for concept
<3> Alternate term for concept
<4> Definition of concept
<5> Source of concept
<6> Concept mention of a defined term in the same document
```

When the target item links `<1>` are present in the source code but the target item list is not present, Metanorma should treat the Key as missing but do not crash.

When the target item links are present in the source code and the target item list is present, Metanorma should render the target item list as a "Key" of the Figure.

This task is really about supporting source code block with a Key. This needs to be done in Metanorma XML proper.

From ISO DIR 2 on Figures with Key:
<img width="821" alt="Screenshot 2023-03-24 at 9 11 33 AM" src="https://user-images.githubusercontent.com/11865/227399096-2a296033-8bd7-4639-b123-ee68c1734513.png">

This is needed for proper PDF rendering in https://github.com/metanorma/metanorma-ogc/issues/517 (@intelligent2013)

**Comment by ronaldtse** [comment]
Relevant to https://github.com/metanorma/isodoc/issues/499

**Comment by opoudjis** [comment]
> This source code block should be rendered as a Figure with Key:

Under what conditions? Universally for all source code in Metanorma? Just OGC? Just ISO? Why exactly are we switching from inline annotation lists to keys after five years.

Will not action without scope and rationale.
