### ISSUE TITLE
Document fails to compile with plantuml input if the adoc is not at root

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#77]
Seems that Travis has trouble compiling the PlantUML input, causing the document not even to get generated, when the source adoc is at `sources/foo.adoc` and the WSD file is at `sources/models/bar.wsd`.

See the specific branch https://github.com/CalConnect/csd-standard-doc/tree/rt-broken-plantuml which demonstrates this problem despite all the paths set correctly. Metanorma still uses the wrong path to include the generated image.

(https://github.com/CalConnect/csd-lightweight-doc/issues/1)

**Comment by opoudjis** [comment]
So: 

* Document is in `sources/sections/a2-cc.adoc`
* Include path in document is: `include::../models/metanorma-model-csd/models/Csd_StandardDocument.wsd[]`
* Include path that metanorma is attempting is: `sources/models/metanorma-model-csd/models/Csd_StandardDocument.wsd`

I've run metanorma on the rt-broken-plantuml branch, and it's parsing the diagrams successfully, once I've initialised the submodules. Generation is crashing elsewhere, in the generation of all_parts references; I'll patch that, but I don't believe that I can reproduce your error.

**Comment by opoudjis** [comment]
to_all_parts parsing was assuming that both an English and a French title are present. That appears not to be the case for ISO/IEC 10118-1.

**Comment by opoudjis** [comment]
OK, now that the references are now fetching again, I see the error:

`Error: No such file or directory @ rb_sysopen - sources/plantuml/StandardDoc_StandardDocument.png, `

That was distinct from the initial not found error I was getting, when I had not yet initialised the submodules yet (so the image wasn't there at all.) Investigating.

**Comment by opoudjis** [comment]
Have fixed issue with plantuml processing: like all images, it is expected to be contained within the `@localdir` directory (e.g. `source/` if the document is in `source/document.adoc`), and plantuml images were being generated in the root plantuml directory.

A couple of other compilation issues in relaton-iso are being addressed separately.
