### ISSUE TITLE
PDF math: Height of left square bracket used as an opening bracket

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#776]
Left: original. Right: Metanorma.

The height of the "opening bracket" when it is the "left square bracket" gives it indeterminate height.

<img width="260" alt="Screenshot 2023-04-17 at 11 19 37 AM" src="https://user-images.githubusercontent.com/11865/232442469-84042b5d-3c55-4b91-bb42-c9a8cddd1c2d.png">

_Originally posted by @ronaldtse in https://github.com/metanorma/iso-iec-80000/issues/38#issuecomment-1511032259_

**Comment by Intelligent2013** [comment]
`git clone https://github.com/metanorma/iso-iec-80000`
`iso-iec-80000\sources\iso-80000-2-2019`
`bundle exec metanorma -t iso -x presentation document.adoc`
causes the error:
```
AsciiMath 1000 of 1450
parsing: bb(ii(A)) + bb(ii(B)) = bb(ii()C)
undefined method `to_mathml_without_math_tag' for nil:NilClass

              [parameter_one.to_mathml_without_math_tag],
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Maths: Malformed MathML: undefined method `to_mathml_without_math_tag' for nil:NilClass

              [parameter_one.to_mathml_without_math_tag],
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
(source: `16-matrices.adoc`).

**Comment by Intelligent2013** [comment]
I can repeat the issue for 2nd math only, it has wrong height:
![image](https://user-images.githubusercontent.com/5559926/232722556-259718a9-a06d-473f-9d2c-9e18eb5fc63d.png)

The reason: the last `]` placed outside of `math` in the presentation XML:
```xml
	<p id="_">The notation <stem type="MathML">
			<math xmlns="http://www.w3.org/1998/Math/MathML">
				<mstyle displaystyle="true">
					<mo>]</mo>
					<mo>−</mo>
					<mo>∞</mo>
					<mo>, </mo>
					<mi>b</mi>
				</mstyle>
			</math>
			<asciimath>]-oo, b</asciimath>
		</stem>] is also used.</p>
</td>
```
I.e. first bracket renders by jEuclid, 2nd renders as text.

How to fix:
In `terms.yaml` add `\` before `]`:
```
- id: t2-7.11
...
    The notation stem:[\]-oo, b]] is also used.
```
by
`    The notation stem:[\]-oo, b\]] is also used.`

After fix:
![image](https://user-images.githubusercontent.com/5559926/232725541-35f07a5b-3d50-4626-83ed-4430a7595167.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 ! @manuelfuenmayor can you please help make the change in the PR?

**Comment by Intelligent2013** [comment]
@manuelfuenmayor I've updated terms.yaml already for this particular case, but may be similar another cases.

**Comment by ronaldtse** [comment]
Closing since this is not a PDF issue.
