### ISSUE TITLE
PDF: Incorrect presentation in equations

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#777]
In relation to https://github.com/metanorma/bipm-si-brochure/pull/213

There are several issues in the equations that were not before. Here below, I mostly show examples from French version, but they apply to English version as well:

1. Look at the in the image below and compare the highlighted regions with original version:
   Generated French version:
   ![brochure-issue-6-fr](https://user-images.githubusercontent.com/33627611/232918540-c2a1ef75-248d-4b0f-a9ef-e950c7ac7bdd.PNG)
 
   Original:
   ![brochure-issue-6-fr-original](https://user-images.githubusercontent.com/33627611/232918698-47692140-8748-4109-a92f-bef40195e1bb.PNG)

   (Instances like shown above are everywhere throughout the document.)

2. There are a few cases where parentheses are not shown, for instance:
   Generated French version:
   ![brochure-issue-7-fr](https://user-images.githubusercontent.com/33627611/232919394-b74f49e3-9926-424d-98b8-bf6308b8b70c.PNG)
  
   Original:
   ![brochure-issue-7-fr-original](https://user-images.githubusercontent.com/33627611/232919415-d67999a3-70e5-446d-83b6-822b3568f5b0.PNG)
    (Please also note the second case, `(X) g/mol`, that I missed to highlight.)

**Comment by ronaldtse** [comment]
@manuelfuenmayor the second issue is likely due to Plurimath’s treatment of MathML. Can you please help file the second issue there? Thanks!

**Comment by ronaldtse** [comment]
The first issue might have been fixed in https://github.com/metanorma/iso-iec-80000/pull/38#issuecomment-1513497833 .

**Comment by ronaldtse** [comment]
The second issue is moved to https://github.com/plurimath/plurimath/issues.

**Comment by Intelligent2013** [comment]
Regarding first issue, I've found PDF generated 3 days ago before the patch from https://github.com/metanorma/iso-iec-80000/pull/38#issuecomment-1513497833 from presentation XML generated 3 March:

![image](https://user-images.githubusercontent.com/5559926/232976856-fe6b9462-e876-423a-8681-ab0c66255eb4.png)

I'll re-generate XML and test again.

**Comment by Intelligent2013** [comment]
Confirmed, new generated XML gives bad PDF rendering
![image](https://user-images.githubusercontent.com/5559926/232980624-37e73f6a-0ee1-4ca1-8964-dae9ededf465.png)
I'll compare mathml.

**Comment by Intelligent2013** [comment]
Mathml example 1, left - old xml, right - new xml:
![image](https://user-images.githubusercontent.com/5559926/232982921-e0bb2f36-f7a9-459e-a658-31df3dfc4038.png)

XSLT modifies the mathml on-fly:
left - old xml, right - updated old xml (added `<mspace height="1.47ex" />`, `lspace="0.2em"`, etc.):
![image](https://user-images.githubusercontent.com/5559926/232983561-28cdaf79-91b1-4838-94d6-f404f3d626ac.png)

May be I have to update XSLT for the new structure...

Mathml example 2, left - old xml, right - new xml:
![image](https://user-images.githubusercontent.com/5559926/232983214-c71c787b-c66e-4212-8619-9c0515667fa0.png)

I think the issue in the new mathml - the element `munder` in the new xml.

**Comment by Intelligent2013** [comment]
Rendering on https://www.mathjax.org/#demo:
First example from new xml:
![image](https://user-images.githubusercontent.com/5559926/232990188-47a3d6c9-cd55-4e84-8b2a-d2fe7047052a.png)
To do: need XSLT on-fly update.

Second example from new xml:
![image](https://user-images.githubusercontent.com/5559926/232990418-621f9a6e-f30b-4f85-97c7-c484bd61de52.png)

Exactly, the issue in the mathml.

**Comment by ronaldtse** [comment]
@Intelligent2013 the changes are probably because we switched to our [Plurimath](https://github.com/plurimath/plurimath) library.

Can you file these issues in https://github.com/plurimath/plurimath ? Thanks!

**Comment by Intelligent2013** [comment]
> Can you file these issues in https://github.com/plurimath/plurimath ? 

@ronaldtse done for `munder` https://github.com/plurimath/plurimath/issues/135. For 1st issue I'll modify XSLT.

**Comment by Intelligent2013** [comment]
The issue with superscript fixed (vis XSLT on-fly update):
![image](https://user-images.githubusercontent.com/5559926/233026985-db009d3c-887a-4392-b6a2-34604837e481.png)

BIPM XSLT updated in metanorma-bipm.

**Comment by ronaldtse** [comment]
@Intelligent2013 can you ensure that this fix is applied to all flavors? Thanks.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 can you ensure that this fix is applied to all flavors? Thanks.

@ronaldtse yes, this fix applied in `common.xsl`.

**Comment by ronaldtse** [comment]
Thanks!

**Comment by manuelfuenmayor** [comment]
Confirmed fixed, closing.
