### ISSUE TITLE
PDF: Correct vertical bar symbol presentation

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#778]
In relation to https://github.com/metanorma/iso-iec-80000/pull/38

Vertical bar symbol `|` shows inclined, if encoded with unicode `&#x2223;`.
And, with no blank space in both sides at all, if encoded with `|`.

For example, this markup:

```adoc
Asciimath: stem:[{x_i &#x2223; i in I}]

Asciimath 2: stem:[{x_i | i in I}]
````

Outputs:
![iso-iec-issue-1-generated-2-pdf](https://user-images.githubusercontent.com/33627611/233222799-35d76e03-8150-4561-a442-d1b46ed97d94.PNG)

Output in HTML:
![iso-iec-issue-1-generated-2-html](https://user-images.githubusercontent.com/33627611/233223443-659d8e24-3423-42af-b6d4-701529c77e4e.PNG)

It would be great that, for both markups, the vertical bar shows like this:

![iso-iec-issue-1-original-2](https://user-images.githubusercontent.com/33627611/233223073-0ea9ad84-591a-46a6-8290-4d56a85e8d3e.PNG)

(Although I could add the white spaces in markup.)

**Comment by manuelfuenmayor** [comment]
There are also these cases:

Generated:
![issue-2-generated](https://user-images.githubusercontent.com/33627611/233224125-27af6aea-c501-4d3a-b65e-c947a9f03a85.PNG)

Original:
![issue-2-original](https://user-images.githubusercontent.com/33627611/233224159-e276ae7e-b8f0-47f3-95f9-29f66833ab77.PNG)

Generated:
![issue-3-generated](https://user-images.githubusercontent.com/33627611/233224187-7e3104fd-5a05-4b55-aaaa-4dc057d400ac.PNG)

Original:
![issue-3-original](https://user-images.githubusercontent.com/33627611/233224175-593cdf82-339b-4a66-9204-f2cc00b97ac3.PNG)

Generated:

**Comment by Intelligent2013** [comment]
> Vertical bar symbol `|` shows inclined, if encoded with unicode `&#x2223;`.

`∣` encoded in `<mi>∣</mi>`, therefore it renders as italic:
```xml
<stem type="MathML">
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <mstyle displaystyle="true">
      <mrow>
        <mo>{</mo>
        <msub>
          <mi>x</mi>
          <mi>i</mi>
        </msub>
        <mi>∣</mi>
        <mi>i</mi>
        <mo>∈</mo>
        <mi>I</mi>
        <mo>}</mo>
      </mrow>
    </mstyle>
  </math>
  <asciimath>{x_i ∣ i in I}</asciimath>
</stem>
```

After manual replace `<mo>∣</mo>`, PDF renders so:
![image](https://user-images.githubusercontent.com/5559926/233366612-9caa7da9-c5af-4947-8e24-db0a1a4e1db5.png)


I think it should be encoded in `mo`. @manuelfuenmayor could you create a ticket in `plurimath` repository?

> And, with no blank space in both sides at all, if encoded with `|`.

In this case it encoded in `mo`:
```xml
<stem type="MathML">
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <mstyle displaystyle="true">
      <mrow>
        <mo>{</mo>
        <msub>
          <mi>x</mi>
          <mi>i</mi>
        </msub>
        <mo>|</mo>
        <mi>i</mi>
        <mo>∈</mo>
        <mi>I</mi>
        <mo>}</mo>
      </mrow>
    </mstyle>
  </math>
  <asciimath>{x_i | i in I}</asciimath>
</stem>
```

Note: `&#x2223;` and `|` (`&#x7c`) are different characters. First is 'Divides'. second is 'Vertical line'. In the original document, `7C` is using.

So. I'll try to update mathml on-fly via XSLT again.

**Comment by Intelligent2013** [comment]
XSLT updated.
Example for `|` (`0x7c`):
![image](https://user-images.githubusercontent.com/5559926/233380143-2c7b3bd5-b525-4166-a031-1a5c5a21c12d.png)

**Comment by ronaldtse** [comment]
@Intelligent2013 for the `|` spacing (and other spacing issues), do you think they should be in the Presentation MathML?

**Comment by ronaldtse** [comment]
Got it, thank you @Intelligent2013 !

**Comment by manuelfuenmayor** [comment]
> I think it should be encoded in mo. @manuelfuenmayor could you create a ticket in plurimath repository?

@Intelligent2013, I just read this message of yours. Do you still want the ticket?

**Comment by Intelligent2013** [comment]
> @Intelligent2013, I just read this message of yours. Do you still want the ticket?

@manuelfuenmayor yes, please.
