### ISSUE TITLE
Limit image size to the document's viewable area

### ISSUE THREAD

**Issue by PeterTKY** [metanorma/metanorma-standoc#78]
Right now if we include an image in the document, given that the image is larger (general speaking, the width) than the viewable area, it will be cut. We should shrink the size of the image in this case to fit into the document.

**Comment by opoudjis** [comment]
I'm going to need a lot more information than that, and preferably a sample document. There is code that tries to shrink the image to page size in DOC output; the image size is deliberately left at 100% in HTML.

**Comment by ronaldtse** [comment]
The document in particular is https://github.com/CalConnect/csd-digital-addresses , I've given you access.

**Comment by opoudjis** [comment]
I see. PDF (as opposed to HTML proper) needs to limit the width of images.

**Comment by opoudjis** [comment]
Turns out that while there is image resizing code for HTML as well, it was being skipped for Data URI images. Fixing in isodoc.

**Comment by ronaldtse** [comment]
@opoudjis before we close it, can @PeterTKY confirm the fix? It's implemented in the Git version of the `isodoc` gem.

**Comment by PeterTKY** [comment]
I have always been friendly, and I will if everybody in the team will be!

**Comment by PeterTKY** [comment]
I can verify that images are not cut when they are too large now. But it becomes another problem that the images are now aligning to the left instead of middle. I will create another issue for that.

**Comment by opoudjis** [comment]
Ok, closing issue, thank you.
