### ISSUE TITLE
Flag to globally decline to number assets

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#785]
`sourcecode` is by default numbered, but there will be documents in which we want to globally decline to number sourcecode. To do so, we introduce  a new document attribute, `:block-unnumbered:`, whose value is a comma-delimited list of metanorma elements which shall not be numbered.

**Comment by opoudjis** [comment]
`:block-unnumbered: sourcecode`

**Comment by manuelfuenmayor** [comment]
Nick, maybe you have already thought about this. But it will be necessary to include an attribute to explicit number individual sourceblocks, in case of exceptions.

(I was thinking that it would be cool to enable the numbering for individual blocks if they have a prepended `[[anchor]]` for cross-reference. But that just an idea 😄 )

**Comment by opoudjis** [comment]
Hm. We do have the unnumbered attribute, and if it is set to false, it will override this global default.
