### ISSUE TITLE
Allow backslash to disable cross-reference asset

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#788]
In classic Asciidoc, it is allowed to use the backslash to disable the cross-reference functionality, like this: 
`\<< this-is-not-an-xref>>`.
Can we enable this markup in Metanorma as well? Because I've been "forced" to use:
 `<&#x200c;< this-is-not-an-xref>>`
in order to get the same result.

**Comment by opoudjis** [comment]
I can't replicate:

````
[[this-is-not-an-xref]]
== Clause

\<<this-is-not-an-xref>>
````

converts to

````
<clause id="this-is-not-an-xref" inline-header="false" obligation="normative">
<title>Clause</title>
<p id="_5cbcf85a-bb47-9288-c2f5-5a66edb87dfb">&lt;&lt;this-is-not-an-xref&gt;&gt;</p>
</clause>
````

@manuelfuenmayor Please point me to your source document.

**Comment by manuelfuenmayor** [comment]
@opoudjis, I see what happened here:
If the markup contains a white space at the beginning, the backslash will appear.
E.g. ` \<< this-is-not-an-xref>>` (note the white space before "this-...")

But I realize that in this case the backslash is not needed since the result will be in plain text.
So, this is just a confusion of mine. The rendering works as it should. Thank you.
