### ISSUE TITLE
The directive "[plantuml]" will lead to redundant "@startuml" and "@enduml" in resulting .pml files

### ISSUE THREAD

**Issue by PeterTKY** [metanorma/metanorma-standoc#79]
It will happen when "@startuml" and "@enduml" have already been in the WSD file being included. Having "@startuml" and "@enduml" in WSD files is expected to comply with the plantuml WSD schema. Therefore, the plantuml plugin should detect them and avoid them being redundant.

**Comment by opoudjis** [comment]
Fixed redundant addition: code error.
