### ISSUE TITLE
Math: Matrix unexpected rendering in DOC output

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#791]
*In relation to https://github.com/metanorma/pdfa-iso-32000-2/issues/5*

```adoc
[stem%unnumbered]
++++
[(a,b,0),(c,d,0),(e,f,1)]
++++
````

Generated DOC:
![issue13-generated-doc](https://github.com/metanorma/metanorma-standoc/assets/33627611/1a31a031-b193-4835-a3d9-18241cc085d9)

Original:
![issue13-original](https://github.com/metanorma/metanorma-standoc/assets/33627611/6288c770-fa92-4781-ac43-195b768c75ff)

**Comment by ronaldtse** [comment]
@manuelfuenmayor can you confirm that this is not a plurimath issue? If it is please post it there. Thanks.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, the other outputs show the equation correctly. For example, for PDF:
![issue13-generated-pdf](https://github.com/metanorma/metanorma-standoc/assets/33627611/70ad8f24-74c4-4afe-9ebc-8567118190f2)

**Comment by manuelfuenmayor** [comment]
Apparently, this issue is more generic:
![issue18-generated](https://github.com/metanorma/metanorma-standoc/assets/33627611/3a1ef0ba-dd12-4afb-98ce-ac83d4ce3a51)

**Comment by ronaldtse** [comment]
> the other outputs (HTML, PDF) render the equation correctly. For example, for PDF:

@manuelfuenmayor actually Plurimath renders into these languages used by different formats:
* PDF / HTML : MathML
* Word: OMML

It is rather clear here that the OMML output may be problematic.

**Comment by manuelfuenmayor** [comment]
Ah, I see.
Should I move this issue to Plurimath repository, then?

**Comment by ronaldtse** [comment]
@manuelfuenmayor let's keep this issue and then make a new ticket in Plurimath, thanks!

**Comment by opoudjis** [comment]
@manuelfuenmayor Can this issue be closed?

**Comment by manuelfuenmayor** [comment]
@opoudjis, when I compile the equation sample presented above, I get this error from the word output:

![Screenshot 2023-12-18 214603](https://github.com/metanorma/metanorma-standoc/assets/33627611/cbed0911-67f1-4d29-9f04-494dc7a4c0b7)

Test file: [tests.zip](https://github.com/metanorma/metanorma-standoc/files/13710145/tests.zip)

**Comment by opoudjis** [comment]
I guess that would be a no...

**Comment by opoudjis** [comment]
So the Word matrix expression is still crashing Word; confirmed behaviour.

**Comment by opoudjis** [comment]
Whatever was done in https://github.com/plurimath/plurimath/issues/164 did not address this issue. I'm reopening it.

**Comment by opoudjis** [comment]
Found, it's a Plurimath bug.

**Comment by opoudjis** [comment]
![Screenshot 2023-12-20 at 01 08 18](https://github.com/metanorma/metanorma-standoc/assets/1911039/3a6ab53d-4508-4a45-aaec-c042267fda3b)
