### ISSUE TITLE
DOC: Paragraph separation after table is too small

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#792]
*In relation to https://github.com/metanorma/pdfa-iso-32000-2/issues/5*

Original:
![issue19-original](https://github.com/metanorma/metanorma-standoc/assets/33627611/7c232c7b-43f6-493e-95a9-ccac78c57d0b)

Generated:
![issue19-generated-doc](https://github.com/metanorma/metanorma-standoc/assets/33627611/31c3bfd3-210c-42aa-be76-5c149be0ecb9)

**Comment by opoudjis** [comment]
I would like confirmation before I action, @ronaldtse 

If I put a mandatory space between all tables and following paragraphs, that really will be universal across Metanorma, and it will not be possible to have cases where there is no spacing.

I can do one of the following:

* Always add space after table in Word, no-space is likely an edge case if not an error.
* Add space by default, have a table option which suppresses that space on request.
* Leave as is, people must add space manually by inserting an extra paragraph.

Which of these should I do?

**Comment by ronaldtse** [comment]
> * Leave as is, people must add space manually by inserting an extra paragraph.

What exactly does this mean? What does @manuelfuenmayor need to do here to achieve this effect?

The real question is that I don't see a case where after a proper table element ("Table" element) it is not a new paragraph.

It is only if a table is placed inline, no numbering and caption, then the extra paragraph is not desired. 

Thoughts?

**Comment by opoudjis** [comment]
> What exactly does this mean? What does @manuelfuenmayor need to do here to achieve this effect?

Insert a paragraph containing `{blank}` or `&#xa0;`

> The real question is that I don't see a case where after a proper table element ("Table" element) it is not a new paragraph.

> It is only if a table is placed inline, no numbering and caption, then the extra paragraph is not desired.

When you put it like that, I agree it's pathological. OK, mandatory space.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !

**Comment by opoudjis** [comment]
There is CSS in the Word document that is supposed to be addressing this:

````
div.table_container {
  margin-bottom: 14pt;
} 
````

Need to investigate why it is being ignored.

**Comment by opoudjis** [comment]
Putting space before the CSS command was enough to make it work.
