### ISSUE TITLE
Inline stem equations are center-aligned in DOC

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#793]
This:
```adoc
Nominally, a gray level is the complement of the black component of _CMYK_.
Therefore, the _CMYK_ colour value equivalent to a specific gray level shall be

stem:["cyan" = 0.0] +
stem:["magenta" = 0.0] +
stem:["yellow" = 0.0] +
stem:["black" = 1.0 - "grey"]
````

renders:
![issue17-generated](https://github.com/metanorma/metanorma-standoc/assets/33627611/9e79342e-a289-40db-b97c-18ec8610cae3)

`stem[...]` expressions should be left-aligned.

**Comment by opoudjis** [comment]
I would call this a Word bug, but I have to address it anyway:

When a paragraph consists of only stem expressions, and is justified, Word makes it centered. I need to make it explicitly left-aligned for it to render correctly. Of course, justification is almost always meaningless for stem expressions.
