### ISSUE TITLE
Incorrect image path for "[plantuml]" directive

### ISSUE THREAD

**Issue by PeterTKY** [metanorma/metanorma-standoc#80]
Right now with the "[plantuml]" directive, it will attempt to include generated png images from the path "./images/plantuml". But actually those images will be sitting at "./plantuml", so it always results in error for the including of the image.

**Comment by opoudjis** [comment]
There was a recent code change that may have resolved this: https://github.com/metanorma/metanorma-standoc/issues/77

If you have not updated metanorma-standoc, please do. The code changes rapidly, and gems are released fortnightly.

For all bug reports, include the documents causing the issue, so I can try to replicate these.

**Comment by PeterTKY** [comment]
Just updated to the newest version of metanorma-standoc. I saw that the plantuml directory has been moved inside /sources, but the incorrect image path issue still exists.

The generated .pml and .png files are sitting at "sources/plantuml" now, but it is expecting "sources/images/plantuml/*.png". Therefore, it's causing:
`Error: No such file or directory @ rb_sysopen - sources/images/plantuml/9.png`

**Comment by opoudjis** [comment]
@PeterTKY, you have still failed to tell me which document this is in, or how to replicate this. I am going to assume that this is csd-digital-addresses, as Ronald indicated to me, and you've inserted a symbolic link, so it was hard for me to work out what was going on. Please be more helpful with debugging requests.

You're using the Asciidoctor `:imagesdir:`, and I've been caught unawares by that: the plantuml images have been put in the plantuml directory, but the `:imagesdir:` directory has not been prefixed to that destination. The plantuml macro will need to move its output to the `:imagesdir:`, if present.

Metanorma should never have even been run on a file outside of the working directory. This project's pursuit of flexibility has been making my life needlessly unpleasant.

**Comment by opoudjis** [comment]
Note that the bugfixes for these will not be available until the next gem release of the Metanorma stack, which I intend to do end of week.

**Comment by ronaldtse** [comment]
I've updated the comment about Metanorma running outside the working directory. The working directory has *nothing* to do with the location of the entry file path; the context should not be assumed.

**Comment by PeterTKY** [comment]
> @PeterTKY, you have still failed to tell me which document this is in, or how to replicate this. I am going to assume that this is csd-digital-addresses, as Ronald indicated to me, and you've inserted a symbolic link, so it was hard for me to work out what was going on. Please be more helpful with debugging requests.
> 
> You're using the Asciidoctor `:imagesdir:`, which is obligatorily prefixed to all images, and I've been caught unawares by that: the plantuml images have been put in the plantuml directory, but the `:imagesdir:` directory has not been prefixed to that destination. The plantuml macro will need to move its output to the `:imagesdir:`, if present; if not, it will leave it in the `plantuml` directory.

@opoudjis , the repo @ronaldtse showed you was not meant solely to help you debug but a REAL one we are working on using the metanorma stack. However, we suffered a lot by that bug, which we shouldn't have been, and we had to workaround that by providing the symbolic link. It was not a very pleasant experience.

I have been believing you a lot, and I provided you very precise path of that problematic image. It should have been more than enough to fix the bug for any experienced developer. But it's looking right now next time I have to provide even more details.

Thanks for letting me know your difficult on all these! I will be more than happy to tell you more details next time.

**Comment by ronaldtse** [comment]
It's all about communication and context. We're all working towards the same goal, so let's stay friendly. :wink:

**Comment by PeterTKY** [comment]
I have always been friendly. I will be if everybody in the team will be.

**Comment by ronaldtse** [comment]
Thanks @PeterTKY !

**Comment by PeterTKY** [comment]
And I won't forget to provide MORE details than usual ;)
