### ISSUE TITLE
Blockquote not rendering correctly

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#807]
This markup:
```adoc
[quote,Captain James T. Kirk,Star Trek IV: The Voyage Home]   
Everybody remember where we parked.
````

renders in NIST:
![issue1-nist](https://github.com/metanorma/metanorma-standoc/assets/33627611/b6e1bcf5-5d0d-4ebb-a570-61999702c269)

For some reason, this markup generates a crossreference error:

````
Crossreferences: (XML Line 000022): Star Trek IV: The Voyage Home does not have a corresponding anchor ID in the bibliography!
````

In normal AsciiDoc, this markup renders:
![issue1-asciidoc](https://github.com/metanorma/metanorma-standoc/assets/33627611/8cf9fc7c-130a-427d-84ea-66d61253611b)

File samples: [blockquote_sample.zip](https://github.com/metanorma/metanorma-standoc/files/12254731/blockquote_sample.zip)

**Comment by opoudjis** [comment]
Metanorma does NOT follow Asciidoctor's slovenly ways about references. It demands that any reference in a Metanorma blockquote, as the third positional attribute, be a real citation, that shows up in the bibliography, and not just an unreferenced random title.

https://www.metanorma.org/author/topics/document-format/text/#block-quotes

Metanorma, very simply, WILL NOT generate a citation that looks like the above. If you want results like Asciidoc, you will need to put them in the author field, the second argument, and escape the quote marks:

````
[quote, "The Ware Report, \"Defense Science Board Task Force on Computer Security, 1970\""]
____
Providing satisfactory security controls in a computer system is... a
system design problem. A combination of hardware, software, communications,
physical, personnel and administrative-procedural safeguards is required
for comprehensive security….software safeguards alone are not sufficient.
____ 
````
