### ISSUE TITLE
Misplaced entries in (BSI) Table of Contents

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma-standoc#816]
Source: https://github.com/metanorma/mn-samples-bsi/pull/304

Only in HTML output:
![issue3-html](https://github.com/metanorma/metanorma-standoc/assets/33627611/224790cc-aed1-4aa6-8ab9-a5fb4f004231)

**Comment by opoudjis** [comment]
Fixed in https://github.com/metanorma/metanorma-ogc/issues/597

![Screenshot 2023-11-12 at 17 16 50](https://github.com/metanorma/metanorma-standoc/assets/1911039/bbacdced-19b3-4bc0-911a-f37577eabf32)
