### ISSUE TITLE
Numbering entry notes with `%termnote`

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#819]
Entry notes are not numbered when `[NOTE%termnote]` is applied. This becomes an issue when there are multiple entry notes in amendments, or when a single entry note is numbered.

Examples from ISO 19111:2019 Amendment 2:
![image](https://github.com/metanorma/metanorma-standoc/assets/55683568/2bcf41b9-9a21-4676-85bc-21c623a025b8)
![image](https://github.com/metanorma/metanorma-standoc/assets/55683568/13f4e422-269a-441d-9505-2b6b45756aae)

Generated:
![image](https://github.com/metanorma/metanorma-standoc/assets/55683568/527308ec-e07d-41b5-9532-b08b7e1484c0)
![image](https://github.com/metanorma/metanorma-standoc/assets/55683568/c1d7ecb6-a34f-4957-98c4-32056b9b45c3)

Using `autonumber` does not work in the quote environment, and in this case, it does nothing when it is used before the quote environment.

**Comment by opoudjis** [comment]
Yeah, I know what's happening: when there is only one termnote, Metanorma is taking over and saying "ha, there's only one of these, why would you need to number them at all?" I'll need to work around that (turn that check off in autonumber mode.)

**Comment by opoudjis** [comment]
I can't replicate this. i've just used autonumber (outside the quotes), as:

````
[change=delete,locality="clause=3.1.16"]
== 3.1.16, datum ensemble

In EXAMPLE, remove right parenthesis after "...and G1762." The complete revised
definition becomes:

autonumber:termnote[1]

____
*3.1.16* +
*datum ensemble* +

....
____

[change=modify,locality="clause=3.1.31"]
== 3.1.31, geodetic coordinate reference system

Replace definition with

autonumber:termnote[1]

____
*3.1.31* +
*geodetic coordinate reference system* +

....

____

````

and I'm getting the expected rendering:

<img width="835" alt="Screenshot 2023-10-02 at 23 04 07" src="https://github.com/metanorma/metanorma-standoc/assets/1911039/ed5419c5-5e6d-466b-931f-bc16f54ea188">

I suspect you weren't using "termnote" to name the assets.
