### ISSUE TITLE
Incorrect images included in documents using the [plantuml] directive

### ISSUE THREAD

**Issue by PeterTKY** [metanorma/metanorma-standoc#83]
It can be reproduced at https://github.com/CalConnect/csd-digital-addresses, which @opoudjis has access. Simply `make` will do.

After the `make` you will see in "sources/models/adoc/*.adoc":
In AddressProfile.adoc
`[plantuml]
....
include::../plantuml/AddressProfile.wsd[]
....`

In AddressFeature.adoc
`
[plantuml]
....
include::../plantuml/AddressFeature.wsd[]
....
`

In all these "sources/models/adoc/\*.adoc" files, they include different "../plantuml/\*.wsd" files. However, when they are compiled into documents, we can see all the corresponding images become "sources/plantuml/9.png". In other words, the same image is included in the document compiled for different "\*.wsd" files (please open documents/\*.doc for verification).

**Comment by opoudjis** [comment]
The file name is generated currently as the line number that the PlantUML occurs in, but of course since you have multiple files being included, the file name is no longer unique. I will use a GUID instead.
