### ISSUE TITLE
PlantUML should use "output switch" instead of "moving files"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#84]
https://github.com/metanorma/metanorma-standoc/blob/dc0cfe23cdbc6493668a8b209863e3d027f97121/lib/asciidoctor/standoc/macros.rb#L85-L107

1. Use the PlantUML "output switch" to generate files in correct directory.

From http://plantuml.com/command-line :
> Output Directory
>
> You can specify an output directory for all images using the -o switch:
>
>java -jar plantuml.jar -o "c:/outputPng" "c:/directory2"
>If you recurse into several directory, there is a slight difference if you provide an absolute or a relative path for this output directory.
>
>* absolute path: An unique output directory will be used, with all images generated inside
>* relative path: Several output directories will be used across the file tree.
 
2. Use `Pathname` for file paths (and joins of them) for Windows compatibility.

**Comment by opoudjis** [comment]
The code ends up more complicated if I try to infer the destination directory ahead of time; I am trying to deal with the unwelcome use of `:imagesdir:`, which is propagated into the source URI, and that is the only place I know it from. Sugggestion 1 rejected. 

Implementing suggestion 2.
