### ISSUE TITLE
Allow some markup options in reviewer notes

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#842]
Can some markup options, such as items lists, be enabled for the reviewer notes?

Model International Standard ISO 17301-1 contains comments in the following form:
![image](https://github.com/metanorma/iso-2533/assets/55683568/91b8933e-4a47-461e-b7ae-f9962607e1a6)

They are now rendered as follows:
![image](https://github.com/metanorma/iso-2533/assets/55683568/b9009d8a-09e7-4b9b-a4bb-6c6a71fc5e91)

Corresponding markup used for this comment was:
````
[reviewer=ISO,from=scope,to=scope]
****
* Mandatory clause
* Defines the subject of the document
* Used as a summary for the abstract
** ISO/IEC Directives, Part 2, 2021, Clause 14
****
````

**Comment by ronaldtse** [comment]
I guess these are “annotations”?

We don’t need to render them in the same way but they would be useful to be encoded.

**Comment by opoudjis** [comment]
The markup is being processed fine in Presentation XML

````
<review id="_6cdc7905-52e9-792a-cd6d-eb66ad6782ff" reviewer="ISO" date="2023-12-19T00:00:00Z" from="cl1" to="cl1"><ul id="_f0971edb-8922-0c00-455f-c29aa0b26721"><li><p id="_c8a5e2b7-aabd-32bb-48ae-9e83befcbece">Mandatory clause</p>
</li>
<li><p id="_0f4100e2-e40b-14b5-d0fc-96c588d75c91">Defines the subject of the document</p>
</li>
<li><p id="_1476525f-9f86-6aaa-591f-0434326bfbc9">Used as a summary for the abstract</p>
<ul id="_b3c044e5-ac10-79a9-6e67-f12111c0c37a"><li><p id="_3d5fb026-c318-e916-f182-8b7fbbb244bb">ISO/IEC Directives, Part 2, 2021, Clause 14</p>
</li>
</ul>
</li>
</ul>
</review>
````

and in Word:

![Screenshot 2023-12-19 at 22 25 33](https://github.com/metanorma/metanorma-standoc/assets/1911039/d2783f51-4ffc-4820-be31-c9dd24233386)

So this too is a PDF-specific issue.

**Comment by opoudjis** [comment]
[Archive 3.zip](https://github.com/metanorma/metanorma-standoc/files/13714995/Archive.3.zip)

**Comment by Intelligent2013** [comment]
Generated XFDF contains paragraphs `p`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xfdf xmlns="http://ns.adobe.com/xfdf/">
	<annots>
		<text color="#FFC333" opacity="0.600000" flags="nozoom,norotate" date="2023-12-19T00:00:00Z" page="4" rect="70.866,89.076" title="ISO">
			<contents-richtext>
				<body xmlns="http://www.w3.org/1999/xhtml">
					<p dir="ltr">Mandatory clause</p>
					<p dir="ltr">Defines the subject of the document</p>
					<p dir="ltr">Used as a summary for the abstract</p>
					<p dir="ltr">ISO/IEC Directives, Part 2, 2021, Clause 14</p>
				</body>
			</contents-richtext>
			<popup flags="nozoom,norotate" open="yes" page="4" rect=""/>
		</text>
		<text color="#FFC333" opacity="0.600000" flags="nozoom,norotate" date="2023-12-19T00:00:00Z" page="5" rect="249.809,91.709" title="ISO">
			<contents-richtext>
				<body xmlns="http://www.w3.org/1999/xhtml">
					<p dir="ltr">ISO/IEC Directives, Part 2, 2021, Clause 19</p>
				</body>
			</contents-richtext>
			<popup flags="nozoom,norotate" open="yes" page="5" rect=""/>
		</text>
	</annots>
</xfdf>
```
but Adobe Acrobat renders as plain text:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/4db46346-230f-4561-8aa5-e42f5ffe5ea1)

**Comment by Intelligent2013** [comment]
From PDF spec:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/7ec7b15c-d110-4c39-a977-6c3293ecf6f8)

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/mn2pdf/releases/tag/v1.81.

![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/362ebde2-0011-4cae-88f8-d499775222c8)
