### ISSUE TITLE
Reviewer notes do not get generated when annex anchors are used

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-standoc#844]
Reviewer notes do not get generated at all in case the source .adoc file contains a reviewer note that has `from` and/or `to` anchor set to an anchor of some annex.

For example, if the following is used, the PDF output will contain no comments at all:
````
[[anc1]]
[appendix]
== annex

[reviewer=ISO,from=anc1,to=anc1]
****
* ISO/IEC Directives, Part 2, 2021, Clause 19
****
````

**Comment by Intelligent2013** [comment]
ISO XSLT updated, but can't be updated in metanorma-iso gem due the error (https://github.com/metanorma/mn-native-pdf/actions/runs/7323939034/job/19947018928)
```
Installing fontist 1.17.1
Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to
underlying error <bad response Forbidden 403
(https://rubygems.org/gems/expressir-1.3.0-x86_64-linux.gem)>
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.22/lib/bundler/rubygems_integration.rb:497:in
`rescue in download_gem'
```

Will try again later.

**Comment by anermina** [comment]
Thank you, @opoudjis and @Intelligent2013 !

**Comment by Intelligent2013** [comment]
ISO XSLT updated in metanorma-iso repository.
