### ISSUE TITLE
rspec versioning failing on GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#846]
https://github.com/metanorma/metanorma-standoc/actions/runs/7247192029/job/19745338301?pr=845

````
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: rspec (>= 0) and rspec (~> 3.6). Bundler cannot continue.
````

**Comment by opoudjis** [comment]
I was going to to do releases today, so as not to bother you on Gregorian Christmas.

However, all the flavours after standoc have had their releases fail, because of this issue (and the insistence that GHA pass before release). 

At least metanorma-iec has failed because of Expressir installation on GHA.

... The releases are all ready on my side, but I have to pass this now on to you to resolve...

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis just finished update our gems based on list in https://github.com/metanorma/metanorma-release

I observed a new issue related to expressir installation on ruby 2.7 https://github.com/metanorma/metanorma-iso/actions/runs/7286474150/job/19855266937

Should we still keep ruby 2.7 in our matrix?

**Comment by ronaldtse** [comment]
@CAMOBAP I believe @maxirmx will be fixing the Ruby 2.7 issue of Expressir...
