### ISSUE TITLE
Specification of `custom-charset-font` using the semicolon delimiter `;` leads to crash

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#849]
In:
* https://github.com/metanorma/pdfa-iso-32000-2/issues/10

We need to use multiple different fonts for different charsets to render PUA glyphs. It is unclear whether the `,` comma or the `;` semicolon is used for delimiting the fonts.

This works:
```adoc
:fonts: D050000L;TeXGyreTermes
:presentation-metadata-custom-charset-font: dingbats:"D050000L",agl:"TeXGyreTermes"
```

This crashes:
```adoc
:fonts: D050000L;TeXGyreTermes
:presentation-metadata-custom-charset-font: dingbats:"D050000L";agl:"TeXGyreTermes"
```

This causes Metanorma to misrecognize `dingbats:"D050000L";agl:"TeXGyreTermes"` as a single font.

**Comment by opoudjis** [comment]
The documentation says explicitly presentation-metadata-custom-charset-font is comma-delimited:

https://www.metanorma.org/author/topics/inline_markup/text_formatting/#custom-character-sets

> In order to be rendered, a font implementing that interpretation needs to be indicated as a processing hint for Metanorma. This is done with the Presentation XML metadata directive :presentation-metadata-custom-charset-font: {name of interpretation}:"{name of font}", as a document attribute, giving a comma-delimited list of charset-font pairs.

and that :fonts: is semicolon-delimited:

https://www.metanorma.org/author/ref/document-attributes/#visual-appearance

> Semicolon-delimited listing of fonts to be used for this document, in addition to the fonts predefined for the flavour
