### ISSUE TITLE
Tests should fail when `java: not found`

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-standoc#86]
Improve exception handling https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/validate.rb#L43

**Comment by CAMOBAP** [comment]
Tests passed successfully if java, not found

```
...
..........asciidoctor: WARNING: <stdin>: line 6: section title out of sequence: expected level 1, got level 2
[relaton] cache /root/.relaton/cache/iec/: version is obsolete and cache is cleared.
Jing failed with error: sh: 1: java: not found


Finished in 6.78 seconds (files took 3.38 seconds to load)
95 examples, 0 failures
```

**Comment by CAMOBAP** [comment]
As far as I see the validation is optional so this is correct behavior, @opoudjis @ronaldtse can you confirm?

**Comment by opoudjis** [comment]
Hm. @ronaldtse should make the call. FWIW: we don't officially say that validation is optional, but in practice, I'm ok with execution continuing if Java is not found.

**Comment by ronaldtse** [comment]
@CAMOBAP Java is a requirement of the system because PDF generation requires it. We should fail the tests if Java is not found. There must be some mechanism to ensure Java exists in running Ruby code? Can you help find some existing code that does that?

**Comment by ronaldtse** [comment]
@CAMOBAP is this completed and to be closed? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse yep it's implemented https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor/standoc/validate.rb#L84

**Comment by ronaldtse** [comment]
Thanks!
