### ISSUE TITLE
Chocolatey fallen over on Github Actions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#866]
https://github.com/metanorma/metanorma-standoc/actions/runs/7957667089/job/21720937727
https://github.com/metanorma/isodoc/actions/runs/7957590917

````
Installing the following packages:
inkscape
By installing, you accept licenses for the packages.
Invalid credentials specified.
Please provide credentials for: https://community.chocolatey.org/api/v2/
User name: Password: Chocolatey had an error on fv-az972-285 (with user runneradmin):
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
````

And yes, I have rerun the jobs.

**Comment by opoudjis** [comment]
This, once again, is messing up my release, by preventing autorelease of gems for no acceptable reason, and I am going to force release all gems to get through tonight. Which will mess up the docker release process, but as I have advised you the last three times a Github Actions  dependency has fallen over during Metanorma release, I no longer give a damn.

I do not know, @CAMOBAP @ronaldtse, what it is going to take to make Github Actions acceptably stable enough to be useful, but it clearly is NOT, and it has not been for years. Every second release is falling over on some gem dependency or other, and compromising the release process.

Perhaps consider doing daily automated runs of Github Actions on a gem with strong dependencies, such as standoc, to monitor dependencies. But I should not have to deal with this nonsense every month, and I should not have to find out that something has fallen over in Github Actions on release day.

**Comment by CAMOBAP** [comment]
On it

**Comment by opoudjis** [comment]
It is.

**Comment by opoudjis** [comment]
Issue appears to have gone away in the last gem released, 

https://github.com/metanorma/metanorma-bipm/actions/runs/7959648343

**Comment by CAMOBAP** [comment]
yep, it's chocolatey infrastructure issue, I'm looking for a way to cache packages locally to avoid such problems in future

**Comment by CAMOBAP** [comment]
Chocolatey cache added for all our worflows in `ci` repo https://github.com/metanorma/ci/pull/152

**Comment by opoudjis** [comment]
It has come back:

https://github.com/metanorma/isodoc/actions/runs/8079275539/job/22073356665?pr=562

````
Chocolatey v2.2.2
Installing the following packages:
inkscape
By installing, you accept licenses for the packages.

InkScape v1.3.0 [Approved]
InkScape package files install completed. Performing other installation steps.
WARNING: No registry key found based on  'InkScape*'
Installing 64-bit InkScape...
WARNING: Something is wrong with the install log location specified. Please fix this in the package silent arguments (or in install arguments you specified). The directory specified as part of the log file path must exist for an MSI to be able to log to that directory. This is most likely an issue with the 'InkScape' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\InkScape\tools\inkscape-1.3_2023-07-21_0e150ed6c4-x64_31XBEKV.msi" /qn /norestart /l*v "vendor/choco\InkScape.1.3.0.MsiInstall.log" ] was not successful. Exit code was '1622'. Exit code indicates the following: Something is wrong with the install log location specified. Please fix this in the package silent arguments (or in install arguments you specified). The directory specified as part of the log file path must exist for an MSI to be able to log to that directory. This is most likely an issue with the 'InkScape' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The install of InkScape was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\InkScape\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
````

**Comment by opoudjis** [comment]
inkscape now compromised on OSX as well:

https://github.com/metanorma/isodoc/actions/runs/8134185809/job/22226775985

`/usr/share/inkscape/extensions/eps_input.inx doesn't exists. Skip`

And Windows inkscape is not installing at all in GHA as of today.

**Comment by opoudjis** [comment]
OSX issue seems to have gone away from this morning's run...

**Comment by opoudjis** [comment]
OSX issue has come back:

https://github.com/metanorma/isodoc/actions/runs/8170586998/job/22337018816?pr=564

````
Error: Download failed on Cask 'inkscape' with message: Download failed: https://media.inkscape.org/dl/resources/file/Inkscape-1.3.2_x86_64.dmg
{}
Command HOMEBREW_CASK_OPTS='--no-quarantine' brew install --cask inkscape FAILED!
````

**Comment by opoudjis** [comment]
Is still an issue with both isodoc and metanorma:

https://github.com/metanorma/metanorma/actions/runs/8222284986/job/22483600609
https://github.com/metanorma/isodoc/actions/runs/8222170747

**Comment by opoudjis** [comment]
Well one thing I am going to say, @CAMOBAP : isodoc releases on push version, regardless of whether it passes rspec, because of the intolerable and ongoing delays on GHA. This needs to be the case with standoc as well, especially as its GHA execution is constantly hostage to fragile external dependencies. (In fact, I thought it was, but it isn't this run.)

**Comment by opoudjis** [comment]
This is still not fixed: https://github.com/metanorma/isodoc/actions/runs/8249423682

**Comment by opoudjis** [comment]
Seems to be fixed, closing.
