### ISSUE TITLE
Chore: force fetch of relaton index in spec

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#867]
Reflecting debugging we've had to do for metanorma-ieee:

For any test file including VCR and relaton in the Metanorma suite:

````
before do
  allow_any_instance_of(Relaton::Index::FileIO).to receive(:check_file).and_return(nil)
end
````

> this should force Relaton::Index to make index request regardless cached it or no

Index fetches out of sequence are causing unforeseen discrepancies between local environment processing of Relaton under VCR, and Github Actions runs.

In addition, will start wiping ~/.relaton and all VCR cassettes before each release, to force refetch of all relaton records, given discrepancies introduced between relaton releases. `bundle exec relaton db clear` is not enough at the moment, because NIST fetches are currently cached separately. @andrew2net will fix that in time.

**Comment by andrew2net** [comment]
@opoudjis I've tried this approach in Relaton and made some corrections. To force fetching indexes use:
```ruby
before do
  # Force to download index file
  allow_any_instance_of(Relaton::Index::Type).to receive(:actual?).and_return(false)
  allow_any_instance_of(Relaton::Index::FileIO).to receive(:check_file).and_return(nil)
end
```
To force fetching NIST pubs-export dataset use:
```ruby
before do
  # Force to download pubs-export.zip
  allow(File).to receive(:exist?).with(RelatonNist::PubsExport::DATAFILE).and_return false
  allow(File).to receive(:exist?).and_call_original
end
```
