### ISSUE TITLE
Reference rendering no longer shows all title parts?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#87]
This is from a metanorma-itu document:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/11865/61432276-7537ef80-a962-11e9-92ea-4c70157dde68.png">

The first two entries are manual. The rest are auto-fetched. The auto-fetched ones are missing the "title-intro" and "title-parts".

The document in question is https://github.com/CalConnect/csd-timezone-model

**Comment by opoudjis** [comment]
This issue was fixed in https://github.com/metanorma/metanorma-iso/issues/272, but I am checking that all three parts of the title are being added when needed.

**Comment by opoudjis** [comment]
They are being concatenated naively, and not in the right order in relaton-iso-bib:

`titles.map { |t| t.title.content }.join(" - ")`

titles is being built in the order main - intro - part, instead of intro - main - part.

**Comment by ronaldtse** [comment]
This leads me to a question: is this supposed to be done in metanorma-iso or relaton-iso? I thought we wanted a fully rendered string in Relaton data to allow easy rendering of the title?

**Comment by opoudjis** [comment]
That is supposed to be done in relaton-iso-bib, and that's where I'm fixing it.

**Comment by ronaldtse** [comment]
Got it, thanks.
