### ISSUE TITLE
Release standoc automatically

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#881]
I have asked for this before, and I'm asking for this again.

At the moment the isodoc gem is released by GHA on push of a release, without waiting for it to pass the GHA tests, in order to make the release process tractable, and avoid a half hour of dead time.

This needs to be extended to metanorma-standoc. Gems, starting with metanorma-iso, rely on changes in both isodoc and metanorma-standoc, and the fact that the metanorma-standoc updates are not available to the test run of metanorma-iso means that tests incorrectly fail. That is forcing me to do manual releases, which defeats the entire purpose of running those tests to begin with.

I won't insist on the same happening for metanorma-iso, even though it is presupposed for several gems, because I can delay testing and releasing those gems to the end. But I need this in place for metanorma-standoc. Releases are routinely being disrupted because of it.

**Comment by CAMOBAP** [comment]
> I have asked for this before, and I'm asking for this again.

I apologize for missing/ignoring the original request, I confirm the issue on `isodoc` repo

Doublechecking other repos too to fix it ASAP

**Comment by CAMOBAP** [comment]
From my list there was: ammitto,bipm-data-importer,gb-agencies,html2doc,iev,isodoc-i18n,isodoc,isoics,metanorma-gb,metanorma-plugin-datastruct,metanorma-plugin-lutaml,metanorma-utils,metanorma-vg,metanorma,mn-requirements,reeper,reverse_adoc,stepmod-utils

All of them were updated, and release will happens after tests passed

**Comment by opoudjis** [comment]
Um, just to make sure: my desired behaviour was that release happen WITHOUT testing on standoc, just as it is with isodoc. Is that what you've realised? Because they're both infrastructure gems, waiting on testing to release them delays the entire release. So my request was to release standoc without prior testing, not to make isodoc released after prior testing...

**Comment by opoudjis** [comment]
Cool, thank you very much!
