### ISSUE TITLE
Do not preprocess links in PlantUML blocks

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#884]
From https://github.com/metanorma/metanorma/issues/356

Well, I have updated plantuml to latest (at the moment `PlantUML version 1.2024.3 (Thu Feb 15 19:40:05 UTC 2024)`) available in `metanorma/metanorma:main`, but this doesn't resolve the problem.

After looking in the deep, json getting corrupted during `asciidoctor` preprocessing, namely it becomes:

```
@startuml
allowmixing

json Template {
	"action": "com.joesphoto.filter",
	"description": "Magic Filter",
	"digitalSourceType": "link:++http://cv.iptc.org/newscodes/digitalsourcetype/compositeSynthetic"++[],
	"softwareAgent" : [{
		"name": "Joe's Photo Editor",
		"version": "2.0",
		"schema.org.SoftwareApplication.operatingSystem": "Windows 10"
	}]
}
@enduml
```

i.e. `link:++{}++[]` append to `digitalSourceType` value

### Workaround

A single workaround that was found is to preprocess link ahead i.e.:

```
"digitalSourceType": "+http://cv.iptc.org/newscodes/digitalsourcetype/compositeSynthetic+",
```

@lrosenthol will this workaround acceptable for you

---

It looks to me that we should forbid `asciidoc` 'preprocessing' in `[plantuml]` blocks?

**Comment by opoudjis** [comment]
There is a general issue of plugins clashing with each other, and I don't know that I can address that. The link preprocessor knows to skip source markup, and it knows about `source|listing|literal|pass`. I can add plantuml to that, but I will see if there are more general solutions, maybe including block-level processing, or reordering the plugins.

**Comment by ronaldtse** [comment]
> It looks to me that we should forbid `asciidoc` 'preprocessing' in `[plantuml]` blocks?

Definitely. AsciiDoc preprocessing should not happen in any `source`-type blocks, even for YAML...

**Comment by opoudjis** [comment]
Actually, this is simpler than that. I forgot to tell the Link preprocessor that `....` is a literal delimiter, to be treated like `----` for source code.

Tested and confirmed working with @lrosenthol ’s sample PlantUML.
