### ISSUE TITLE
External links should be relative links

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#897]
From: https://github.com/metanorma/annotated-express-report/issues/17

This is the source for this issue:
```adoc
===== Method Definition Schema

* Annotated EXPRESS schema: link:method_definition_schema/method_definition_schema.exp[]
```

Notice how there are 2 problems:
1. The PDF link became an absolute path. It should always be relative to the PDF file itself.
2. The path is also wrong. The path was meant to be relative from the source text file, which is located at `sources/report-pdf-latex-validation/10303-49/10303-49.adoc`

<img width="815" alt="Screenshot 2024-07-25 at 10 44 49 AM" src="https://github.com/user-attachments/assets/e02d1891-24e9-4dd6-85fc-8f54c768f23a">

**Comment by opoudjis** [comment]
> The PDF link became an absolute path. It should always be relative to the PDF file itself.

Untrue. The link, both in PDF and HTML, is the relative link method_definition_schema/method_definition_schema.exp , not the absolute link /method_definition_schema/method_definition_schema.exp

**Comment by opoudjis** [comment]
This issue reflects a design constraint of Asciidoctor, that was already recorded in https://github.com/metanorma/metanorma-standoc/issues/802: this is an included document in a subdirectory, and Asciidoctor does not rewrite links to assets, be they images or other documents, in subdirectories. This was raised a decade ago in Asciidoctor, and it has not been addressed; see e.g. https://github.com/asciidoctor/asciidoctor/issues/1903 https://github.com/asciidoctor/asciidoctor/issues/3603 . The latest is that if it is addressed at all, it will be addressed in a new subdocument macro, in at least the second iteration of the AsciiDoc Language specification.

I am absolutely not going to reimplement Asciidoc includes preprocessing. I was unable to do so last year with embeds. I will not be addressing this.
