### ISSUE TITLE
Are jobs being run on rake workflow?

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#906]
If you look at

https://github.com/metanorma/metanorma-standoc/actions

Jobs are being run for the past three days, since https://github.com/metanorma/metanorma-standoc/pull/904, in seconds rather than the expected 8 minutes; so the versioned rake job

https://github.com/metanorma/metanorma-standoc/actions/runs/10242440927

only involved one job, not the standard 12 of the environment permutations. It looks like testing is being skipped on the rake workflow.

This is not happening to isodoc, the other gem releasing without testing:

https://github.com/metanorma/isodoc/actions/runs/10242154911

The isodoc latest version rake job took 13 mins to run, as is normal.

**Comment by CAMOBAP** [comment]
Good catch! I see the problem the fix is on the way

**Comment by CAMOBAP** [comment]
Done, fix on metanorma/ci side, I will close after next successful cron run

**Comment by opoudjis** [comment]
Hasn't succeeded tonight: https://github.com/metanorma/metanorma-standoc/actions/runs/10264115878

**Comment by CAMOBAP** [comment]
This specific case happens because the tag was pushed on this commit.

I.e. on other repos when the tag pushed workflow starts twice for commit and for tag. And we ave special check to skip run for push commit an run it only on tag

Because for `isodoc` and `metanorma-standoc` we do release on tag it means that we don't run `rake` on tags

I need to think how to make it work without duplication of existing configuration

**Comment by opoudjis** [comment]
This is still happening on standoc.

**Comment by opoudjis** [comment]
Now happening with isodoc: https://github.com/metanorma/isodoc/actions/runs/10876562482

**Comment by opoudjis** [comment]
@CAMOBAP This is *still* happening, two months after the ticket was raised:

https://github.com/metanorma/isodoc/actions/runs/11098531722

This has to be fixed. PRs during the fortnight are running successfully, but the integration testing that we need to do is being ignored. Even though I need the releases to happen without integration testing for timely release, the tests still do need to be run.

**Comment by CAMOBAP** [comment]
Fixe on metanorma/ci side for `isodoc` and `metanorma-standoc`

Tested on `isodoc` https://github.com/metanorma/isodoc/actions/runs/11098531722/job/30835391453
