### ISSUE TITLE
Issues with machine-readable requirement syntax

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#94]
Problems remaining now:

* Requirement ID not showing
* Requirement obligation not showing
* Requirement "type" not showing
* Accept both `[.requirement,...]` and `[requirement,...]` syntaxes
* Find out why original table rendering didn't work.

These issues apply to metanorma-standoc as well.

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-ogc/issues/44#issuecomment-517154953_

**Comment by opoudjis** [comment]
In addition:

Add "Permission/Requirement/Recommendation" label even if there is no anchor identifier (inherited checking from OGC).

**Comment by opoudjis** [comment]
> Find out why original table rendering didn't work.

Addressed in https://github.com/metanorma/metanorma-ogc/issues/44: the original legacy table encoding of OGC requirements presupposed only one row of the table, the tables in the new document used two rows, and Ronald has decided to suppress the table representation, rather than deal with this visual rendering-driven inconsistency.

**Comment by opoudjis** [comment]
> Accept both [.requirement,...] and [requirement,...] syntaxes

Already done in Standoc. Had added in OGC, but have since done away with the legacy representation.

**Comment by opoudjis** [comment]
The example Ronald has brought up is:

````
[requirement,type="general",id="/req/pipelineml-conceptual/similarity",obligation="shall"]
====
This is a test. An encoding, when claiming compliance with this conceptual model, SHALL implement its components (classes, attributes, relationships) respecting the conceptual model definitions and intent, such that high semantic similarity is obtained between the encoding and conceptual model components.
====
````

@ronaldtse, I don't know where you got that example from, but it does not reflect the implementation, as it has been documented in https://www.metanorma.com/author/topics/document-format/requirements-recommendations-permissions/

In other words, RTFM :-/

````
[.recommendation,label="/ogc/recommendation/wfs/2",subject="user",inherit="/ss/584/2015/level/1",classification="control-class:Technical;priority:P0;family:System and Communications Protection,System and Communications Protocols",obligation="permission,recommendation"]
====
I recommend this
==== 
````

> Requirement ID not showing

The attribute should not be called "id", but "label", which is rendered.

> Requirement "type" not showing

There is no "type" attribute; there is "classification", which is a series of key-value pairs. They are not currently rendered, and I do not believe we should be rendering a whole series of key-value pairs. Recall that we have deliberately left several attributes of machine readable requirement unrendered: the subject of the requirement, the obligation, the inherit label.

THIS WAS DELIBERATE, and we decided so at the time, in January. I think rendering these would be a mistake: they will look disgusting, and will add very little value to a printed standard. If you do not come up with an elegant way of representing these three attributes in print, I will close this ticket.

The following is NOT an elegant way of representing these three attributes. It is also the only way I can think of:

> **Recommendation 1**        
> **/ogc/recommendation/wfs/2**
> _Subject: user_
> _Obligation: permission, recommendation_
> _control-class: Technical_
> _priority: P0_
> _family: System and Communications Protection, System and Communications Protocols_
> 
> I recommend this

**Comment by ronaldtse** [comment]
@opoudjis the syntax I used was from the metanorma-mrr-samples repository. It was generating the correct output, that’s why I put it here.

**Comment by ronaldtse** [comment]
The rendering of requirement attributes are obviously flavor-dependent. The generic/base type of rendering could use your sole example, it’s not that bad.

**Comment by opoudjis** [comment]
> @opoudjis the syntax I used was from the metanorma-mrr-samples repository. It was generating the correct output, that’s why I put it here.

Great, now I have another repository to maintain that I'd completely forgotten about. It's almost like this project is trying to drive me insane.

For God's sake, can I get rid of metanorma-mrr-samples?

**Comment by opoudjis** [comment]
> The generic/base type of rendering could use your sole example, it’s not that bad.

Yuck.

Implementing in isodoc.

**Comment by ronaldtse** [comment]
@opoudjis if you want to get rid of metanorma-mrr-samples, what do you propose we do in its place?

Converted its internals into "real" metanorma tests/specs? Move them to metanorma.com as examples?

**Comment by opoudjis** [comment]
If you want to showcase the requirements language outside of metanorma, then there is a case for leaving this separate. You tell me.

Otherwise, they should move to tests, with maybe an instance in isodoc-rice (which is meant to illustrate all of Metanorma) and an instance in metanorma.com.
