### ISSUE TITLE
Remove strict latexml check

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-standoc#96]
Probably this line https://github.com/metanorma/metanorma-standoc/commit/e5d5e0767984b4c817c2628d2ba78605cbcf3939#diff-219484aaca85c392d091b0f8af538cdeR12 isn't a good idea for those users who don't work with standoc documents because it force users to install latexml

**Comment by opoudjis** [comment]
... All users who use any Metanorma gem use Metanorma-standoc, it is the base class gem. Not all such users are going to use latex, but that is a different issue.

**Comment by ronaldtse** [comment]
@camobap795 I agree that for users who don’t use latexmath, they should not be forced to have LaTeXML. This applies across Metanorma and not only to one specific flavor.

**Comment by CAMOBAP795** [comment]
Done
