### ISSUE TITLE
Try JSON Path-style keys for Metanorma AsciiBib

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#97]
Metanorma AsciiBib is now compromised by the fact that Asciidoctor definition lists cannot reliably nest more than three levels deep. As a workaround, we will attempt JSON Path-style keys for the definition lists, which will allow them to stay only one level deep:

From

````
contributor::
        role::: author
        person:::
          name::::
      +
      --
      completename::
        language::: en
        content::: Fred
      --
````

to 

````
contributor.role:: author
contributor.person.name.completename.language:: en
contributor.person.name.completename.language.content:: Fred
````

**Comment by ronaldtse** [comment]
Or something like `toml`:

```
[asciibib,contributor]
role:: author

[asciibib,contributor.person.name.completename]
language:: en
language.content:: Fred 
```
?

**Comment by opoudjis** [comment]
Also documented in relaton-bib/hash.adoc.

Just saw your toml alternative. Rejected. Harder to parse, and I'm not seeing a compelling case for it. What I have just done works, let's leave it alone for now...

**Comment by ronaldtse** [comment]
Agreed. Thanks!
